/* tslint:disable */
/* eslint-disable */
/**
 * efs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreatePermissionRuleRequest
 */
export interface CreatePermissionRuleRequest {

    /**
     * @type {string}
     * @memberof CreatePermissionRuleRequest
     */
    CidrIp: string;

    /**
     * @type {string}
     * @memberof CreatePermissionRuleRequest
     */
    PermissionGroupId: string;

    /**
     * @type {string}
     * @memberof CreatePermissionRuleRequest
     */
    RwMode: CreatePermissionRuleRequestRwModeEnum;

    /**
     * @type {string}
     * @memberof CreatePermissionRuleRequest
     */
    UserMode: CreatePermissionRuleRequestUserModeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreatePermissionRuleRequestRwModeEnum {
    Unknown = 'Unknown',
    RW = 'RW',
    RO = 'RO'
}
/**
 * @export
 * @enum {string}
 */
export enum CreatePermissionRuleRequestUserModeEnum {
    Unknown = 'Unknown',
    RootSquash = 'Root_squash',
    NoRootSquash = 'No_root_squash',
    AllSquash = 'All_squash'
}

