/* tslint:disable */
/* eslint-disable */
/**
 * efs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateFileSystemRequest
 */
export interface UpdateFileSystemRequest {

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    BandwidthMode?: UpdateFileSystemRequestBandwidthModeEnum;

    /**
     * @type {number}
     * @memberof UpdateFileSystemRequest
     */
    BurstBandwidth?: number;

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    FileSystemId: string;

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    FileSystemName?: string;

    /**
     * @type {number}
     * @memberof UpdateFileSystemRequest
     */
    ProvisionedBandwidth?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateFileSystemRequestBandwidthModeEnum {
    Unknown = 'Unknown',
    Baseline = 'Baseline',
    Provisioned = 'Provisioned'
}

