/* tslint:disable */
/* eslint-disable */
/**
 * clawsentry
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BaseForCreateClawInput } from './base-for-create-claw-input';
 /**
 * 
 *
 * @export
 * @interface CreateClawRequest
 */
export interface CreateClawRequest {

    /**
     * @type {BaseForCreateClawInput}
     * @memberof CreateClawRequest
     */
    Base?: BaseForCreateClawInput;

    /**
     * @type {string}
     * @memberof CreateClawRequest
     */
    ClawType?: CreateClawRequestClawTypeEnum;

    /**
     * @type {string}
     * @memberof CreateClawRequest
     */
    ExternalClawID: string;

    /**
     * @type {string}
     * @memberof CreateClawRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof CreateClawRequest
     */
    Source?: CreateClawRequestSourceEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateClawRequestClawTypeEnum {
    Arkclaw = 'arkclaw',
    Openclaw = 'openclaw',
    Hermes = 'hermes',
    Hibot = 'hibot',
    Doubao = 'doubao',
    Opencode = 'opencode',
    Codex = 'codex',
    Coco = 'coco',
    Trae = 'trae'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateClawRequestSourceEnum {
    Arkclaw = 'arkclaw',
    ThirdParty = 'third_party',
    Hibot = 'hibot'
}

