/* tslint:disable */
/* eslint-disable */
/**
 * resourcecenter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QueryForListQueriesOutput
 */
export interface QueryForListQueriesOutput {

    /**
     * @type {string}
     * @memberof QueryForListQueriesOutput
     */
    CreatedTime?: string;

    /**
     * @type {string}
     * @memberof QueryForListQueriesOutput
     */
    Description?: string;

    /**
     * @type {number}
     * @memberof QueryForListQueriesOutput
     */
    QueryID?: number;

    /**
     * @type {string}
     * @memberof QueryForListQueriesOutput
     */
    QueryName?: string;

    /**
     * @type {string}
     * @memberof QueryForListQueriesOutput
     */
    UpdatedTime?: string;
}
