/* tslint:disable */
/* eslint-disable */
/**
 * cloud_trail
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TosConfigForListBackfillDeliveryTasksOutput
 */
export interface TosConfigForListBackfillDeliveryTasksOutput {

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    BucketName?: string;

    /**
     * @type {boolean}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    Enabled?: boolean;

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    KMSKeyID?: string;

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    KeyPrefix?: string;

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    Region?: string;

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    SSEAlgorithm?: string;

    /**
     * @type {number}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    TosAccountId?: number;

    /**
     * @type {string}
     * @memberof TosConfigForListBackfillDeliveryTasksOutput
     */
    TosWriteRoleTrn?: string;
}
