/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChangeObjectForSyncAllowListOutput
 */
export interface ChangeObjectForSyncAllowListOutput {

    /**
     * @type {Array<string>}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    AddedIpList?: Array<string>;

    /**
     * @type {string}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    BindMode?: ChangeObjectForSyncAllowListOutputBindModeEnum;

    /**
     * @type {boolean}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    HasChanged?: boolean;

    /**
     * @type {boolean}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    HasDeleted?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    NewIpList?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    OldIpList?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    RemovedIpList?: Array<string>;

    /**
     * @type {string}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    SecurityGroupId?: string;

    /**
     * @type {string}
     * @memberof ChangeObjectForSyncAllowListOutput
     */
    SecurityGroupName?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ChangeObjectForSyncAllowListOutputBindModeEnum {
    AssociateEcsIp = 'AssociateEcsIp',
    IngressDirectionIp = 'IngressDirectionIp'
}

