/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilterForDescribeClientSessionSnapshotInput
 */
export interface FilterForDescribeClientSessionSnapshotInput {

    /**
     * @type {string}
     * @memberof FilterForDescribeClientSessionSnapshotInput
     */
    FilterKey?: string;

    /**
     * @type {string}
     * @memberof FilterForDescribeClientSessionSnapshotInput
     */
    FilterValue?: string;
}
