/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TaskStepInfoForDescribeTasksOutput
 */
export interface TaskStepInfoForDescribeTasksOutput {

    /**
     * @type {string}
     * @memberof TaskStepInfoForDescribeTasksOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof TaskStepInfoForDescribeTasksOutput
     */
    ProgressDesc?: string;

    /**
     * @type {number}
     * @memberof TaskStepInfoForDescribeTasksOutput
     */
    StepProgress?: number;

    /**
     * @type {string}
     * @memberof TaskStepInfoForDescribeTasksOutput
     */
    StepStatus?: TaskStepInfoForDescribeTasksOutputStepStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TaskStepInfoForDescribeTasksOutputStepStatusEnum {
    Running = 'Running',
    Success = 'Success',
    Failed = 'Failed',
    Waiting = 'Waiting'
}

