/* tslint:disable */
/* eslint-disable */
/**
 * milvus
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChargeConfigForMSDescribeInstancesOutput } from './charge-config-for-msdescribe-instances-output';
import { NetworkConfigForMSDescribeInstancesOutput } from './network-config-for-msdescribe-instances-output';
 /**
 * 
 *
 * @export
 * @interface InstanceInfoForMSDescribeInstancesOutput
 */
export interface InstanceInfoForMSDescribeInstancesOutput {

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    AccountId?: string;

    /**
     * @type {ChargeConfigForMSDescribeInstancesOutput}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    ChargeConfig?: ChargeConfigForMSDescribeInstancesOutput;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    CreateTime?: string;

    /**
     * @type {boolean}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    DeleteProtectEnabled?: boolean;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    InstanceName?: string;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    InstanceVersion?: InstanceInfoForMSDescribeInstancesOutputInstanceVersionEnum;

    /**
     * @type {NetworkConfigForMSDescribeInstancesOutput}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    NetworkConfig?: NetworkConfigForMSDescribeInstancesOutput;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    Region?: string;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    Status?: InstanceInfoForMSDescribeInstancesOutputStatusEnum;

    /**
     * @type {string}
     * @memberof InstanceInfoForMSDescribeInstancesOutput
     */
    UpdateTime?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum InstanceInfoForMSDescribeInstancesOutputInstanceVersionEnum {
    V25 = 'V2_5',
    V26 = 'V2_6'
}
/**
 * @export
 * @enum {string}
 */
export enum InstanceInfoForMSDescribeInstancesOutputStatusEnum {
    SemiInit = 'SemiInit',
    SemiCreating = 'SemiCreating',
    SemiCreateFailed = 'SemiCreateFailed',
    SemiCreated = 'SemiCreated',
    SemiReleasing = 'SemiReleasing',
    SemiReleased = 'SemiReleased',
    Init = 'Init',
    WaitingPaid = 'WaitingPaid',
    WaitCreate = 'WaitCreate',
    Creating = 'Creating',
    Running = 'Running',
    Updating = 'Updating',
    WaitRelease = 'WaitRelease',
    Releasing = 'Releasing',
    Released = 'Released',
    CreateFailed = 'CreateFailed',
    Error = 'Error'
}

