/* tslint:disable */
/* eslint-disable */
/**
 * milvus
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SubnetInfoForMSCreateInstanceOneStepInput } from './subnet-info-for-mscreate-instance-one-step-input';
import { VpcInfoForMSCreateInstanceOneStepInput } from './vpc-info-for-mscreate-instance-one-step-input';
 /**
 * 
 *
 * @export
 * @interface NetworkConfigForMSCreateInstanceOneStepInput
 */
export interface NetworkConfigForMSCreateInstanceOneStepInput {

    /**
     * @type {boolean}
     * @memberof NetworkConfigForMSCreateInstanceOneStepInput
     */
    HttpsEnabled?: boolean;

    /**
     * @type {boolean}
     * @memberof NetworkConfigForMSCreateInstanceOneStepInput
     */
    InnerEndpointEnabled?: boolean;

    /**
     * @type {string}
     * @memberof NetworkConfigForMSCreateInstanceOneStepInput
     */
    IpVersion?: NetworkConfigForMSCreateInstanceOneStepInputIpVersionEnum;

    /**
     * @type {SubnetInfoForMSCreateInstanceOneStepInput}
     * @memberof NetworkConfigForMSCreateInstanceOneStepInput
     */
    SubnetInfo?: SubnetInfoForMSCreateInstanceOneStepInput;

    /**
     * @type {VpcInfoForMSCreateInstanceOneStepInput}
     * @memberof NetworkConfigForMSCreateInstanceOneStepInput
     */
    VpcInfo?: VpcInfoForMSCreateInstanceOneStepInput;
}

/**
 * @export
 * @enum {string}
 */
export enum NetworkConfigForMSCreateInstanceOneStepInputIpVersionEnum {
    IPv4 = 'IPv4',
    DualStack = 'DualStack'
}

