/* tslint:disable */
/* eslint-disable */
/**
 * milvus
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConfigForDMUpdateWorkflowInput } from './config-for-dmupdate-workflow-input';
import { OptionsForDMUpdateWorkflowInput } from './options-for-dmupdate-workflow-input';
 /**
 * 
 *
 * @export
 * @interface TransformForDMUpdateWorkflowInput
 */
export interface TransformForDMUpdateWorkflowInput {

    /**
     * @type {ConfigForDMUpdateWorkflowInput}
     * @memberof TransformForDMUpdateWorkflowInput
     */
    Config?: ConfigForDMUpdateWorkflowInput;

    /**
     * @type {string}
     * @memberof TransformForDMUpdateWorkflowInput
     */
    Operator?: string;

    /**
     * @type {OptionsForDMUpdateWorkflowInput}
     * @memberof TransformForDMUpdateWorkflowInput
     */
    Options?: OptionsForDMUpdateWorkflowInput;
}
