/* tslint:disable */
/* eslint-disable */
/**
 * volcsms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ShortUrlConfigForListSecondTemplateOutput } from './short-url-config-for-list-second-template-output';
import { TemplateParamForListSecondTemplateOutput } from './template-param-for-list-second-template-output';
 /**
 * 
 *
 * @export
 * @interface ListForListSecondTemplateOutput
 */
export interface ListForListSecondTemplateOutput {

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    area?: ListForListSecondTemplateOutputAreaEnum;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    channelType?: ListForListSecondTemplateOutputChannelTypeEnum;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    content?: string;

    /**
     * @type {number}
     * @memberof ListForListSecondTemplateOutput
     */
    createdAt?: number;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    description?: string;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    name?: string;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    project?: string;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    secondTemplateId?: string;

    /**
     * @type {ShortUrlConfigForListSecondTemplateOutput}
     * @memberof ListForListSecondTemplateOutput
     */
    shortUrlConfig?: ShortUrlConfigForListSecondTemplateOutput;

    /**
     * @type {Array<string>}
     * @memberof ListForListSecondTemplateOutput
     */
    signatures?: Array<string>;

    /**
     * @type {number}
     * @memberof ListForListSecondTemplateOutput
     */
    status?: number;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    statusDescription?: string;

    /**
     * @type {Array<string>}
     * @memberof ListForListSecondTemplateOutput
     */
    subAccounts?: Array<string>;

    /**
     * @type {string}
     * @memberof ListForListSecondTemplateOutput
     */
    templateId?: string;

    /**
     * @type {Array<TemplateParamForListSecondTemplateOutput>}
     * @memberof ListForListSecondTemplateOutput
     */
    templateParams?: Array<TemplateParamForListSecondTemplateOutput>;

    /**
     * @type {number}
     * @memberof ListForListSecondTemplateOutput
     */
    updatedAt?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ListForListSecondTemplateOutputAreaEnum {
    Cn = 'cn'
}
/**
 * @export
 * @enum {string}
 */
export enum ListForListSecondTemplateOutputChannelTypeEnum {
    CNOTP = 'CN_OTP',
    CNNTC = 'CN_NTC',
    CNMKT = 'CN_MKT'
}

