/* tslint:disable */
/* eslint-disable */
/**
 * volcsms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListForListSmsSendLogForAgentOutput
 */
export interface ListForListSmsSendLogForAgentOutput {

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    Account?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    ChannelType?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    Content?: string;

    /**
     * @type {number}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    Count?: number;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    ErrorCode?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    ErrorMessage?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    ErrorType?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    MessageId?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    Mobile?: string;

    /**
     * @type {number}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    ReceiptTime?: number;

    /**
     * @type {number}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    SendTime?: number;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    Signature?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    SubAccount?: string;

    /**
     * @type {string}
     * @memberof ListForListSmsSendLogForAgentOutput
     */
    TemplateId?: string;
}
