/* tslint:disable */
/* eslint-disable */
/**
 * volcsms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ShortUrlConfigForListSecondTemplateOutput
 */
export interface ShortUrlConfigForListSecondTemplateOutput {

    /**
     * @type {string}
     * @memberof ShortUrlConfigForListSecondTemplateOutput
     */
    belong?: string;

    /**
     * @type {string}
     * @memberof ShortUrlConfigForListSecondTemplateOutput
     */
    isEnabled?: string;

    /**
     * @type {string}
     * @memberof ShortUrlConfigForListSecondTemplateOutput
     */
    isNeedClickDetails?: string;

    /**
     * @type {number}
     * @memberof ShortUrlConfigForListSecondTemplateOutput
     */
    uaCheckStrategy?: number;
}
