/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ColumnForListSolutionsOutput
 */
export interface ColumnForListSolutionsOutput {

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    DefaultValue?: string;

    /**
     * @type {boolean}
     * @memberof ColumnForListSolutionsOutput
     */
    DefaultValueRawExpression?: boolean;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    IsAdditionalColumn?: string;

    /**
     * @type {boolean}
     * @memberof ColumnForListSolutionsOutput
     */
    IsPartitionColumn?: boolean;

    /**
     * @type {boolean}
     * @memberof ColumnForListSolutionsOutput
     */
    IsPrimaryKey?: boolean;

    /**
     * @type {number}
     * @memberof ColumnForListSolutionsOutput
     */
    Length?: number;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    Name?: string;

    /**
     * @type {boolean}
     * @memberof ColumnForListSolutionsOutput
     */
    Nullable?: boolean;

    /**
     * @type {number}
     * @memberof ColumnForListSolutionsOutput
     */
    Precision?: number;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    Properties?: string;

    /**
     * @type {number}
     * @memberof ColumnForListSolutionsOutput
     */
    Scale?: number;

    /**
     * @type {Array<string>}
     * @memberof ColumnForListSolutionsOutput
     */
    SupportTypeList?: Array<string>;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    Type?: string;

    /**
     * @type {string}
     * @memberof ColumnForListSolutionsOutput
     */
    Value?: string;
}
