/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertTaskConfigForCreateSolutionInput } from './convert-task-config-for-create-solution-input';
import { DataSourceConfigForCreateSolutionInput } from './data-source-config-for-create-solution-input';
import { EngineConfigForCreateSolutionInput } from './engine-config-for-create-solution-input';
import { EnvConfigForCreateSolutionInput } from './env-config-for-create-solution-input';
import { IdentifierMappingRuleForCreateSolutionInput } from './identifier-mapping-rule-for-create-solution-input';
import { SyncStrategyForCreateSolutionInput } from './sync-strategy-for-create-solution-input';
import { TableMappingConfigForCreateSolutionInput } from './table-mapping-config-for-create-solution-input';
import { TaskNameMappingRuleForCreateSolutionInput } from './task-name-mapping-rule-for-create-solution-input';
import { TopicMappingConfigForCreateSolutionInput } from './topic-mapping-config-for-create-solution-input';
 /**
 * 
 *
 * @export
 * @interface ConfForCreateSolutionInput
 */
export interface ConfForCreateSolutionInput {

    /**
     * @type {string}
     * @memberof ConfForCreateSolutionInput
     */
    ColumnMappingRules?: string;

    /**
     * @type {DataSourceConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    DataSourceConfig?: DataSourceConfigForCreateSolutionInput;

    /**
     * @type {EngineConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    EngineConfig?: EngineConfigForCreateSolutionInput;

    /**
     * @type {EnvConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    EnvConfig?: EnvConfigForCreateSolutionInput;

    /**
     * @type {IdentifierMappingRuleForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    IdentifierMappingRule?: IdentifierMappingRuleForCreateSolutionInput;

    /**
     * @type {SyncStrategyForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    SyncStrategy?: SyncStrategyForCreateSolutionInput;

    /**
     * @type {TableMappingConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    TableMappingConfig?: TableMappingConfigForCreateSolutionInput;

    /**
     * @type {ConvertTaskConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    TaskConfig?: ConvertTaskConfigForCreateSolutionInput;

    /**
     * @type {TaskNameMappingRuleForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    TaskNameMappingRule?: TaskNameMappingRuleForCreateSolutionInput;

    /**
     * @type {TopicMappingConfigForCreateSolutionInput}
     * @memberof ConfForCreateSolutionInput
     */
    TopicMappingConfig?: TopicMappingConfigForCreateSolutionInput;
}
