/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertTaskConfigForGetSolutionExecutionOutput } from './convert-task-config-for-get-solution-execution-output';
import { DataSourceConfigForGetSolutionExecutionOutput } from './data-source-config-for-get-solution-execution-output';
import { EngineConfigForGetSolutionExecutionOutput } from './engine-config-for-get-solution-execution-output';
import { EnvConfigForGetSolutionExecutionOutput } from './env-config-for-get-solution-execution-output';
import { IdentifierMappingRuleForGetSolutionExecutionOutput } from './identifier-mapping-rule-for-get-solution-execution-output';
import { SyncStrategyForGetSolutionExecutionOutput } from './sync-strategy-for-get-solution-execution-output';
import { TableMappingConfigForGetSolutionExecutionOutput } from './table-mapping-config-for-get-solution-execution-output';
import { TaskNameMappingRuleForGetSolutionExecutionOutput } from './task-name-mapping-rule-for-get-solution-execution-output';
import { TopicMappingConfigForGetSolutionExecutionOutput } from './topic-mapping-config-for-get-solution-execution-output';
 /**
 * 
 *
 * @export
 * @interface ConfForGetSolutionExecutionOutput
 */
export interface ConfForGetSolutionExecutionOutput {

    /**
     * @type {string}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    ColumnMappingRules?: string;

    /**
     * @type {DataSourceConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    DataSourceConfig?: DataSourceConfigForGetSolutionExecutionOutput;

    /**
     * @type {EngineConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    EngineConfig?: EngineConfigForGetSolutionExecutionOutput;

    /**
     * @type {EnvConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    EnvConfig?: EnvConfigForGetSolutionExecutionOutput;

    /**
     * @type {IdentifierMappingRuleForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    IdentifierMappingRule?: IdentifierMappingRuleForGetSolutionExecutionOutput;

    /**
     * @type {SyncStrategyForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    SyncStrategy?: SyncStrategyForGetSolutionExecutionOutput;

    /**
     * @type {TableMappingConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    TableMappingConfig?: TableMappingConfigForGetSolutionExecutionOutput;

    /**
     * @type {ConvertTaskConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    TaskConfig?: ConvertTaskConfigForGetSolutionExecutionOutput;

    /**
     * @type {TaskNameMappingRuleForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    TaskNameMappingRule?: TaskNameMappingRuleForGetSolutionExecutionOutput;

    /**
     * @type {TopicMappingConfigForGetSolutionExecutionOutput}
     * @memberof ConfForGetSolutionExecutionOutput
     */
    TopicMappingConfig?: TopicMappingConfigForGetSolutionExecutionOutput;
}
