/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PartitionForListSolutionsOutput } from './partition-for-list-solutions-output';
import { PropertyForListSolutionsOutput } from './property-for-list-solutions-output';
import { SortStrategyForListSolutionsOutput } from './sort-strategy-for-list-solutions-output';
 /**
 * 
 *
 * @export
 * @interface ConvertParameterForListSolutionsOutput
 */
export interface ConvertParameterForListSolutionsOutput {

    /**
     * @type {Array<PartitionForListSolutionsOutput>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    Columns?: Array<PartitionForListSolutionsOutput>;

    /**
     * @type {string}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    DatabaseName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    OrderByKeys?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    PartitionKeys?: Array<string>;

    /**
     * @type {number}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    ProjectId?: number;

    /**
     * @type {Array<PropertyForListSolutionsOutput>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    Properties?: Array<PropertyForListSolutionsOutput>;

    /**
     * @type {string}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    SchemaName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    ShardingKeys?: Array<string>;

    /**
     * @type {SortStrategyForListSolutionsOutput}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    SortStrategy?: SortStrategyForListSolutionsOutput;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    SplitKeys?: Array<string>;

    /**
     * @type {string}
     * @memberof ConvertParameterForListSolutionsOutput
     */
    TableName?: string;
}
