/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PartitionForUpdateSolutionInput } from './partition-for-update-solution-input';
import { PropertyForUpdateSolutionInput } from './property-for-update-solution-input';
import { SortStrategyForUpdateSolutionInput } from './sort-strategy-for-update-solution-input';
 /**
 * 
 *
 * @export
 * @interface ConvertParameterForUpdateSolutionInput
 */
export interface ConvertParameterForUpdateSolutionInput {

    /**
     * @type {Array<PartitionForUpdateSolutionInput>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    Columns?: Array<PartitionForUpdateSolutionInput>;

    /**
     * @type {string}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    DatabaseName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    OrderByKeys?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    PartitionKeys?: Array<string>;

    /**
     * @type {number}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    ProjectId?: number;

    /**
     * @type {Array<PropertyForUpdateSolutionInput>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    Properties?: Array<PropertyForUpdateSolutionInput>;

    /**
     * @type {string}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    SchemaName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    ShardingKeys?: Array<string>;

    /**
     * @type {SortStrategyForUpdateSolutionInput}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    SortStrategy?: SortStrategyForUpdateSolutionInput;

    /**
     * @type {Array<string>}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    SplitKeys?: Array<string>;

    /**
     * @type {string}
     * @memberof ConvertParameterForUpdateSolutionInput
     */
    TableName?: string;
}
