/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DdlForUpdateSolutionTableMappingsInput
 */
export interface DdlForUpdateSolutionTableMappingsInput {

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    AddTableColumn?: DdlForUpdateSolutionTableMappingsInputAddTableColumnEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    CreateTable?: DdlForUpdateSolutionTableMappingsInputCreateTableEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    DropTable?: DdlForUpdateSolutionTableMappingsInputDropTableEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    DropTableColumn?: DdlForUpdateSolutionTableMappingsInputDropTableColumnEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    RenameTable?: DdlForUpdateSolutionTableMappingsInputRenameTableEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    RenameTableColumn?: DdlForUpdateSolutionTableMappingsInputRenameTableColumnEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    TruncateTable?: DdlForUpdateSolutionTableMappingsInputTruncateTableEnum;

    /**
     * @type {string}
     * @memberof DdlForUpdateSolutionTableMappingsInput
     */
    UpdateTableColumn?: DdlForUpdateSolutionTableMappingsInputUpdateTableColumnEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputAddTableColumnEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputCreateTableEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputDropTableEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputDropTableColumnEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputRenameTableEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputRenameTableColumnEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputTruncateTableEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}
/**
 * @export
 * @enum {string}
 */
export enum DdlForUpdateSolutionTableMappingsInputUpdateTableColumnEnum {
    EXECUTE = 'EXECUTE',
    IGNORE = 'IGNORE',
    FAIL = 'FAIL',
    LOG = 'LOG'
}

