/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EnvConfigForListSolutionsOutput
 */
export interface EnvConfigForListSolutionsOutput {

    /**
     * @type {number}
     * @memberof EnvConfigForListSolutionsOutput
     */
    FolderId?: number;

    /**
     * @type {number}
     * @memberof EnvConfigForListSolutionsOutput
     */
    ProjectId?: number;
}
