/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertConvertParameterForUpdateSolutionInput } from './convert-convert-parameter-for-update-solution-input';
 /**
 * 
 *
 * @export
 * @interface InternalForUpdateSolutionInput
 */
export interface InternalForUpdateSolutionInput {

    /**
     * @type {number}
     * @memberof InternalForUpdateSolutionInput
     */
    DataSourceId?: number;

    /**
     * @type {ConvertConvertParameterForUpdateSolutionInput}
     * @memberof InternalForUpdateSolutionInput
     */
    Parameter?: ConvertConvertParameterForUpdateSolutionInput;
}
