/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ItemForListDataSourcesOutput
 */
export interface ItemForListDataSourcesOutput {

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Conf?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    CreateUserId?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    CreateUserName?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    DataSourceType?: ItemForListDataSourcesOutputDataSourceTypeEnum;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    DisplayType?: string;

    /**
     * @type {number}
     * @memberof ItemForListDataSourcesOutput
     */
    Id?: number;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Idc?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Item?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    OwnerUserName?: string;

    /**
     * @type {number}
     * @memberof ItemForListDataSourcesOutput
     */
    ProjectId?: number;

    /**
     * @type {number}
     * @memberof ItemForListDataSourcesOutput
     */
    Status?: number;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    SubItem?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    Subtype?: ItemForListDataSourcesOutputSubtypeEnum;

    /**
     * @type {number}
     * @memberof ItemForListDataSourcesOutput
     */
    TenantId?: number;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    TestConf?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListDataSourcesOutput
     */
    UpdateUserId?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ItemForListDataSourcesOutputDataSourceTypeEnum {
    Abase = 'abase',
    Bmq = 'bmq',
    Bytees = 'bytees',
    BytehouseCdw = 'bytehouse_cdw',
    BytehouseCe = 'bytehouse_ce',
    Cfs = 'cfs',
    Clickhouse = 'clickhouse',
    Datasail = 'datasail',
    Doris = 'doris',
    Es = 'es',
    Ftp = 'ftp',
    Gaussdb = 'gaussdb',
    Gbase8s = 'gbase8s',
    Greenplum = 'greenplum',
    Hana = 'hana',
    Hbase = 'hbase',
    Hdfs = 'hdfs',
    Hive = 'hive',
    Hudi = 'hudi',
    Iceberg = 'iceberg',
    Kafka = 'kafka',
    Kudu = 'kudu',
    Lance = 'lance',
    Larksheet = 'larksheet',
    Las = 'las',
    MaxCompute = 'max_compute',
    Mongo = 'mongo',
    Mysql = 'mysql',
    MysqlSharding = 'mysql_sharding',
    Oceanbase = 'oceanbase',
    Oracle = 'oracle',
    Oss = 'oss',
    Paimon = 'paimon',
    Pg = 'pg',
    Redis = 'redis',
    RestApi = 'rest_api',
    Rocketmq = 'rocketmq',
    SqlServer = 'sql_server',
    Ssh = 'ssh',
    Starrocks = 'starrocks',
    Tdengine = 'tdengine',
    Tidb = 'tidb',
    Tls = 'tls',
    Tos = 'tos',
    Vedb = 'vedb',
    Vikingdb = 'vikingdb'
}
/**
 * @export
 * @enum {string}
 */
export enum ItemForListDataSourcesOutputSubtypeEnum {
    Default = 'default',
    VolcEngine = 'volc_engine',
    Emr = 'emr',
    EmrServerless = 'emr_serverless',
    VikingdbVector = 'vikingdb_vector'
}

