/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterExpsForUpdateSolutionInput } from './filter-exps-for-update-solution-input';
import { LogicCatalogMetaForUpdateSolutionInput } from './logic-catalog-meta-for-update-solution-input';
import { ParameterForUpdateSolutionInput } from './parameter-for-update-solution-input';
import { ReaderForUpdateSolutionInput } from './reader-for-update-solution-input';
 /**
 * 
 *
 * @export
 * @interface LogicReaderForUpdateSolutionInput
 */
export interface LogicReaderForUpdateSolutionInput {

    /**
     * @type {string}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    BinlogType?: LogicReaderForUpdateSolutionInputBinlogTypeEnum;

    /**
     * @type {FilterExpsForUpdateSolutionInput}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    FilterExps?: FilterExpsForUpdateSolutionInput;

    /**
     * @type {LogicCatalogMetaForUpdateSolutionInput}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    LogicCatalogMeta?: LogicCatalogMetaForUpdateSolutionInput;

    /**
     * @type {ParameterForUpdateSolutionInput}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    Parameter?: ParameterForUpdateSolutionInput;

    /**
     * @type {string}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    ReaderTableMode?: LogicReaderForUpdateSolutionInputReaderTableModeEnum;

    /**
     * @type {Array<ReaderForUpdateSolutionInput>}
     * @memberof LogicReaderForUpdateSolutionInput
     */
    Readers?: Array<ReaderForUpdateSolutionInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForUpdateSolutionInputBinlogTypeEnum {
    DEBEZIUMJSON = 'DEBEZIUM_JSON',
    CANALPROTO = 'CANAL_PROTO'
}
/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForUpdateSolutionInputReaderTableModeEnum {
    STATICTABLESPECIFIED = 'STATIC_TABLE_SPECIFIED',
    DYNAMICTABLEREGULAR = 'DYNAMIC_TABLE_REGULAR'
}

