/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterExpsForUpdateSolutionTableMappingsInput } from './filter-exps-for-update-solution-table-mappings-input';
import { LogicCatalogMetaForUpdateSolutionTableMappingsInput } from './logic-catalog-meta-for-update-solution-table-mappings-input';
import { ParameterForUpdateSolutionTableMappingsInput } from './parameter-for-update-solution-table-mappings-input';
import { ReaderForUpdateSolutionTableMappingsInput } from './reader-for-update-solution-table-mappings-input';
 /**
 * 
 *
 * @export
 * @interface LogicReaderForUpdateSolutionTableMappingsInput
 */
export interface LogicReaderForUpdateSolutionTableMappingsInput {

    /**
     * @type {string}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    BinlogType?: LogicReaderForUpdateSolutionTableMappingsInputBinlogTypeEnum;

    /**
     * @type {FilterExpsForUpdateSolutionTableMappingsInput}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    FilterExps?: FilterExpsForUpdateSolutionTableMappingsInput;

    /**
     * @type {LogicCatalogMetaForUpdateSolutionTableMappingsInput}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    LogicCatalogMeta?: LogicCatalogMetaForUpdateSolutionTableMappingsInput;

    /**
     * @type {ParameterForUpdateSolutionTableMappingsInput}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    Parameter?: ParameterForUpdateSolutionTableMappingsInput;

    /**
     * @type {string}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    ReaderTableMode?: LogicReaderForUpdateSolutionTableMappingsInputReaderTableModeEnum;

    /**
     * @type {Array<ReaderForUpdateSolutionTableMappingsInput>}
     * @memberof LogicReaderForUpdateSolutionTableMappingsInput
     */
    Readers?: Array<ReaderForUpdateSolutionTableMappingsInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForUpdateSolutionTableMappingsInputBinlogTypeEnum {
    DEBEZIUMJSON = 'DEBEZIUM_JSON',
    CANALPROTO = 'CANAL_PROTO'
}
/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForUpdateSolutionTableMappingsInputReaderTableModeEnum {
    STATICTABLESPECIFIED = 'STATIC_TABLE_SPECIFIED',
    DYNAMICTABLEREGULAR = 'DYNAMIC_TABLE_REGULAR'
}

