/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterExpsForGetSolutionExecutionOutput } from './filter-exps-for-get-solution-execution-output';
import { LogicCatalogMetaForGetSolutionExecutionOutput } from './logic-catalog-meta-for-get-solution-execution-output';
import { ParameterForGetSolutionExecutionOutput } from './parameter-for-get-solution-execution-output';
import { ReaderForGetSolutionExecutionOutput } from './reader-for-get-solution-execution-output';
 /**
 * 
 *
 * @export
 * @interface LogicReaderForGetSolutionExecutionOutput
 */
export interface LogicReaderForGetSolutionExecutionOutput {

    /**
     * @type {string}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    BinlogType?: LogicReaderForGetSolutionExecutionOutputBinlogTypeEnum;

    /**
     * @type {FilterExpsForGetSolutionExecutionOutput}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    FilterExps?: FilterExpsForGetSolutionExecutionOutput;

    /**
     * @type {LogicCatalogMetaForGetSolutionExecutionOutput}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    LogicCatalogMeta?: LogicCatalogMetaForGetSolutionExecutionOutput;

    /**
     * @type {ParameterForGetSolutionExecutionOutput}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    Parameter?: ParameterForGetSolutionExecutionOutput;

    /**
     * @type {string}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    ReaderTableMode?: LogicReaderForGetSolutionExecutionOutputReaderTableModeEnum;

    /**
     * @type {Array<ReaderForGetSolutionExecutionOutput>}
     * @memberof LogicReaderForGetSolutionExecutionOutput
     */
    Readers?: Array<ReaderForGetSolutionExecutionOutput>;
}

/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForGetSolutionExecutionOutputBinlogTypeEnum {
    DEBEZIUMJSON = 'DEBEZIUM_JSON',
    CANALPROTO = 'CANAL_PROTO'
}
/**
 * @export
 * @enum {string}
 */
export enum LogicReaderForGetSolutionExecutionOutputReaderTableModeEnum {
    STATICTABLESPECIFIED = 'STATIC_TABLE_SPECIFIED',
    DYNAMICTABLEREGULAR = 'DYNAMIC_TABLE_REGULAR'
}

