/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ColumnForListSolutionTableMappingsOutput } from './column-for-list-solution-table-mappings-output';
 /**
 * 
 *
 * @export
 * @interface ParameterForListSolutionTableMappingsOutput
 */
export interface ParameterForListSolutionTableMappingsOutput {

    /**
     * @type {Array<ColumnForListSolutionTableMappingsOutput>}
     * @memberof ParameterForListSolutionTableMappingsOutput
     */
    Columns?: Array<ColumnForListSolutionTableMappingsOutput>;

    /**
     * @type {string}
     * @memberof ParameterForListSolutionTableMappingsOutput
     */
    LogicDatabaseName?: string;

    /**
     * @type {string}
     * @memberof ParameterForListSolutionTableMappingsOutput
     */
    LogicTableName?: string;

    /**
     * @type {Array<string>}
     * @memberof ParameterForListSolutionTableMappingsOutput
     */
    SplitKeys?: Array<string>;
}
