/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SolutionScheduleGroupForListSolutionsOutput } from './solution-schedule-group-for-list-solutions-output';
 /**
 * 
 *
 * @export
 * @interface ScheduleConfigForListSolutionsOutput
 */
export interface ScheduleConfigForListSolutionsOutput {

    /**
     * @type {SolutionScheduleGroupForListSolutionsOutput}
     * @memberof ScheduleConfigForListSolutionsOutput
     */
    SolutionScheduleGroup?: SolutionScheduleGroupForListSolutionsOutput;
}
