/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SolutionScheduleGroupForGetSolutionExecutionOutput } from './solution-schedule-group-for-get-solution-execution-output';
 /**
 * 
 *
 * @export
 * @interface ScheduleConfigForGetSolutionExecutionOutput
 */
export interface ScheduleConfigForGetSolutionExecutionOutput {

    /**
     * @type {SolutionScheduleGroupForGetSolutionExecutionOutput}
     * @memberof ScheduleConfigForGetSolutionExecutionOutput
     */
    SolutionScheduleGroup?: SolutionScheduleGroupForGetSolutionExecutionOutput;
}
