/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TableNameForListSolutionTableMappingsOutput
 */
export interface TableNameForListSolutionTableMappingsOutput {

    /**
     * @type {string}
     * @memberof TableNameForListSolutionTableMappingsOutput
     */
    FilterAction?: TableNameForListSolutionTableMappingsOutputFilterActionEnum;

    /**
     * @type {string}
     * @memberof TableNameForListSolutionTableMappingsOutput
     */
    FilterPattern?: string;

    /**
     * @type {string}
     * @memberof TableNameForListSolutionTableMappingsOutput
     */
    FilterType?: TableNameForListSolutionTableMappingsOutputFilterTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TableNameForListSolutionTableMappingsOutputFilterActionEnum {
    INCLUDE = 'INCLUDE',
    EXCLUDE = 'EXCLUDE'
}
/**
 * @export
 * @enum {string}
 */
export enum TableNameForListSolutionTableMappingsOutputFilterTypeEnum {
    FULL = 'FULL',
    REG = 'REG'
}

