/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResourceConfigForUpdateSolutionInput } from './resource-config-for-update-solution-input';
import { RuntimeConfigForUpdateSolutionInput } from './runtime-config-for-update-solution-input';
import { ScheduleConfigForUpdateSolutionInput } from './schedule-config-for-update-solution-input';
 /**
 * 
 *
 * @export
 * @interface TaskConfigForUpdateSolutionInput
 */
export interface TaskConfigForUpdateSolutionInput {

    /**
     * @type {string}
     * @memberof TaskConfigForUpdateSolutionInput
     */
    ExecutionMode?: TaskConfigForUpdateSolutionInputExecutionModeEnum;

    /**
     * @type {ResourceConfigForUpdateSolutionInput}
     * @memberof TaskConfigForUpdateSolutionInput
     */
    ResourceConfig?: ResourceConfigForUpdateSolutionInput;

    /**
     * @type {RuntimeConfigForUpdateSolutionInput}
     * @memberof TaskConfigForUpdateSolutionInput
     */
    RuntimeConfig?: RuntimeConfigForUpdateSolutionInput;

    /**
     * @type {ScheduleConfigForUpdateSolutionInput}
     * @memberof TaskConfigForUpdateSolutionInput
     */
    ScheduleConfig?: ScheduleConfigForUpdateSolutionInput;
}

/**
 * @export
 * @enum {string}
 */
export enum TaskConfigForUpdateSolutionInputExecutionModeEnum {
    STREAMING = 'STREAMING',
    BATCH = 'BATCH',
    MERGE = 'MERGE',
    SENSOR = 'SENSOR'
}

