/* tslint:disable */
/* eslint-disable */
/**
 * dataleap20260301
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchIncrTaskNameMappingForUpdateSolutionInput } from './batch-incr-task-name-mapping-for-update-solution-input';
import { BatchSnapTaskNameMappingForUpdateSolutionInput } from './batch-snap-task-name-mapping-for-update-solution-input';
 /**
 * 
 *
 * @export
 * @interface TaskNameMappingRuleForUpdateSolutionInput
 */
export interface TaskNameMappingRuleForUpdateSolutionInput {

    /**
     * @type {Array<BatchIncrTaskNameMappingForUpdateSolutionInput>}
     * @memberof TaskNameMappingRuleForUpdateSolutionInput
     */
    BatchIncrTaskNameMappings?: Array<BatchIncrTaskNameMappingForUpdateSolutionInput>;

    /**
     * @type {Array<BatchSnapTaskNameMappingForUpdateSolutionInput>}
     * @memberof TaskNameMappingRuleForUpdateSolutionInput
     */
    BatchSnapTaskNameMappings?: Array<BatchSnapTaskNameMappingForUpdateSolutionInput>;

    /**
     * @type {string}
     * @memberof TaskNameMappingRuleForUpdateSolutionInput
     */
    Type?: TaskNameMappingRuleForUpdateSolutionInputTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TaskNameMappingRuleForUpdateSolutionInputTypeEnum {
    GLOBAL = 'GLOBAL',
    CUSTOM = 'CUSTOM'
}

