/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MaintenanceWindowForDescribeDBInstanceDetailOutput } from './maintenance-window-for-describe-dbinstance-detail-output';
import { TagForDescribeDBInstanceDetailOutput } from './tag-for-describe-dbinstance-detail-output';
 /**
 * 
 *
 * @export
 * @interface BasicInfoForDescribeDBInstanceDetailOutput
 */
export interface BasicInfoForDescribeDBInstanceDetailOutput {

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    AllowListVersion?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    AutoUpgradeMinorVersion?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    CurrentKernelVersion?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DBEngineVersion?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DataSyncMode?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DeletionProtection?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DrDtsTaskId?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DrDtsTaskName?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DrDtsTaskStatus?: string;

    /**
     * @type {number}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    DrSecondsBehindMaster?: number;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    EngineType?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    InstanceName?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    InstanceStatus?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    InstanceType?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    LowerCaseTableNames?: string;

    /**
     * @type {MaintenanceWindowForDescribeDBInstanceDetailOutput}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    MaintenanceWindow?: MaintenanceWindowForDescribeDBInstanceDetailOutput;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    MasterInstanceId?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    MasterInstanceName?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    MasterRegion?: string;

    /**
     * @type {number}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    Memory?: number;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    NewNodeSpec?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    NodeNumber?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    NodeSpec?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    RegionId?: string;

    /**
     * @type {number}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    StorageSpace?: number;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    StorageType?: string;

    /**
     * @type {number}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    StorageUse?: number;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    SubnetId?: string;

    /**
     * @type {Array<TagForDescribeDBInstanceDetailOutput>}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    Tags?: Array<TagForDescribeDBInstanceDetailOutput>;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    TimeZone?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    UpdateTime?: string;

    /**
     * @type {number}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    VCPU?: number;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    VpcId?: string;

    /**
     * @type {string}
     * @memberof BasicInfoForDescribeDBInstanceDetailOutput
     */
    ZoneId?: string;
}
