/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChargeInfoForCreateDBBlueGreenInstanceInput
 */
export interface ChargeInfoForCreateDBBlueGreenInstanceInput {

    /**
     * @type {boolean}
     * @memberof ChargeInfoForCreateDBBlueGreenInstanceInput
     */
    AutoRenew?: boolean;

    /**
     * @type {string}
     * @memberof ChargeInfoForCreateDBBlueGreenInstanceInput
     */
    ChargeType?: string;

    /**
     * @type {number}
     * @memberof ChargeInfoForCreateDBBlueGreenInstanceInput
     */
    Number?: number;

    /**
     * @type {number}
     * @memberof ChargeInfoForCreateDBBlueGreenInstanceInput
     */
    Period?: number;

    /**
     * @type {string}
     * @memberof ChargeInfoForCreateDBBlueGreenInstanceInput
     */
    PeriodUnit?: string;
}
