/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DatabasePrivilegeForCreateDatabaseInput } from './database-privilege-for-create-database-input';
 /**
 * 
 *
 * @export
 * @interface CreateDatabaseRequest
 */
export interface CreateDatabaseRequest {

    /**
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    CharacterSetName?: string;

    /**
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    DBDesc?: string;

    /**
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    DBName: string;

    /**
     * @type {Array<DatabasePrivilegeForCreateDatabaseInput>}
     * @memberof CreateDatabaseRequest
     */
    DatabasePrivileges?: Array<DatabasePrivilegeForCreateDatabaseInput>;

    /**
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    InstanceId: string;
}
