/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlueInfoDifferenceForDescribeDBBlueGreenDifferencesOutput } from './blue-info-difference-for-describe-dbblue-green-differences-output';
import { GreenInfoDifferenceForDescribeDBBlueGreenDifferencesOutput } from './green-info-difference-for-describe-dbblue-green-differences-output';
 /**
 * 
 *
 * @export
 * @interface DescribeDBBlueGreenDifferencesResponse
 */
export interface DescribeDBBlueGreenDifferencesResponse {

    /**
     * @type {BlueInfoDifferenceForDescribeDBBlueGreenDifferencesOutput}
     * @memberof DescribeDBBlueGreenDifferencesResponse
     */
    BlueInfoDifference?: BlueInfoDifferenceForDescribeDBBlueGreenDifferencesOutput;

    /**
     * @type {GreenInfoDifferenceForDescribeDBBlueGreenDifferencesOutput}
     * @memberof DescribeDBBlueGreenDifferencesResponse
     */
    GreenInfoDifference?: GreenInfoDifferenceForDescribeDBBlueGreenDifferencesOutput;
}
