/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InstanceSpecsInfoForDescribeDBInstanceSpecsOutput } from './instance-specs-info-for-describe-dbinstance-specs-output';
 /**
 * 
 *
 * @export
 * @interface DescribeDBInstanceSpecsResponse
 */
export interface DescribeDBInstanceSpecsResponse {

    /**
     * @type {Array<InstanceSpecsInfoForDescribeDBInstanceSpecsOutput>}
     * @memberof DescribeDBInstanceSpecsResponse
     */
    InstanceSpecsInfo?: Array<InstanceSpecsInfoForDescribeDBInstanceSpecsOutput>;
}
