/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
 */
export interface DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput {

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    DtsTaskId?: string;

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    DtsTaskName?: string;

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    DtsTaskStatus?: string;

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    InstanceName?: string;

    /**
     * @type {string}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    Region?: string;

    /**
     * @type {number}
     * @memberof DisasterRecoveryInstanceForDescribeDBInstanceDetailOutput
     */
    SecondsBehindMaster?: number;
}
