/* tslint:disable */
/* eslint-disable */
/**
 * vikingdb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PipelineConfigForMemoryCollectionListOutput } from './pipeline-config-for-memory-collection-list-output';
import { TagForMemoryCollectionListOutput } from './tag-for-memory-collection-list-output';
 /**
 * 
 *
 * @export
 * @interface CollectionListForMemoryCollectionListOutput
 */
export interface CollectionListForMemoryCollectionListOutput {

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    CollectionType?: string;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    CreatedAt?: string;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    CreatedBy?: string;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    DescMsg?: string;

    /**
     * @type {number}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    EventCount?: number;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    Name?: string;

    /**
     * @type {PipelineConfigForMemoryCollectionListOutput}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    PipelineConfig?: PipelineConfigForMemoryCollectionListOutput;

    /**
     * @type {number}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    ProfileCount?: number;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    Project?: string;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    ResourceId?: string;

    /**
     * @type {Array<TagForMemoryCollectionListOutput>}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    Tags?: Array<TagForMemoryCollectionListOutput>;

    /**
     * @type {string}
     * @memberof CollectionListForMemoryCollectionListOutput
     */
    UpdatedAt?: string;
}
