/* tslint:disable */
/* eslint-disable */
/**
 * vikingdb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InstructionForGetVikingdbCollectionOutput } from './instruction-for-get-vikingdb-collection-output';
 /**
 * 
 *
 * @export
 * @interface TensorForGetVikingdbCollectionOutput
 */
export interface TensorForGetVikingdbCollectionOutput {

    /**
     * @type {number}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    Dim?: number;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    ImageField?: string;

    /**
     * @type {InstructionForGetVikingdbCollectionOutput}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    Instruction?: InstructionForGetVikingdbCollectionOutput;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    ModelName?: TensorForGetVikingdbCollectionOutputModelNameEnum;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    ModelVersion?: string;

    /**
     * @type {number}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    NDim?: number;

    /**
     * @type {Array<number>}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    Shape?: Array<number>;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    TensorQuantType?: TensorForGetVikingdbCollectionOutputTensorQuantTypeEnum;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    TextField?: string;

    /**
     * @type {string}
     * @memberof TensorForGetVikingdbCollectionOutput
     */
    VideoField?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum TensorForGetVikingdbCollectionOutputModelNameEnum {
    BgeLargeZh = 'bge-large-zh',
    BgeM3 = 'bge-m3',
    BgeVisualizedM3 = 'bge-visualized-m3',
    DoubaoEmbedding = 'doubao-embedding',
    DoubaoEmbeddingLarge = 'doubao-embedding-large',
    DoubaoEmbeddingVision = 'doubao-embedding-vision',
    SkylarkEmbeddingVision = 'skylark-embedding-vision'
}
/**
 * @export
 * @enum {string}
 */
export enum TensorForGetVikingdbCollectionOutputTensorQuantTypeEnum {
    Int8 = 'int8'
}

