/* tslint:disable */
/* eslint-disable */
/**
 * vikingdb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DenseForCreateVikingdbCollectionInput } from './dense-for-create-vikingdb-collection-input';
import { SparseForCreateVikingdbCollectionInput } from './sparse-for-create-vikingdb-collection-input';
import { TensorForCreateVikingdbCollectionInput } from './tensor-for-create-vikingdb-collection-input';
 /**
 * 
 *
 * @export
 * @interface VectorizeForCreateVikingdbCollectionInput
 */
export interface VectorizeForCreateVikingdbCollectionInput {

    /**
     * @type {DenseForCreateVikingdbCollectionInput}
     * @memberof VectorizeForCreateVikingdbCollectionInput
     */
    Dense?: DenseForCreateVikingdbCollectionInput;

    /**
     * @type {SparseForCreateVikingdbCollectionInput}
     * @memberof VectorizeForCreateVikingdbCollectionInput
     */
    Sparse?: SparseForCreateVikingdbCollectionInput;

    /**
     * @type {TensorForCreateVikingdbCollectionInput}
     * @memberof VectorizeForCreateVikingdbCollectionInput
     */
    Tensor?: TensorForCreateVikingdbCollectionInput;
}
