/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComplianceForDescribeAccountGroupComplianceByConformancePacksOutput } from './compliance-for-describe-account-group-compliance-by-conformance-packs-output';
 /**
 * 
 *
 * @export
 * @interface ComplianceByConformancePackForDescribeAccountGroupComplianceByConformancePacksOutput
 */
export interface ComplianceByConformancePackForDescribeAccountGroupComplianceByConformancePacksOutput {

    /**
     * @type {ComplianceForDescribeAccountGroupComplianceByConformancePacksOutput}
     * @memberof ComplianceByConformancePackForDescribeAccountGroupComplianceByConformancePacksOutput
     */
    Compliance?: ComplianceForDescribeAccountGroupComplianceByConformancePacksOutput;

    /**
     * @type {string}
     * @memberof ComplianceByConformancePackForDescribeAccountGroupComplianceByConformancePacksOutput
     */
    ConformancePackId?: string;
}
