/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeliveryChannelForListDeliveryChannelsOutput
 */
export interface DeliveryChannelForListDeliveryChannelsOutput {

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    AccountId?: string;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryChannelId?: string;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryChannelName?: string;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryChannelTargetTrn?: string;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryChannelType?: DeliveryChannelForListDeliveryChannelsOutputDeliveryChannelTypeEnum;

    /**
     * @type {Array<string>}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryContents?: Array<DeliveryChannelForListDeliveryChannelsOutputDeliveryContentsEnum>;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    DeliveryRoleTrn?: string;

    /**
     * @type {string}
     * @memberof DeliveryChannelForListDeliveryChannelsOutput
     */
    Status?: DeliveryChannelForListDeliveryChannelsOutputStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum DeliveryChannelForListDeliveryChannelsOutputDeliveryChannelTypeEnum {
    SNS = 'SNS',
    TOS = 'TOS',
    TLS = 'TLS'
}
/**
 * @export
 * @enum {string}
 */
export enum DeliveryChannelForListDeliveryChannelsOutputDeliveryContentsEnum {
    ConfigurationItemChangeNotification = 'ConfigurationItemChangeNotification',
    NonCompliantNotification = 'NonCompliantNotification',
    CompliantSnapshot = 'CompliantSnapshot',
    ConfigurationSnapshot = 'ConfigurationSnapshot'
}
/**
 * @export
 * @enum {string}
 */
export enum DeliveryChannelForListDeliveryChannelsOutputStatusEnum {
    Enabled = 'Enabled',
    Disabled = 'Disabled'
}

