/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComplianceByResourceForDescribeComplianceByResourcesOutput } from './compliance-by-resource-for-describe-compliance-by-resources-output';
 /**
 * 
 *
 * @export
 * @interface DescribeComplianceByResourcesResponse
 */
export interface DescribeComplianceByResourcesResponse {

    /**
     * @type {Array<ComplianceByResourceForDescribeComplianceByResourcesOutput>}
     * @memberof DescribeComplianceByResourcesResponse
     */
    ComplianceByResources?: Array<ComplianceByResourceForDescribeComplianceByResourcesOutput>;
}
