/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComplianceListForGetAccountGroupComplianceHistoryOutput } from './compliance-list-for-get-account-group-compliance-history-output';
 /**
 * 
 *
 * @export
 * @interface GetAccountGroupComplianceHistoryResponse
 */
export interface GetAccountGroupComplianceHistoryResponse {

    /**
     * @type {Array<ComplianceListForGetAccountGroupComplianceHistoryOutput>}
     * @memberof GetAccountGroupComplianceHistoryResponse
     */
    ComplianceList?: Array<ComplianceListForGetAccountGroupComplianceHistoryOutput>;

    /**
     * @type {number}
     * @memberof GetAccountGroupComplianceHistoryResponse
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof GetAccountGroupComplianceHistoryResponse
     */
    NextToken?: string;
}
