/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ParameterForCreateAccountGroupRuleTemplateInput
 */
export interface ParameterForCreateAccountGroupRuleTemplateInput {

    /**
     * @type {string}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    AllowedValues?: string;

    /**
     * @type {string}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    DefaultValue?: string;

    /**
     * @type {string}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    Description?: string;

    /**
     * @type {boolean}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    IsCompulsory?: boolean;

    /**
     * @type {string}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof ParameterForCreateAccountGroupRuleTemplateInput
     */
    ValueType?: ParameterForCreateAccountGroupRuleTemplateInputValueTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ParameterForCreateAccountGroupRuleTemplateInputValueTypeEnum {
    String = 'string',
    Number = 'number',
    Boolean = 'boolean',
    ArrayString = 'array[string]',
    ArrayNumber = 'array[number]',
    ArrayBoolean = 'array[boolean]'
}

