/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProjectsForDescribeAccountGroupConformancePacksOutput
 */
export interface ProjectsForDescribeAccountGroupConformancePacksOutput {

    /**
     * @type {Array<string>}
     * @memberof ProjectsForDescribeAccountGroupConformancePacksOutput
     */
    Exclude?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ProjectsForDescribeAccountGroupConformancePacksOutput
     */
    Include?: Array<string>;
}
