/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResourceTypeListForDescribeSupportedResourceTypesOutput
 */
export interface ResourceTypeListForDescribeSupportedResourceTypesOutput {

    /**
     * @type {string}
     * @memberof ResourceTypeListForDescribeSupportedResourceTypesOutput
     */
    ConfigurationItemSample?: string;

    /**
     * @type {string}
     * @memberof ResourceTypeListForDescribeSupportedResourceTypesOutput
     */
    ResourceType?: string;

    /**
     * @type {string}
     * @memberof ResourceTypeListForDescribeSupportedResourceTypesOutput
     */
    ResourceTypeName?: string;

    /**
     * @type {string}
     * @memberof ResourceTypeListForDescribeSupportedResourceTypesOutput
     */
    ServiceCode?: string;

    /**
     * @type {string}
     * @memberof ResourceTypeListForDescribeSupportedResourceTypesOutput
     */
    ServiceName?: string;
}
