/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RuleForListRulesOutput
 */
export interface RuleForListRulesOutput {

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    CreatedTime?: string;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    RiskLevel?: RuleForListRulesOutputRiskLevelEnum;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    RuleId?: string;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    RuleName?: string;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    RuleStatus?: RuleForListRulesOutputRuleStatusEnum;

    /**
     * @type {string}
     * @memberof RuleForListRulesOutput
     */
    RuleTemplateId?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum RuleForListRulesOutputRiskLevelEnum {
    Low = 'Low',
    Medium = 'Medium',
    High = 'High'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForListRulesOutputRuleStatusEnum {
    Enabled = 'Enabled',
    Disabled = 'Disabled'
}

