/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateConformancePackTemplateRequest
 */
export interface UpdateConformancePackTemplateRequest {

    /**
     * @type {string}
     * @memberof UpdateConformancePackTemplateRequest
     */
    ConformancePackTemplateId: string;

    /**
     * @type {string}
     * @memberof UpdateConformancePackTemplateRequest
     */
    Description?: string;

    /**
     * @type {Array<string>}
     * @memberof UpdateConformancePackTemplateRequest
     */
    Labels?: Array<UpdateConformancePackTemplateRequestLabelsEnum>;

    /**
     * @type {string}
     * @memberof UpdateConformancePackTemplateRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof UpdateConformancePackTemplateRequest
     */
    RiskLevel?: UpdateConformancePackTemplateRequestRiskLevelEnum;

    /**
     * @type {Array<string>}
     * @memberof UpdateConformancePackTemplateRequest
     */
    RuleTemplates?: Array<string>;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateConformancePackTemplateRequestLabelsEnum {
    Law = 'Law',
    BestPractice = 'BestPractice'
}
/**
 * @export
 * @enum {string}
 */
export enum UpdateConformancePackTemplateRequestRiskLevelEnum {
    Low = 'Low',
    Medium = 'Medium',
    High = 'High'
}

