/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ScopeForUpdateRuleInput } from './scope-for-update-rule-input';
import { TriggerForUpdateRuleInput } from './trigger-for-update-rule-input';
 /**
 * 
 *
 * @export
 * @interface UpdateRuleRequest
 */
export interface UpdateRuleRequest {

    /**
     * @type {string}
     * @memberof UpdateRuleRequest
     */
    Description: string;

    /**
     * @type {string}
     * @memberof UpdateRuleRequest
     */
    InputParameters: string;

    /**
     * @type {string}
     * @memberof UpdateRuleRequest
     */
    RiskLevel: UpdateRuleRequestRiskLevelEnum;

    /**
     * @type {string}
     * @memberof UpdateRuleRequest
     */
    RuleId: string;

    /**
     * @type {string}
     * @memberof UpdateRuleRequest
     */
    RuleName: string;

    /**
     * @type {ScopeForUpdateRuleInput}
     * @memberof UpdateRuleRequest
     */
    Scope?: ScopeForUpdateRuleInput;

    /**
     * @type {Array<TriggerForUpdateRuleInput>}
     * @memberof UpdateRuleRequest
     */
    Triggers?: Array<TriggerForUpdateRuleInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateRuleRequestRiskLevelEnum {
    Low = 'Low',
    Medium = 'Medium',
    High = 'High'
}

