/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetaDataForAddWorkloadMetaDataOutput } from './meta-data-for-add-workload-meta-data-output';
 /**
 * 
 *
 * @export
 * @interface AddWorkloadMetaDataResponse
 */
export interface AddWorkloadMetaDataResponse {

    /**
     * @type {Array<MetaDataForAddWorkloadMetaDataOutput>}
     * @memberof AddWorkloadMetaDataResponse
     */
    MetaData?: Array<MetaDataForAddWorkloadMetaDataOutput>;

    /**
     * @type {string}
     * @memberof AddWorkloadMetaDataResponse
     */
    WorkloadIdentity?: string;

    /**
     * @type {string}
     * @memberof AddWorkloadMetaDataResponse
     */
    WorkloadPoolName?: string;
}
