/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AttributeMappingForCreateIdentityProviderOAuthInput
 */
export interface AttributeMappingForCreateIdentityProviderOAuthInput {

    /**
     * @type {string}
     * @memberof AttributeMappingForCreateIdentityProviderOAuthInput
     */
    AdditionalConfig?: string;

    /**
     * @type {string}
     * @memberof AttributeMappingForCreateIdentityProviderOAuthInput
     */
    MappingType?: string;

    /**
     * @type {string}
     * @memberof AttributeMappingForCreateIdentityProviderOAuthInput
     */
    SourceAttributeName?: string;

    /**
     * @type {string}
     * @memberof AttributeMappingForCreateIdentityProviderOAuthInput
     */
    TargetAttributeName?: string;
}
