/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BatchConvertFederatedUsersToNativeUsersRequest
 */
export interface BatchConvertFederatedUsersToNativeUsersRequest {

    /**
     * @type {string}
     * @memberof BatchConvertFederatedUsersToNativeUsersRequest
     */
    UserPoolUid: string;

    /**
     * @type {Array<string>}
     * @memberof BatchConvertFederatedUsersToNativeUsersRequest
     */
    UserUids?: Array<string>;
}
