/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ClaimRuleForCreateIdentityProviderWeComOutput
 */
export interface ClaimRuleForCreateIdentityProviderWeComOutput {

    /**
     * @type {string}
     * @memberof ClaimRuleForCreateIdentityProviderWeComOutput
     */
    ClaimType?: string;

    /**
     * @type {boolean}
     * @memberof ClaimRuleForCreateIdentityProviderWeComOutput
     */
    Required?: boolean;

    /**
     * @type {string}
     * @memberof ClaimRuleForCreateIdentityProviderWeComOutput
     */
    SourceClaimPath?: string;

    /**
     * @type {string}
     * @memberof ClaimRuleForCreateIdentityProviderWeComOutput
     */
    TargetClaim?: string;
}
