/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IdentityPoolForCreateRoleCredentialProviderInput } from './identity-pool-for-create-role-credential-provider-input';
import { RoleMappingForCreateRoleCredentialProviderInput } from './role-mapping-for-create-role-credential-provider-input';
 /**
 * 
 *
 * @export
 * @interface ConfigForCreateRoleCredentialProviderInput
 */
export interface ConfigForCreateRoleCredentialProviderInput {

    /**
     * @type {IdentityPoolForCreateRoleCredentialProviderInput}
     * @memberof ConfigForCreateRoleCredentialProviderInput
     */
    IdentityPool?: IdentityPoolForCreateRoleCredentialProviderInput;

    /**
     * @type {string}
     * @memberof ConfigForCreateRoleCredentialProviderInput
     */
    Metadata?: string;

    /**
     * @type {RoleMappingForCreateRoleCredentialProviderInput}
     * @memberof ConfigForCreateRoleCredentialProviderInput
     */
    RoleMapping?: RoleMappingForCreateRoleCredentialProviderInput;
}
