/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionForListUsersInDepartmentInput } from './condition-for-list-users-in-department-input';
import { GroupForListUsersInDepartmentInput } from './group-for-list-users-in-department-input';
 /**
 * 
 *
 * @export
 * @interface ConvertGroupForListUsersInDepartmentInput
 */
export interface ConvertGroupForListUsersInDepartmentInput {

    /**
     * @type {Array<ConditionForListUsersInDepartmentInput>}
     * @memberof ConvertGroupForListUsersInDepartmentInput
     */
    Conditions?: Array<ConditionForListUsersInDepartmentInput>;

    /**
     * @type {Array<GroupForListUsersInDepartmentInput>}
     * @memberof ConvertGroupForListUsersInDepartmentInput
     */
    Groups?: Array<GroupForListUsersInDepartmentInput>;

    /**
     * @type {string}
     * @memberof ConvertGroupForListUsersInDepartmentInput
     */
    Relation?: string;
}
