/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionForListUsersInGroupInput } from './condition-for-list-users-in-group-input';
import { GroupForListUsersInGroupInput } from './group-for-list-users-in-group-input';
 /**
 * 
 *
 * @export
 * @interface ConvertGroupForListUsersInGroupInput
 */
export interface ConvertGroupForListUsersInGroupInput {

    /**
     * @type {Array<ConditionForListUsersInGroupInput>}
     * @memberof ConvertGroupForListUsersInGroupInput
     */
    Conditions?: Array<ConditionForListUsersInGroupInput>;

    /**
     * @type {Array<GroupForListUsersInGroupInput>}
     * @memberof ConvertGroupForListUsersInGroupInput
     */
    Groups?: Array<GroupForListUsersInGroupInput>;

    /**
     * @type {string}
     * @memberof ConvertGroupForListUsersInGroupInput
     */
    Relation?: string;
}
