/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertPathForGetDepartmentPathOutput
 */
export interface ConvertPathForGetDepartmentPathOutput {

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Description?: string;

    /**
     * @type {number}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    DirectChildrenCount?: number;

    /**
     * @type {number}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    DirectMemberCount?: number;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    ExternalID?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    IamRoleTrn?: string;

    /**
     * @type {number}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    MemberCount?: number;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    NamePath?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    ParentDepartmentUid?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Path?: string;

    /**
     * @type {number}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Precedence?: number;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Source?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    Uid?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof ConvertPathForGetDepartmentPathOutput
     */
    UserPoolUid?: string;
}
