/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ErrorsStructuredForCreateUserGroupsCsvOutput } from './errors-structured-for-create-user-groups-csv-output';
import { SuccessfulUidsStructuredForCreateUserGroupsCsvOutput } from './successful-uids-structured-for-create-user-groups-csv-output';
 /**
 * 
 *
 * @export
 * @interface CreateUserGroupsCsvResponse
 */
export interface CreateUserGroupsCsvResponse {

    /**
     * @type {Array<string>}
     * @memberof CreateUserGroupsCsvResponse
     */
    Errors?: Array<string>;

    /**
     * @type {Array<ErrorsStructuredForCreateUserGroupsCsvOutput>}
     * @memberof CreateUserGroupsCsvResponse
     */
    ErrorsStructured?: Array<ErrorsStructuredForCreateUserGroupsCsvOutput>;

    /**
     * @type {number}
     * @memberof CreateUserGroupsCsvResponse
     */
    FailureCount?: number;

    /**
     * @type {number}
     * @memberof CreateUserGroupsCsvResponse
     */
    SuccessCount?: number;

    /**
     * @type {Array<string>}
     * @memberof CreateUserGroupsCsvResponse
     */
    SuccessfulUids?: Array<string>;

    /**
     * @type {Array<SuccessfulUidsStructuredForCreateUserGroupsCsvOutput>}
     * @memberof CreateUserGroupsCsvResponse
     */
    SuccessfulUidsStructured?: Array<SuccessfulUidsStructuredForCreateUserGroupsCsvOutput>;
}
