/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConfigForCreateRoleCredentialProviderInput } from './config-for-create-role-credential-provider-input';
 /**
 * 
 *
 * @export
 * @interface CreateRoleCredentialProviderRequest
 */
export interface CreateRoleCredentialProviderRequest {

    /**
     * @type {ConfigForCreateRoleCredentialProviderInput}
     * @memberof CreateRoleCredentialProviderRequest
     */
    Config?: ConfigForCreateRoleCredentialProviderInput;

    /**
     * @type {string}
     * @memberof CreateRoleCredentialProviderRequest
     */
    Name: string;

    /**
     * @type {string}
     * @memberof CreateRoleCredentialProviderRequest
     */
    PoolName?: string;

    /**
     * @type {string}
     * @memberof CreateRoleCredentialProviderRequest
     */
    ProjectName?: string;

    /**
     * @type {number}
     * @memberof CreateRoleCredentialProviderRequest
     */
    Vendor: number;
}
