/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserPoolDomainRequest
 */
export interface CreateUserPoolDomainRequest {

    /**
     * @type {string}
     * @memberof CreateUserPoolDomainRequest
     */
    CertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateUserPoolDomainRequest
     */
    Domain: string;

    /**
     * @type {string}
     * @memberof CreateUserPoolDomainRequest
     */
    UserPoolUid: string;
}
