/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeInput } from './allowed-claims-and-value-for-create-identity-provider-token-exchange-input';
import { AttributeMappingForCreateIdentityProviderTokenExchangeInput } from './attribute-mapping-for-create-identity-provider-token-exchange-input';
import { ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeInput } from './claims-propagation-config-for-create-identity-provider-token-exchange-input';
import { ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeInput } from './external-identity-provider-configuration-for-create-identity-provider-token-exchange-input';
import { ProviderOptionsForCreateIdentityProviderTokenExchangeInput } from './provider-options-for-create-identity-provider-token-exchange-input';
 /**
 * 
 *
 * @export
 * @interface CreateIdentityProviderTokenExchangeRequest
 */
export interface CreateIdentityProviderTokenExchangeRequest {

    /**
     * @type {Array<string>}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    AllowedAudiences?: Array<string>;

    /**
     * @type {Array<AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeInput>}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    AllowedClaimsAndValues?: Array<AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeInput>;

    /**
     * @type {Array<string>}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    AllowedClients?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    AllowedScopes?: Array<string>;

    /**
     * @type {Array<AttributeMappingForCreateIdentityProviderTokenExchangeInput>}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    AttributeMappings?: Array<AttributeMappingForCreateIdentityProviderTokenExchangeInput>;

    /**
     * @type {ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeInput}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    ClaimsPropagationConfig?: ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeInput;

    /**
     * @type {string}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    EipId?: string;

    /**
     * @type {boolean}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    Enabled: boolean;

    /**
     * @type {ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeInput}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    ExternalIdentityProviderConfiguration?: ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeInput;

    /**
     * @type {string}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    Name: string;

    /**
     * @type {string}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    Provider?: string;

    /**
     * @type {ProviderOptionsForCreateIdentityProviderTokenExchangeInput}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    ProviderOptions?: ProviderOptionsForCreateIdentityProviderTokenExchangeInput;

    /**
     * @type {string}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    ProviderType: string;

    /**
     * @type {string}
     * @memberof CreateIdentityProviderTokenExchangeRequest
     */
    UserPoolUid: string;
}
