/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomAttributeForCreateUserOutput } from './custom-attribute-for-create-user-output';
import { ExternalIdentityForCreateUserOutput } from './external-identity-for-create-user-output';
 /**
 * 
 *
 * @export
 * @interface CreateUserResponse
 */
export interface CreateUserResponse {

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Birthdate?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Connection?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    CreateTime?: string;

    /**
     * @type {Array<CustomAttributeForCreateUserOutput>}
     * @memberof CreateUserResponse
     */
    CustomAttributes?: Array<CustomAttributeForCreateUserOutput>;

    /**
     * @type {Array<string>}
     * @memberof CreateUserResponse
     */
    DepartmentUids?: Array<string>;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Email?: string;

    /**
     * @type {boolean}
     * @memberof CreateUserResponse
     */
    EmailVerified?: boolean;

    /**
     * @type {Array<ExternalIdentityForCreateUserOutput>}
     * @memberof CreateUserResponse
     */
    ExternalIdentities?: Array<ExternalIdentityForCreateUserOutput>;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    FamilyName?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Gender?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    GivenName?: string;

    /**
     * @type {Array<string>}
     * @memberof CreateUserResponse
     */
    GroupUids?: Array<string>;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestBrowser?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestLogin?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestLoginConnectionName?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestLoginConnectionProvider?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestLoginConnectionType?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    LatestLoginMethod?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Locale?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    MiddleName?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Nickname?: string;

    /**
     * @type {number}
     * @memberof CreateUserResponse
     */
    NumLogins?: number;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    PhoneNumber?: string;

    /**
     * @type {boolean}
     * @memberof CreateUserResponse
     */
    PhoneNumberVerified?: boolean;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Picture?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    PreferredUsername?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Profile?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Sub?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Uid?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    UserMetadata?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    UserState?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Website?: string;

    /**
     * @type {string}
     * @memberof CreateUserResponse
     */
    Zoneinfo?: string;
}
