/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForGetOutboundEgressIPOutput
 */
export interface DataForGetOutboundEgressIPOutput {

    /**
     * @type {number}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    CreateTime?: number;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    EipAddress?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    EipID?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    ID?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    NatGatewayID?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    NatGatewayName?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    NatGatewayVpcID?: string;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    NatGatewayVpcName?: string;

    /**
     * @type {number}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    OAuthClientResourceNum?: number;

    /**
     * @type {string}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    Status?: string;

    /**
     * @type {number}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    UpdateTime?: number;

    /**
     * @type {number}
     * @memberof DataForGetOutboundEgressIPOutput
     */
    UserPoolIdpResourceNum?: number;
}
