/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GroupForListGroupsForUsersOutput } from './group-for-list-groups-for-users-output';
 /**
 * 
 *
 * @export
 * @interface DataForListGroupsForUsersOutput
 */
export interface DataForListGroupsForUsersOutput {

    /**
     * @type {Array<GroupForListGroupsForUsersOutput>}
     * @memberof DataForListGroupsForUsersOutput
     */
    Groups?: Array<GroupForListGroupsForUsersOutput>;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUsersOutput
     */
    UserUid?: string;
}
