/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForListGroupsForUserOutput
 */
export interface DataForListGroupsForUserOutput {

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    GroupIdTokenName?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    IamRoleTrn?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    Name?: string;

    /**
     * @type {number}
     * @memberof DataForListGroupsForUserOutput
     */
    Precedence?: number;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    Source?: string;

    /**
     * @type {number}
     * @memberof DataForListGroupsForUserOutput
     */
    TotalCountOfGroupMember?: number;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    Uid?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof DataForListGroupsForUserOutput
     */
    UserPoolUid?: string;
}
