/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ExternalIdentityProviderConfigurationForUpdateIdentityProviderTokenExchangeOutput
 */
export interface ExternalIdentityProviderConfigurationForUpdateIdentityProviderTokenExchangeOutput {

    /**
     * @type {string}
     * @memberof ExternalIdentityProviderConfigurationForUpdateIdentityProviderTokenExchangeOutput
     */
    OAuthUserIdAttribute?: string;

    /**
     * @type {string}
     * @memberof ExternalIdentityProviderConfigurationForUpdateIdentityProviderTokenExchangeOutput
     */
    OAuthUserInfoUrl?: string;

    /**
     * @type {string}
     * @memberof ExternalIdentityProviderConfigurationForUpdateIdentityProviderTokenExchangeOutput
     */
    OIDCIssuerUrl?: string;
}
