/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomAttributeFilterForListUsersInput } from './custom-attribute-filter-for-list-users-input';
import { UniversalSearchForListUsersInput } from './universal-search-for-list-users-input';
 /**
 * 
 *
 * @export
 * @interface FilterForListUsersInput
 */
export interface FilterForListUsersInput {

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Connection?: string;

    /**
     * @type {CustomAttributeFilterForListUsersInput}
     * @memberof FilterForListUsersInput
     */
    CustomAttributeFilter?: CustomAttributeFilterForListUsersInput;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    DepartmentUid?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    DepartmentUidRecursive?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Email?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    EmailIsDuplicated?: boolean;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    EmailIsNullOrEmpty?: boolean;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    EmailPhoneNameIsNullOrEmpty?: boolean;

    /**
     * @type {Array<string>}
     * @memberof FilterForListUsersInput
     */
    ExternalProviderUserIdentifiersOr?: Array<string>;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    FamilyName?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    FamilyNameIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Gender?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    GenderIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    GivenName?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    GivenNameIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    GroupUid?: string;

    /**
     * @type {Array<string>}
     * @memberof FilterForListUsersInput
     */
    GroupUidsOr?: Array<string>;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    LatestBrowser?: string;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    LatestLoginMethod?: string;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Locale?: string;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    MiddleName?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    MiddleNameIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Name?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    NameIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Nickname?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    NicknameIsNullOrEmpty?: boolean;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    NotInAnyDepartment?: boolean;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    NotInAnyGroup?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    PhoneNumber?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    PhoneNumberIsDuplicated?: boolean;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    PhoneNumberIsNullOrEmpty?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    PreferredUsername?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    PreferredUsernameIsNullOrEmpty?: boolean;

    /**
     * @type {Array<UniversalSearchForListUsersInput>}
     * @memberof FilterForListUsersInput
     */
    UniversalSearch?: Array<UniversalSearchForListUsersInput>;

    /**
     * @type {Array<string>}
     * @memberof FilterForListUsersInput
     */
    UserUidsOr?: Array<string>;

    /**
     * @type {string}
     * @memberof FilterForListUsersInput
     */
    Website?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListUsersInput
     */
    WebsiteIsNullOrEmpty?: boolean;
}
