/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowedRoleForListRoleCredentialProvidersOutput } from './allowed-role-for-list-role-credential-providers-output';
 /**
 * 
 *
 * @export
 * @interface FromRequestForListRoleCredentialProvidersOutput
 */
export interface FromRequestForListRoleCredentialProvidersOutput {

    /**
     * @type {Array<AllowedRoleForListRoleCredentialProvidersOutput>}
     * @memberof FromRequestForListRoleCredentialProvidersOutput
     */
    AllowedRoles?: Array<AllowedRoleForListRoleCredentialProvidersOutput>;
}
