/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleMappingForGetIamRoleAttachmentOutput } from './role-mapping-for-get-iam-role-attachment-output';
 /**
 * 
 *
 * @export
 * @interface GetIamRoleAttachmentResponse
 */
export interface GetIamRoleAttachmentResponse {

    /**
     * @type {string}
     * @memberof GetIamRoleAttachmentResponse
     */
    DefaultAuthenticatedRoleTrn?: string;

    /**
     * @type {string}
     * @memberof GetIamRoleAttachmentResponse
     */
    DefaultUnauthenticatedRoleTrn?: string;

    /**
     * @type {Array<RoleMappingForGetIamRoleAttachmentOutput>}
     * @memberof GetIamRoleAttachmentResponse
     */
    RoleMappings?: Array<RoleMappingForGetIamRoleAttachmentOutput>;

    /**
     * @type {string}
     * @memberof GetIamRoleAttachmentResponse
     */
    Uid?: string;

    /**
     * @type {string}
     * @memberof GetIamRoleAttachmentResponse
     */
    UserPoolUid?: string;
}
