/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListUsersInGroupInput } from './filter-for-list-users-in-group-input';
 /**
 * 
 *
 * @export
 * @interface ListUsersInGroupRequest
 */
export interface ListUsersInGroupRequest {

    /**
     * @type {FilterForListUsersInGroupInput}
     * @memberof ListUsersInGroupRequest
     */
    Filter?: FilterForListUsersInGroupInput;

    /**
     * @type {string}
     * @memberof ListUsersInGroupRequest
     */
    GroupUid: string;

    /**
     * @type {number}
     * @memberof ListUsersInGroupRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof ListUsersInGroupRequest
     */
    NextToken?: string;

    /**
     * @type {number}
     * @memberof ListUsersInGroupRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListUsersInGroupRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListUsersInGroupRequest
     */
    UserPoolUid: string;
}
