/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PermissionPointForListPermissionPointsOutput } from './permission-point-for-list-permission-points-output';
 /**
 * 
 *
 * @export
 * @interface ListPermissionPointsResponse
 */
export interface ListPermissionPointsResponse {

    /**
     * @type {number}
     * @memberof ListPermissionPointsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListPermissionPointsResponse
     */
    PageSize?: number;

    /**
     * @type {Array<PermissionPointForListPermissionPointsOutput>}
     * @memberof ListPermissionPointsResponse
     */
    PermissionPoints?: Array<PermissionPointForListPermissionPointsOutput>;

    /**
     * @type {number}
     * @memberof ListPermissionPointsResponse
     */
    TotalCount?: number;
}
