/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MemberDiffForCommitDepartmentSyncSessionOutput
 */
export interface MemberDiffForCommitDepartmentSyncSessionOutput {

    /**
     * @type {string}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    Action?: string;

    /**
     * @type {boolean}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    AfterIsPrimary?: boolean;

    /**
     * @type {string}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    AfterRole?: string;

    /**
     * @type {boolean}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    BeforeIsPrimary?: boolean;

    /**
     * @type {string}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    BeforeRole?: string;

    /**
     * @type {string}
     * @memberof MemberDiffForCommitDepartmentSyncSessionOutput
     */
    UserUid?: string;
}
