/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RulesConfigurationForCreateIamRoleAttachmentInput
 */
export interface RulesConfigurationForCreateIamRoleAttachmentInput {

    /**
     * @type {string}
     * @memberof RulesConfigurationForCreateIamRoleAttachmentInput
     */
    Claim?: string;

    /**
     * @type {string}
     * @memberof RulesConfigurationForCreateIamRoleAttachmentInput
     */
    MatchType?: string;

    /**
     * @type {string}
     * @memberof RulesConfigurationForCreateIamRoleAttachmentInput
     */
    Role?: string;

    /**
     * @type {string}
     * @memberof RulesConfigurationForCreateIamRoleAttachmentInput
     */
    Value?: string;
}
