/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AttributeMappingForUpdateIdentityProviderWeComOutput } from './attribute-mapping-for-update-identity-provider-we-com-output';
import { ClaimsPropagationConfigForUpdateIdentityProviderWeComOutput } from './claims-propagation-config-for-update-identity-provider-we-com-output';
import { EipRecordForUpdateIdentityProviderWeComOutput } from './eip-record-for-update-identity-provider-we-com-output';
import { ProviderOptionsForUpdateIdentityProviderWeComOutput } from './provider-options-for-update-identity-provider-we-com-output';
 /**
 * 
 *
 * @export
 * @interface UpdateIdentityProviderWeComResponse
 */
export interface UpdateIdentityProviderWeComResponse {

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    AgentId?: string;

    /**
     * @type {Array<AttributeMappingForUpdateIdentityProviderWeComOutput>}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    AttributeMappings?: Array<AttributeMappingForUpdateIdentityProviderWeComOutput>;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    AuthorizationEndpoint?: string;

    /**
     * @type {ClaimsPropagationConfigForUpdateIdentityProviderWeComOutput}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    ClaimsPropagationConfig?: ClaimsPropagationConfigForUpdateIdentityProviderWeComOutput;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    CorpId?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    DetailedUserInfoEndpoint?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    DomainVerifyContent?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    DomainVerifyFileName?: string;

    /**
     * @type {EipRecordForUpdateIdentityProviderWeComOutput}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    EipRecord?: EipRecordForUpdateIdentityProviderWeComOutput;

    /**
     * @type {boolean}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    Enabled?: boolean;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    Name?: string;

    /**
     * @type {Array<string>}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    OutboundEgressIps?: Array<string>;

    /**
     * @type {ProviderOptionsForUpdateIdentityProviderWeComOutput}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    ProviderOptions?: ProviderOptionsForUpdateIdentityProviderWeComOutput;

    /**
     * @type {boolean}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    RetrieveSensitiveUserInfoEnabled?: boolean;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    Secret?: string;

    /**
     * @type {boolean}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    SoleProviderConnection?: boolean;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    TokenEndpoint?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    Uid?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderWeComResponse
     */
    UserEndpoint?: string;
}
