/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateActionResponse
 */
export interface UpdateActionResponse {

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    ActionId?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    ActionKey?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    ActionName?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    Description?: string;

    /**
     * @type {boolean}
     * @memberof UpdateActionResponse
     */
    Enabled?: boolean;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    NamespaceId?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    ResourceType?: string;

    /**
     * @type {string}
     * @memberof UpdateActionResponse
     */
    UpdateTime?: string;
}
