/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomAttributesToUpsertForUpdateUsersInput } from './custom-attributes-to-upsert-for-update-users-input';
 /**
 * 
 *
 * @export
 * @interface UserForUpdateUsersInput
 */
export interface UserForUpdateUsersInput {

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Birthdate?: string;

    /**
     * @type {Array<CustomAttributesToUpsertForUpdateUsersInput>}
     * @memberof UserForUpdateUsersInput
     */
    CustomAttributesToUpsert?: Array<CustomAttributesToUpsertForUpdateUsersInput>;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Email?: string;

    /**
     * @type {boolean}
     * @memberof UserForUpdateUsersInput
     */
    EmailVerified?: boolean;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    FamilyName?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Gender?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    GivenName?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Locale?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    MiddleName?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Nickname?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    PhoneNumber?: string;

    /**
     * @type {boolean}
     * @memberof UserForUpdateUsersInput
     */
    PhoneNumberVerified?: boolean;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Picture?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    PreferredUsername?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Profile?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    UserMetadata?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    UserState?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    UserUid?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Website?: string;

    /**
     * @type {string}
     * @memberof UserForUpdateUsersInput
     */
    Zoneinfo?: string;
}
