/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssumedRoleUserForGetRoleCredentialsOutput } from './assumed-role-user-for-get-role-credentials-output';
import { CredentialsForGetRoleCredentialsOutput } from './credentials-for-get-role-credentials-output';
import { OIDCTokenInfoForGetRoleCredentialsOutput } from './oidctoken-info-for-get-role-credentials-output';
 /**
 * 
 *
 * @export
 * @interface VolcEngResponseForGetRoleCredentialsOutput
 */
export interface VolcEngResponseForGetRoleCredentialsOutput {

    /**
     * @type {AssumedRoleUserForGetRoleCredentialsOutput}
     * @memberof VolcEngResponseForGetRoleCredentialsOutput
     */
    AssumedRoleUser?: AssumedRoleUserForGetRoleCredentialsOutput;

    /**
     * @type {CredentialsForGetRoleCredentialsOutput}
     * @memberof VolcEngResponseForGetRoleCredentialsOutput
     */
    Credentials?: CredentialsForGetRoleCredentialsOutput;

    /**
     * @type {OIDCTokenInfoForGetRoleCredentialsOutput}
     * @memberof VolcEngResponseForGetRoleCredentialsOutput
     */
    OIDCTokenInfo?: OIDCTokenInfoForGetRoleCredentialsOutput;
}
