/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AlertingRuleTagForCreateAlertingRuleGroupInput } from './alerting-rule-tag-for-create-alerting-rule-group-input';
import { ItemForCreateAlertingRuleGroupInput } from './item-for-create-alerting-rule-group-input';
import { TagForCreateAlertingRuleGroupInput } from './tag-for-create-alerting-rule-group-input';
import { VariableForCreateAlertingRuleGroupInput } from './variable-for-create-alerting-rule-group-input';
 /**
 * 
 *
 * @export
 * @interface CreateAlertingRuleGroupRequest
 */
export interface CreateAlertingRuleGroupRequest {

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    AlertingRuleProjectName?: string;

    /**
     * @type {Array<AlertingRuleTagForCreateAlertingRuleGroupInput>}
     * @memberof CreateAlertingRuleGroupRequest
     */
    AlertingRuleTags?: Array<AlertingRuleTagForCreateAlertingRuleGroupInput>;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    AlertingRuleTemplateId: string;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    AlertingRuleTemplateVersion?: string;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    Description?: string;

    /**
     * @type {Array<ItemForCreateAlertingRuleGroupInput>}
     * @memberof CreateAlertingRuleGroupRequest
     */
    Items?: Array<ItemForCreateAlertingRuleGroupInput>;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    Name: string;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    NotifyGroupPolicyId: string;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    NotifyPolicyId?: string;

    /**
     * @type {Array<TagForCreateAlertingRuleGroupInput>}
     * @memberof CreateAlertingRuleGroupRequest
     */
    Tags?: Array<TagForCreateAlertingRuleGroupInput>;

    /**
     * @type {Array<VariableForCreateAlertingRuleGroupInput>}
     * @memberof CreateAlertingRuleGroupRequest
     */
    Variables?: Array<VariableForCreateAlertingRuleGroupInput>;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleGroupRequest
     */
    WorkspaceId: string;
}
