/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForCreateAlertingRuleTemplateInput } from './item-for-create-alerting-rule-template-input';
import { LabelForCreateAlertingRuleTemplateInput } from './label-for-create-alerting-rule-template-input';
import { TagForCreateAlertingRuleTemplateInput } from './tag-for-create-alerting-rule-template-input';
import { VariableForCreateAlertingRuleTemplateInput } from './variable-for-create-alerting-rule-template-input';
 /**
 * 
 *
 * @export
 * @interface CreateAlertingRuleTemplateRequest
 */
export interface CreateAlertingRuleTemplateRequest {

    /**
     * @type {string}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Description?: string;

    /**
     * @type {Array<ItemForCreateAlertingRuleTemplateInput>}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Items?: Array<ItemForCreateAlertingRuleTemplateInput>;

    /**
     * @type {Array<LabelForCreateAlertingRuleTemplateInput>}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Labels?: Array<LabelForCreateAlertingRuleTemplateInput>;

    /**
     * @type {string}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Name: string;

    /**
     * @type {Array<TagForCreateAlertingRuleTemplateInput>}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Tags?: Array<TagForCreateAlertingRuleTemplateInput>;

    /**
     * @type {Array<VariableForCreateAlertingRuleTemplateInput>}
     * @memberof CreateAlertingRuleTemplateRequest
     */
    Variables?: Array<VariableForCreateAlertingRuleTemplateInput>;
}
