/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DepartmentForListClawInstancesOutput
 */
export interface DepartmentForListClawInstancesOutput {

    /**
     * @type {string}
     * @memberof DepartmentForListClawInstancesOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof DepartmentForListClawInstancesOutput
     */
    NamePath?: string;

    /**
     * @type {string}
     * @memberof DepartmentForListClawInstancesOutput
     */
    Path?: string;

    /**
     * @type {string}
     * @memberof DepartmentForListClawInstancesOutput
     */
    Uid?: string;
}
