/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DnsServerForEnablePrivateEgressDnsInput } from './dns-server-for-enable-private-egress-dns-input';
 /**
 * 
 *
 * @export
 * @interface EnablePrivateEgressDnsRequest
 */
export interface EnablePrivateEgressDnsRequest {

    /**
     * @type {Array<DnsServerForEnablePrivateEgressDnsInput>}
     * @memberof EnablePrivateEgressDnsRequest
     */
    DnsServers?: Array<DnsServerForEnablePrivateEgressDnsInput>;

    /**
     * @type {Array<string>}
     * @memberof EnablePrivateEgressDnsRequest
     */
    Domains?: Array<string>;

    /**
     * @type {string}
     * @memberof EnablePrivateEgressDnsRequest
     */
    PrivateEgressId: string;

    /**
     * @type {string}
     * @memberof EnablePrivateEgressDnsRequest
     */
    RequestId: string;

    /**
     * @type {string}
     * @memberof EnablePrivateEgressDnsRequest
     */
    SpaceId: string;
}
