/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateForGetClawOmniSpaceTemplateOutput } from './template-for-get-claw-omni-space-template-output';
 /**
 * 
 *
 * @export
 * @interface GetClawOmniSpaceTemplateResponse
 */
export interface GetClawOmniSpaceTemplateResponse {

    /**
     * @type {Array<TemplateForGetClawOmniSpaceTemplateOutput>}
     * @memberof GetClawOmniSpaceTemplateResponse
     */
    Templates?: Array<TemplateForGetClawOmniSpaceTemplateOutput>;
}
