/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetUserPoolClientResponse
 */
export interface GetUserPoolClientResponse {

    /**
     * @type {string}
     * @memberof GetUserPoolClientResponse
     */
    ClientId?: string;

    /**
     * @type {string}
     * @memberof GetUserPoolClientResponse
     */
    ClientSecret?: string;
}
