/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AuthorizerForListClawInstancesOutput } from './authorizer-for-list-claw-instances-output';
 /**
 * 
 *
 * @export
 * @interface InboundAuthorizerConfigurationForListClawInstancesOutput
 */
export interface InboundAuthorizerConfigurationForListClawInstancesOutput {

    /**
     * @type {AuthorizerForListClawInstancesOutput}
     * @memberof InboundAuthorizerConfigurationForListClawInstancesOutput
     */
    Authorizer?: AuthorizerForListClawInstancesOutput;

    /**
     * @type {string}
     * @memberof InboundAuthorizerConfigurationForListClawInstancesOutput
     */
    AuthorizerType?: string;
}
