/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListUsersInput } from './filter-for-list-users-input';
 /**
 * 
 *
 * @export
 * @interface ListUsersRequest
 */
export interface ListUsersRequest {

    /**
     * @type {FilterForListUsersInput}
     * @memberof ListUsersRequest
     */
    Filter?: FilterForListUsersInput;

    /**
     * @type {number}
     * @memberof ListUsersRequest
     */
    PageNumber: number;

    /**
     * @type {number}
     * @memberof ListUsersRequest
     */
    PageSize: number;

    /**
     * @type {string}
     * @memberof ListUsersRequest
     */
    SpaceId: string;
}
