/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModelForListClawOmniSpaceEnabledModelsOutput
 */
export interface ModelForListClawOmniSpaceEnabledModelsOutput {

    /**
     * @type {string}
     * @memberof ModelForListClawOmniSpaceEnabledModelsOutput
     */
    ApiKey?: string;

    /**
     * @type {string}
     * @memberof ModelForListClawOmniSpaceEnabledModelsOutput
     */
    ModelBaseUrl?: string;

    /**
     * @type {string}
     * @memberof ModelForListClawOmniSpaceEnabledModelsOutput
     */
    ModelId?: string;

    /**
     * @type {string}
     * @memberof ModelForListClawOmniSpaceEnabledModelsOutput
     */
    ModelSource?: string;
}
