/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StopClawOmniInstanceCommandJobRequest
 */
export interface StopClawOmniInstanceCommandJobRequest {

    /**
     * @type {string}
     * @memberof StopClawOmniInstanceCommandJobRequest
     */
    JobId: string;

    /**
     * @type {string}
     * @memberof StopClawOmniInstanceCommandJobRequest
     */
    SpaceId: string;
}
