/* tslint:disable */
/* eslint-disable */
/**
 * arkclaw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeOutput } from './allowed-claims-and-value-for-create-identity-provider-token-exchange-output';
import { AttributeMappingForCreateIdentityProviderTokenExchangeOutput } from './attribute-mapping-for-create-identity-provider-token-exchange-output';
import { ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeOutput } from './claims-propagation-config-for-create-identity-provider-token-exchange-output';
import { EipRecordForCreateIdentityProviderTokenExchangeOutput } from './eip-record-for-create-identity-provider-token-exchange-output';
import { ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeOutput } from './external-identity-provider-configuration-for-create-identity-provider-token-exchange-output';
import { ProviderOptionsForCreateIdentityProviderTokenExchangeOutput } from './provider-options-for-create-identity-provider-token-exchange-output';
 /**
 * 
 *
 * @export
 * @interface TokenExchangeForCreateIdentityProviderTokenExchangeOutput
 */
export interface TokenExchangeForCreateIdentityProviderTokenExchangeOutput {

    /**
     * @type {Array<string>}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    AllowedAudiences?: Array<string>;

    /**
     * @type {Array<AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeOutput>}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    AllowedClaimsAndValues?: Array<AllowedClaimsAndValueForCreateIdentityProviderTokenExchangeOutput>;

    /**
     * @type {Array<string>}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    AllowedClients?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    AllowedScopes?: Array<string>;

    /**
     * @type {Array<AttributeMappingForCreateIdentityProviderTokenExchangeOutput>}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    AttributeMappings?: Array<AttributeMappingForCreateIdentityProviderTokenExchangeOutput>;

    /**
     * @type {ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeOutput}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    ClaimsPropagationConfig?: ClaimsPropagationConfigForCreateIdentityProviderTokenExchangeOutput;

    /**
     * @type {EipRecordForCreateIdentityProviderTokenExchangeOutput}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    EipRecord?: EipRecordForCreateIdentityProviderTokenExchangeOutput;

    /**
     * @type {boolean}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    Enabled?: boolean;

    /**
     * @type {ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeOutput}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    ExternalIdentityProviderConfiguration?: ExternalIdentityProviderConfigurationForCreateIdentityProviderTokenExchangeOutput;

    /**
     * @type {string}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    Provider?: string;

    /**
     * @type {ProviderOptionsForCreateIdentityProviderTokenExchangeOutput}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    ProviderOptions?: ProviderOptionsForCreateIdentityProviderTokenExchangeOutput;

    /**
     * @type {string}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    ProviderType?: string;

    /**
     * @type {string}
     * @memberof TokenExchangeForCreateIdentityProviderTokenExchangeOutput
     */
    Uid?: string;
}
