/* tslint:disable */
/* eslint-disable */
/**
 * volcsms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client, ClientConfig, Command, buildRequestConfigFromMetaPath, CommandOutput } from '@volcengine/sdk-core';

import { ApplySmsSignatureV2Request } from './types/index';
import { ApplySmsSignatureV2Response } from './types/index';
import { ApplySmsTemplateV2Request } from './types/index';
import { ApplySmsTemplateV2Response } from './types/index';
import { ConsentBatchTaskRequest } from './types/index';
import { ConsentBatchTaskResponse } from './types/index';
import { DeleteBatchTaskRequest } from './types/index';
import { DeleteBatchTaskResponse } from './types/index';
import { GetBatchTaskDetailRequest } from './types/index';
import { GetBatchTaskDetailResponse } from './types/index';
import { GetBatchTaskListRequest } from './types/index';
import { GetBatchTaskListResponse } from './types/index';
import { GetSignatureIdentificationListRequest } from './types/index';
import { GetSignatureIdentificationListResponse } from './types/index';
import { GetSubAccountDetailRequest } from './types/index';
import { GetSubAccountDetailResponse } from './types/index';
import { GetUploadTosURLRequest } from './types/index';
import { GetUploadTosURLResponse } from './types/index';
import { ListSecondTemplateRequest } from './types/index';
import { ListSecondTemplateResponse } from './types/index';
import { ListSignatureForAgentRequest } from './types/index';
import { ListSignatureForAgentResponse } from './types/index';
import { ListSmsSendLogForAgentRequest } from './types/index';
import { ListSmsSendLogForAgentResponse } from './types/index';
import { ListSmsTemplateForAgentRequest } from './types/index';
import { ListSmsTemplateForAgentResponse } from './types/index';
import { ListSubAccountForAgentRequest } from './types/index';
import { ListSubAccountForAgentResponse } from './types/index';
import { ListTotalSendCountStatForAgentRequest } from './types/index';
import { ListTotalSendCountStatForAgentResponse } from './types/index';
import { SendSmsForAgentRequest } from './types/index';
import { SendSmsForAgentResponse } from './types/index';
import { SetBatchTaskRequest } from './types/index';
import { SetBatchTaskResponse } from './types/index';
import { TemplateUploadDemoRequest } from './types/index';
import { TemplateUploadDemoResponse } from './types/index';

// ============================================================================
// Output Type Definitions
// ============================================================================
export type ApplySmsSignatureV2CommandOutput = CommandOutput<ApplySmsSignatureV2Response>;
export type ApplySmsTemplateV2CommandOutput = CommandOutput<ApplySmsTemplateV2Response>;
export type ConsentBatchTaskCommandOutput = CommandOutput<ConsentBatchTaskResponse>;
export type DeleteBatchTaskCommandOutput = CommandOutput<DeleteBatchTaskResponse>;
export type GetBatchTaskDetailCommandOutput = CommandOutput<GetBatchTaskDetailResponse>;
export type GetBatchTaskListCommandOutput = CommandOutput<GetBatchTaskListResponse>;
export type GetSignatureIdentificationListCommandOutput = CommandOutput<GetSignatureIdentificationListResponse>;
export type GetSubAccountDetailCommandOutput = CommandOutput<GetSubAccountDetailResponse>;
export type GetUploadTosURLCommandOutput = CommandOutput<GetUploadTosURLResponse>;
export type ListSecondTemplateCommandOutput = CommandOutput<ListSecondTemplateResponse>;
export type ListSignatureForAgentCommandOutput = CommandOutput<ListSignatureForAgentResponse>;
export type ListSmsSendLogForAgentCommandOutput = CommandOutput<ListSmsSendLogForAgentResponse>;
export type ListSmsTemplateForAgentCommandOutput = CommandOutput<ListSmsTemplateForAgentResponse>;
export type ListSubAccountForAgentCommandOutput = CommandOutput<ListSubAccountForAgentResponse>;
export type ListTotalSendCountStatForAgentCommandOutput = CommandOutput<ListTotalSendCountStatForAgentResponse>;
export type SendSmsForAgentCommandOutput = CommandOutput<SendSmsForAgentResponse>;
export type SetBatchTaskCommandOutput = CommandOutput<SetBatchTaskResponse>;
export type TemplateUploadDemoCommandOutput = CommandOutput<TemplateUploadDemoResponse>;

/**
 * VOLCSMSClient Service Client
 */
export class VOLCSMSClient extends Client {
  constructor(config: ClientConfig = {}) {
    super({
      protocol: 'https',
      region: 'cn-beijing',
      ...config,
    });
  }
}

/**
 * Command to ApplySmsSignatureV2
 */
export class ApplySmsSignatureV2Command extends Command<
  ApplySmsSignatureV2Request,
  ApplySmsSignatureV2CommandOutput,
  'ApplySmsSignatureV2Command'
> {
  static readonly metaPath = '/ApplySmsSignatureV2/2026-01-01/volcsms/post/application_json/';

  constructor(input: ApplySmsSignatureV2Request) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ApplySmsSignatureV2Command.metaPath);
  }
}
/**
 * Command to ApplySmsTemplateV2
 */
export class ApplySmsTemplateV2Command extends Command<
  ApplySmsTemplateV2Request,
  ApplySmsTemplateV2CommandOutput,
  'ApplySmsTemplateV2Command'
> {
  static readonly metaPath = '/ApplySmsTemplateV2/2026-01-01/volcsms/post/application_json/';

  constructor(input: ApplySmsTemplateV2Request) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ApplySmsTemplateV2Command.metaPath);
  }
}
/**
 * Command to ConsentBatchTask
 */
export class ConsentBatchTaskCommand extends Command<
  ConsentBatchTaskRequest,
  ConsentBatchTaskCommandOutput,
  'ConsentBatchTaskCommand'
> {
  static readonly metaPath = '/ConsentBatchTask/2026-01-01/volcsms/post/application_json/';

  constructor(input: ConsentBatchTaskRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ConsentBatchTaskCommand.metaPath);
  }
}
/**
 * Command to DeleteBatchTask
 */
export class DeleteBatchTaskCommand extends Command<
  DeleteBatchTaskRequest,
  DeleteBatchTaskCommandOutput,
  'DeleteBatchTaskCommand'
> {
  static readonly metaPath = '/DeleteBatchTask/2026-01-01/volcsms/post/application_json/';

  constructor(input: DeleteBatchTaskRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBatchTaskCommand.metaPath);
  }
}
/**
 * Command to GetBatchTaskDetail
 */
export class GetBatchTaskDetailCommand extends Command<
  GetBatchTaskDetailRequest,
  GetBatchTaskDetailCommandOutput,
  'GetBatchTaskDetailCommand'
> {
  static readonly metaPath = '/GetBatchTaskDetail/2026-01-01/volcsms/get/text_plain/';

  constructor(input: GetBatchTaskDetailRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetBatchTaskDetailCommand.metaPath);
  }
}
/**
 * Command to GetBatchTaskList
 */
export class GetBatchTaskListCommand extends Command<
  GetBatchTaskListRequest,
  GetBatchTaskListCommandOutput,
  'GetBatchTaskListCommand'
> {
  static readonly metaPath = '/GetBatchTaskList/2026-01-01/volcsms/get/text_plain/';

  constructor(input: GetBatchTaskListRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetBatchTaskListCommand.metaPath);
  }
}
/**
 * Command to GetSignatureIdentificationList
 */
export class GetSignatureIdentificationListCommand extends Command<
  GetSignatureIdentificationListRequest,
  GetSignatureIdentificationListCommandOutput,
  'GetSignatureIdentificationListCommand'
> {
  static readonly metaPath = '/GetSignatureIdentificationList/2026-01-01/volcsms/post/application_json/';

  constructor(input: GetSignatureIdentificationListRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetSignatureIdentificationListCommand.metaPath);
  }
}
/**
 * Command to GetSubAccountDetail
 */
export class GetSubAccountDetailCommand extends Command<
  GetSubAccountDetailRequest,
  GetSubAccountDetailCommandOutput,
  'GetSubAccountDetailCommand'
> {
  static readonly metaPath = '/GetSubAccountDetail/2026-01-01/volcsms/get/text_plain/';

  constructor(input: GetSubAccountDetailRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetSubAccountDetailCommand.metaPath);
  }
}
/**
 * Command to GetUploadTosURL
 */
export class GetUploadTosURLCommand extends Command<
  GetUploadTosURLRequest,
  GetUploadTosURLCommandOutput,
  'GetUploadTosURLCommand'
> {
  static readonly metaPath = '/GetUploadTosURL/2026-01-01/volcsms/get/text_plain/';

  constructor(input: GetUploadTosURLRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetUploadTosURLCommand.metaPath);
  }
}
/**
 * Command to ListSecondTemplate
 */
export class ListSecondTemplateCommand extends Command<
  ListSecondTemplateRequest,
  ListSecondTemplateCommandOutput,
  'ListSecondTemplateCommand'
> {
  static readonly metaPath = '/ListSecondTemplate/2026-01-01/volcsms/get/text_plain/';

  constructor(input: ListSecondTemplateRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSecondTemplateCommand.metaPath);
  }
}
/**
 * Command to ListSignatureForAgent
 */
export class ListSignatureForAgentCommand extends Command<
  ListSignatureForAgentRequest,
  ListSignatureForAgentCommandOutput,
  'ListSignatureForAgentCommand'
> {
  static readonly metaPath = '/ListSignatureForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: ListSignatureForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSignatureForAgentCommand.metaPath);
  }
}
/**
 * Command to ListSmsSendLogForAgent
 */
export class ListSmsSendLogForAgentCommand extends Command<
  ListSmsSendLogForAgentRequest,
  ListSmsSendLogForAgentCommandOutput,
  'ListSmsSendLogForAgentCommand'
> {
  static readonly metaPath = '/ListSmsSendLogForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: ListSmsSendLogForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSmsSendLogForAgentCommand.metaPath);
  }
}
/**
 * Command to ListSmsTemplateForAgent
 */
export class ListSmsTemplateForAgentCommand extends Command<
  ListSmsTemplateForAgentRequest,
  ListSmsTemplateForAgentCommandOutput,
  'ListSmsTemplateForAgentCommand'
> {
  static readonly metaPath = '/ListSmsTemplateForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: ListSmsTemplateForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSmsTemplateForAgentCommand.metaPath);
  }
}
/**
 * Command to ListSubAccountForAgent
 */
export class ListSubAccountForAgentCommand extends Command<
  ListSubAccountForAgentRequest,
  ListSubAccountForAgentCommandOutput,
  'ListSubAccountForAgentCommand'
> {
  static readonly metaPath = '/ListSubAccountForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: ListSubAccountForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSubAccountForAgentCommand.metaPath);
  }
}
/**
 * Command to ListTotalSendCountStatForAgent
 */
export class ListTotalSendCountStatForAgentCommand extends Command<
  ListTotalSendCountStatForAgentRequest,
  ListTotalSendCountStatForAgentCommandOutput,
  'ListTotalSendCountStatForAgentCommand'
> {
  static readonly metaPath = '/ListTotalSendCountStatForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: ListTotalSendCountStatForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListTotalSendCountStatForAgentCommand.metaPath);
  }
}
/**
 * Command to SendSmsForAgent
 */
export class SendSmsForAgentCommand extends Command<
  SendSmsForAgentRequest,
  SendSmsForAgentCommandOutput,
  'SendSmsForAgentCommand'
> {
  static readonly metaPath = '/SendSmsForAgent/2026-01-01/volcsms/post/application_json/';

  constructor(input: SendSmsForAgentRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(SendSmsForAgentCommand.metaPath);
  }
}
/**
 * Command to SetBatchTask
 */
export class SetBatchTaskCommand extends Command<
  SetBatchTaskRequest,
  SetBatchTaskCommandOutput,
  'SetBatchTaskCommand'
> {
  static readonly metaPath = '/SetBatchTask/2026-01-01/volcsms/post/application_json/';

  constructor(input: SetBatchTaskRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(SetBatchTaskCommand.metaPath);
  }
}
/**
 * Command to TemplateUploadDemo
 */
export class TemplateUploadDemoCommand extends Command<
  TemplateUploadDemoRequest,
  TemplateUploadDemoCommandOutput,
  'TemplateUploadDemoCommand'
> {
  static readonly metaPath = '/TemplateUploadDemo/2026-01-01/volcsms/post/application_json/';

  constructor(input: TemplateUploadDemoRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(TemplateUploadDemoCommand.metaPath);
  }
}

export default {
  VOLCSMSClient,
  ApplySmsSignatureV2Command,
  ApplySmsTemplateV2Command,
  ConsentBatchTaskCommand,
  DeleteBatchTaskCommand,
  GetBatchTaskDetailCommand,
  GetBatchTaskListCommand,
  GetSignatureIdentificationListCommand,
  GetSubAccountDetailCommand,
  GetUploadTosURLCommand,
  ListSecondTemplateCommand,
  ListSignatureForAgentCommand,
  ListSmsSendLogForAgentCommand,
  ListSmsTemplateForAgentCommand,
  ListSubAccountForAgentCommand,
  ListTotalSendCountStatForAgentCommand,
  SendSmsForAgentCommand,
  SetBatchTaskCommand,
  TemplateUploadDemoCommand,
};
