/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransitRouterRouteEntryForDescribeTransitRouterRouteEntriesOutput } from './transit-router-route-entry-for-describe-transit-router-route-entries-output';
 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterRouteEntriesResponse
 */
export interface DescribeTransitRouterRouteEntriesResponse {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteEntriesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteEntriesResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteEntriesResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<TransitRouterRouteEntryForDescribeTransitRouterRouteEntriesOutput>}
     * @memberof DescribeTransitRouterRouteEntriesResponse
     */
    TransitRouterRouteEntries?: Array<TransitRouterRouteEntryForDescribeTransitRouterRouteEntriesOutput>;
}
