/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransitRouterRouteTablePropagationForDescribeTransitRouterRouteTablePropagationsOutput } from './transit-router-route-table-propagation-for-describe-transit-router-route-table-propagations-output';
 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterRouteTablePropagationsResponse
 */
export interface DescribeTransitRouterRouteTablePropagationsResponse {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteTablePropagationsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteTablePropagationsResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteTablePropagationsResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<TransitRouterRouteTablePropagationForDescribeTransitRouterRouteTablePropagationsOutput>}
     * @memberof DescribeTransitRouterRouteTablePropagationsResponse
     */
    TransitRouterRouteTablePropagations?: Array<TransitRouterRouteTablePropagationForDescribeTransitRouterRouteTablePropagationsOutput>;
}
