/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterRouteTablePropagationsRequest
 */
export interface DescribeTransitRouterRouteTablePropagationsRequest {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteTablePropagationsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterRouteTablePropagationsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeTransitRouterRouteTablePropagationsRequest
     */
    TransitRouterAttachmentId?: string;

    /**
     * @type {string}
     * @memberof DescribeTransitRouterRouteTablePropagationsRequest
     */
    TransitRouterRouteTableId: string;
}
