/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AlarmNodeForGetRaspAlarmSummaryInfoOutput } from './alarm-node-for-get-rasp-alarm-summary-info-output';
import { AuditLogAlarmForGetRaspAlarmSummaryInfoOutput } from './audit-log-alarm-for-get-rasp-alarm-summary-info-output';
import { ExtendInfoForGetRaspAlarmSummaryInfoOutput } from './extend-info-for-get-rasp-alarm-summary-info-output';
import { KillChainNodeListForGetRaspAlarmSummaryInfoOutput } from './kill-chain-node-list-for-get-rasp-alarm-summary-info-output';
import { VirusHitDataListForGetRaspAlarmSummaryInfoOutput } from './virus-hit-data-list-for-get-rasp-alarm-summary-info-output';
 /**
 * 
 *
 * @export
 * @interface AlarmContentForGetRaspAlarmSummaryInfoOutput
 */
export interface AlarmContentForGetRaspAlarmSummaryInfoOutput {

    /**
     * @type {AlarmNodeForGetRaspAlarmSummaryInfoOutput}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    AlarmNode?: AlarmNodeForGetRaspAlarmSummaryInfoOutput;

    /**
     * @type {AuditLogAlarmForGetRaspAlarmSummaryInfoOutput}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    AuditLogAlarm?: AuditLogAlarmForGetRaspAlarmSummaryInfoOutput;

    /**
     * @type {ExtendInfoForGetRaspAlarmSummaryInfoOutput}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    ExtendInfo?: ExtendInfoForGetRaspAlarmSummaryInfoOutput;

    /**
     * @type {boolean}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    FileDownloadable?: boolean;

    /**
     * @type {Array<KillChainNodeListForGetRaspAlarmSummaryInfoOutput>}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    KillChainNodeList?: Array<KillChainNodeListForGetRaspAlarmSummaryInfoOutput>;

    /**
     * @type {Array<string>}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    KillChainStepList?: Array<string>;

    /**
     * @type {Array<VirusHitDataListForGetRaspAlarmSummaryInfoOutput>}
     * @memberof AlarmContentForGetRaspAlarmSummaryInfoOutput
     */
    VirusHitDataList?: Array<VirusHitDataListForGetRaspAlarmSummaryInfoOutput>;
}
