/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
 */
export interface AuditLogAlarmForGetVirusAlarmSummaryInfoOutput {

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    authorization_reason?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    binding_roleref?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    binding_subject?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    body?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    exec_command?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    exec_container?: string;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    images?: Array<string>;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    impersonated_user_groups?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    impersonated_user_name?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    node_host?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    node_name?: string;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    privileged_capabilities?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    read_only_mounts?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    read_write_mounts?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    real_user_groups?: Array<string>;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    real_user_name?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    reason_user_agent?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    request_uri?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    resource_kind?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    resource_name?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    resource_namespace?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    response_code?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    response_reason?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    response_status?: string;

    /**
     * @type {Array<string>}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    shared_namespaces?: Array<string>;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    source_ip?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    source_ip_asset?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    user_agent?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    user_groups?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    user_name?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    verb?: string;

    /**
     * @type {string}
     * @memberof AuditLogAlarmForGetVirusAlarmSummaryInfoOutput
     */
    workload_asset?: string;
}
