/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BaseInfoForGetHidsAlarmInfoOutput
 */
export interface BaseInfoForGetHidsAlarmInfoOutput {

    /**
     * @type {string}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    AgentID?: string;

    /**
     * @type {string}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    Hostname?: string;

    /**
     * @type {Array<string>}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    InIPList?: Array<string>;

    /**
     * @type {string}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    Os?: string;

    /**
     * @type {string}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    OsPlatform?: string;

    /**
     * @type {Array<string>}
     * @memberof BaseInfoForGetHidsAlarmInfoOutput
     */
    OutIPList?: Array<string>;
}
