/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RiskNumForListBaselinesOutput } from './risk-num-for-list-baselines-output';
 /**
 * 
 *
 * @export
 * @interface BaselineListForListBaselinesOutput
 */
export interface BaselineListForListBaselinesOutput {

    /**
     * @type {number}
     * @memberof BaselineListForListBaselinesOutput
     */
    AffectedHost?: number;

    /**
     * @type {number}
     * @memberof BaselineListForListBaselinesOutput
     */
    BaselineID?: number;

    /**
     * @type {string}
     * @memberof BaselineListForListBaselinesOutput
     */
    BaselineName?: string;

    /**
     * @type {string}
     * @memberof BaselineListForListBaselinesOutput
     */
    BaselineNameEn?: string;

    /**
     * @type {number}
     * @memberof BaselineListForListBaselinesOutput
     */
    CheckListNum?: number;

    /**
     * @type {number}
     * @memberof BaselineListForListBaselinesOutput
     */
    DetectProgress?: number;

    /**
     * @type {string}
     * @memberof BaselineListForListBaselinesOutput
     */
    DetectStatus?: string;

    /**
     * @type {number}
     * @memberof BaselineListForListBaselinesOutput
     */
    LastDetectedTime?: number;

    /**
     * @type {RiskNumForListBaselinesOutput}
     * @memberof BaselineListForListBaselinesOutput
     */
    RiskNum?: RiskNumForListBaselinesOutput;
}
