/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CurrentQuotaForCheckInstallAgentClientOutput } from './current-quota-for-check-install-agent-client-output';
import { RequestQuotaForCheckInstallAgentClientOutput } from './request-quota-for-check-install-agent-client-output';
 /**
 * 
 *
 * @export
 * @interface CheckInstallAgentClientResponse
 */
export interface CheckInstallAgentClientResponse {

    /**
     * @type {Array<string>}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoAgentIDs?: Array<string>;

    /**
     * @type {number}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoCount?: number;

    /**
     * @type {number}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoEnableCount?: number;

    /**
     * @type {Array<string>}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoEnableIDs?: Array<string>;

    /**
     * @type {number}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoInstallAndEnableCount?: number;

    /**
     * @type {Array<string>}
     * @memberof CheckInstallAgentClientResponse
     */
    AutoInstallAndEnableIDs?: Array<string>;

    /**
     * @type {CurrentQuotaForCheckInstallAgentClientOutput}
     * @memberof CheckInstallAgentClientResponse
     */
    CurrentQuota?: CurrentQuotaForCheckInstallAgentClientOutput;

    /**
     * @type {boolean}
     * @memberof CheckInstallAgentClientResponse
     */
    HitLimit?: boolean;

    /**
     * @type {number}
     * @memberof CheckInstallAgentClientResponse
     */
    ManualCount?: number;

    /**
     * @type {RequestQuotaForCheckInstallAgentClientOutput}
     * @memberof CheckInstallAgentClientResponse
     */
    RequestQuota?: RequestQuotaForCheckInstallAgentClientOutput;
}
