/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RangeForDeleteWhiteListsInput } from './range-for-delete-white-lists-input';
import { RangeIncludeGlobalForDeleteWhiteListsInput } from './range-include-global-for-delete-white-lists-input';
 /**
 * 
 *
 * @export
 * @interface ConditionsForDeleteWhiteListsInput
 */
export interface ConditionsForDeleteWhiteListsInput {

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    CloudProviders?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    Desc?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    LeafGroupIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    MatchAlarmName?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    MatchContent?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    MatchKey?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    Name?: string;

    /**
     * @type {RangeForDeleteWhiteListsInput}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    Range?: RangeForDeleteWhiteListsInput;

    /**
     * @type {RangeIncludeGlobalForDeleteWhiteListsInput}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    RangeIncludeGlobal?: RangeIncludeGlobalForDeleteWhiteListsInput;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    TopGroupID?: string;

    /**
     * @type {number}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    UpdateTimeEnd?: number;

    /**
     * @type {number}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    UpdateTimeStart?: number;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    User?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDeleteWhiteListsInput
     */
    WhiteListID?: string;
}
