/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConditionsForBaselineChecklistWhiteInput
 */
export interface ConditionsForBaselineChecklistWhiteInput {

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    AgentID?: string;

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    AgentIP?: string;

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    AgentTags?: string;

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    CheckName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    CloudProviders?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    Hostname?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    LeafGroupIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForBaselineChecklistWhiteInput
     */
    TopGroupID?: string;
}
