/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RiskForDisableHostImportantProtectInput } from './risk-for-disable-host-important-protect-input';
 /**
 * 
 *
 * @export
 * @interface ConditionsForDisableHostImportantProtectInput
 */
export interface ConditionsForDisableHostImportantProtectInput {

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    AgentID?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    AgentIDList?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    AgentStatus?: Array<string>;

    /**
     * @type {boolean}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    AllHost?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    CloudProviders?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Hostname?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Ip?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    LeafGroupIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Os?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Platforms?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    ProxyName?: string;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    ProxyServerName?: string;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Regions?: Array<string>;

    /**
     * @type {RiskForDisableHostImportantProtectInput}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Risk?: RiskForDisableHostImportantProtectInput;

    /**
     * @type {boolean}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    SecurityEnhancement?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Status?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Tags?: Array<string>;

    /**
     * @type {string}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    TopGroupID?: string;

    /**
     * @type {boolean}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    VirusFileAutoIsolate?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    Visibility?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ConditionsForDisableHostImportantProtectInput
     */
    VpcIds?: Array<string>;
}
