/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AttributionListForListRaspAlarmsOutput } from './attribution-list-for-list-rasp-alarms-output';
import { ClusterForListRaspAlarmsOutput } from './cluster-for-list-rasp-alarms-output';
import { HostForListRaspAlarmsOutput } from './host-for-list-rasp-alarms-output';
 /**
 * 
 *
 * @export
 * @interface DataForListRaspAlarmsOutput
 */
export interface DataForListRaspAlarmsOutput {

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    AgentGroup?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    AgentID?: string;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlarmCount?: number;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlarmHandleResult?: number;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlarmHostname?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlarmID?: string;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlarmTime?: number;

    /**
     * @type {Array<string>}
     * @memberof DataForListRaspAlarmsOutput
     */
    AlertTags?: Array<string>;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    AnalysisRecordUUID?: string;

    /**
     * @type {Array<string>}
     * @memberof DataForListRaspAlarmsOutput
     */
    Args?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DataForListRaspAlarmsOutput
     */
    ArgsList?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DataForListRaspAlarmsOutput
     */
    ArgvList?: Array<string>;

    /**
     * @type {Array<AttributionListForListRaspAlarmsOutput>}
     * @memberof DataForListRaspAlarmsOutput
     */
    AttributionList?: Array<AttributionListForListRaspAlarmsOutput>;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    _Class?: string;

    /**
     * @type {ClusterForListRaspAlarmsOutput}
     * @memberof DataForListRaspAlarmsOutput
     */
    Cluster?: ClusterForListRaspAlarmsOutput;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Confidence?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    DataType?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    ErrorReason?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    EventID?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    EventName?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Exe?: string;

    /**
     * @type {boolean}
     * @memberof DataForListRaspAlarmsOutput
     */
    FileDownloadable?: boolean;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    FileHash?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    FilePath?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    GroupPath?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    HandleFailReason?: string;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    HandleTime?: number;

    /**
     * @type {HostForListRaspAlarmsOutput}
     * @memberof DataForListRaspAlarmsOutput
     */
    Host?: HostForListRaspAlarmsOutput;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    ImageName?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    InDocker?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    LLMAnalysisResult?: string;

    /**
     * @type {boolean}
     * @memberof DataForListRaspAlarmsOutput
     */
    LLMProcessed?: boolean;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    LastAlarmTime?: number;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Level?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    MlpInstanceID?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    MlpPrivateIP?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    NsPid?: string;

    /**
     * @type {Array<string>}
     * @memberof DataForListRaspAlarmsOutput
     */
    OperationList?: Array<string>;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    OsType?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Pid?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    ProbeHook?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Region?: string;

    /**
     * @type {boolean}
     * @memberof DataForListRaspAlarmsOutput
     */
    SecurityIntelligenceComplete?: boolean;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    SecurityIntelligenceResult?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Sid?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    StackTraceFormat?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    StackTraceHash?: string;

    /**
     * @type {number}
     * @memberof DataForListRaspAlarmsOutput
     */
    Status?: number;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    TraceID?: string;

    /**
     * @type {string}
     * @memberof DataForListRaspAlarmsOutput
     */
    Type?: string;
}
