/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForListRepoImageLayerVulnOutput
 */
export interface DataForListRepoImageLayerVulnOutput {

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    ID?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    PkgName?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    PkgPath?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    PkgType?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    PkgVer?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    Severity?: string;

    /**
     * @type {string}
     * @memberof DataForListRepoImageLayerVulnOutput
     */
    VulnID?: string;
}
