/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForGetFingerprintPortOutput
 */
export interface DataForGetFingerprintPortOutput {

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    AgentID?: string;

    /**
     * @type {Array<string>}
     * @memberof DataForGetFingerprintPortOutput
     */
    AgentTags?: Array<string>;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Cmdline?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Comm?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    ContainerID?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    ContainerName?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Dip?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Dport?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    EipAddress?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Exe?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Family?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Hostname?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    ID?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Inode?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    _Interface?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Pid?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    PrimaryIpAddress?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Sip?: string;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Sport?: string;

    /**
     * @type {number}
     * @memberof DataForGetFingerprintPortOutput
     */
    StartTime?: number;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    State?: string;

    /**
     * @type {number}
     * @memberof DataForGetFingerprintPortOutput
     */
    Type?: number;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Uid?: string;

    /**
     * @type {number}
     * @memberof DataForGetFingerprintPortOutput
     */
    UpdateTime?: number;

    /**
     * @type {string}
     * @memberof DataForGetFingerprintPortOutput
     */
    Username?: string;
}
