/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BasicQueryForDeleteAutoIsolateAgentListInput } from './basic-query-for-delete-auto-isolate-agent-list-input';
 /**
 * 
 *
 * @export
 * @interface DeleteAutoIsolateAgentListRequest
 */
export interface DeleteAutoIsolateAgentListRequest {

    /**
     * @type {Array<string>}
     * @memberof DeleteAutoIsolateAgentListRequest
     */
    AgentIDList?: Array<string>;

    /**
     * @type {BasicQueryForDeleteAutoIsolateAgentListInput}
     * @memberof DeleteAutoIsolateAgentListRequest
     */
    basicQuery?: BasicQueryForDeleteAutoIsolateAgentListInput;
}
