/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionsForDeleteRaspConfigInput } from './conditions-for-delete-rasp-config-input';
 /**
 * 
 *
 * @export
 * @interface DeleteRaspConfigRequest
 */
export interface DeleteRaspConfigRequest {

    /**
     * @type {ConditionsForDeleteRaspConfigInput}
     * @memberof DeleteRaspConfigRequest
     */
    Conditions?: ConditionsForDeleteRaspConfigInput;

    /**
     * @type {Array<string>}
     * @memberof DeleteRaspConfigRequest
     */
    IDList?: Array<string>;
}
