/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EcsInstanceForListMultiLevelAssetHostsOutput
 */
export interface EcsInstanceForListMultiLevelAssetHostsOutput {

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    AccessKey?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    AccountID?: string;

    /**
     * @type {number}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Cpu?: number;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    CreatedAt?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    ECSUpdateAt?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    EipAddress?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    HostName?: string;

    /**
     * @type {Array<string>}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    IPList?: Array<string>;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    InstanceName?: string;

    /**
     * @type {number}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Mem?: number;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    OsName?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    OsType?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Platform?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    PlatformVersion?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    PrimaryIpAddress?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Region?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    SecurityEnhancementStrategy?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Status?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    Visibility?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    VpcId?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    VpcName?: string;

    /**
     * @type {string}
     * @memberof EcsInstanceForListMultiLevelAssetHostsOutput
     */
    ZoneId?: string;
}
