/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RiskForExportAssetCenterDevsInput } from './risk-for-export-asset-center-devs-input';
 /**
 * 
 *
 * @export
 * @interface ExportAssetCenterDevsRequest
 */
export interface ExportAssetCenterDevsRequest {

    /**
     * @type {string}
     * @memberof ExportAssetCenterDevsRequest
     */
    AssetId?: string;

    /**
     * @type {Array<string>}
     * @memberof ExportAssetCenterDevsRequest
     */
    AssetIds?: Array<string>;

    /**
     * @type {string}
     * @memberof ExportAssetCenterDevsRequest
     */
    AssetName?: string;

    /**
     * @type {string}
     * @memberof ExportAssetCenterDevsRequest
     */
    IP?: string;

    /**
     * @type {boolean}
     * @memberof ExportAssetCenterDevsRequest
     */
    IsAll?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ExportAssetCenterDevsRequest
     */
    Platforms?: Array<string>;

    /**
     * @type {string}
     * @memberof ExportAssetCenterDevsRequest
     */
    ProtectStatus?: string;

    /**
     * @type {Array<string>}
     * @memberof ExportAssetCenterDevsRequest
     */
    Regions?: Array<string>;

    /**
     * @type {RiskForExportAssetCenterDevsInput}
     * @memberof ExportAssetCenterDevsRequest
     */
    Risk?: RiskForExportAssetCenterDevsInput;

    /**
     * @type {boolean}
     * @memberof ExportAssetCenterDevsRequest
     */
    SecurityEnhancement?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ExportAssetCenterDevsRequest
     */
    Status?: Array<string>;
}
