/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionsForExportAlarmListDataForRaspInput } from './conditions-for-export-alarm-list-data-for-rasp-input';
 /**
 * 
 *
 * @export
 * @interface ExportAlarmListDataForRaspRequest
 */
export interface ExportAlarmListDataForRaspRequest {

    /**
     * @type {Array<string>}
     * @memberof ExportAlarmListDataForRaspRequest
     */
    AlarmIDList?: Array<string>;

    /**
     * @type {ConditionsForExportAlarmListDataForRaspInput}
     * @memberof ExportAlarmListDataForRaspRequest
     */
    Conditions?: ConditionsForExportAlarmListDataForRaspInput;
}
