/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RiskForListRegistryImagesInput } from './risk-for-list-registry-images-input';
 /**
 * 
 *
 * @export
 * @interface FilterForListRegistryImagesInput
 */
export interface FilterForListRegistryImagesInput {

    /**
     * @type {string}
     * @memberof FilterForListRegistryImagesInput
     */
    ImageID?: string;

    /**
     * @type {boolean}
     * @memberof FilterForListRegistryImagesInput
     */
    LatestFlag?: boolean;

    /**
     * @type {string}
     * @memberof FilterForListRegistryImagesInput
     */
    Namespace?: string;

    /**
     * @type {number}
     * @memberof FilterForListRegistryImagesInput
     */
    PushTimeFrom?: number;

    /**
     * @type {number}
     * @memberof FilterForListRegistryImagesInput
     */
    PushTimeTo?: number;

    /**
     * @type {string}
     * @memberof FilterForListRegistryImagesInput
     */
    RegistryName?: string;

    /**
     * @type {string}
     * @memberof FilterForListRegistryImagesInput
     */
    Repo?: string;

    /**
     * @type {RiskForListRegistryImagesInput}
     * @memberof FilterForListRegistryImagesInput
     */
    Risk?: RiskForListRegistryImagesInput;

    /**
     * @type {boolean}
     * @memberof FilterForListRegistryImagesInput
     */
    RiskFlag?: boolean;

    /**
     * @type {Array<string>}
     * @memberof FilterForListRegistryImagesInput
     */
    ScanStatus?: Array<string>;

    /**
     * @type {number}
     * @memberof FilterForListRegistryImagesInput
     */
    ScanTimeFrom?: number;

    /**
     * @type {number}
     * @memberof FilterForListRegistryImagesInput
     */
    ScanTimeTo?: number;

    /**
     * @type {string}
     * @memberof FilterForListRegistryImagesInput
     */
    Tag?: string;
}
