/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForGetFingerprintAppGroupOutput } from './data-for-get-fingerprint-app-group-output';
 /**
 * 
 *
 * @export
 * @interface GetFingerprintAppGroupResponse
 */
export interface GetFingerprintAppGroupResponse {

    /**
     * @type {Array<DataForGetFingerprintAppGroupOutput>}
     * @memberof GetFingerprintAppGroupResponse
     */
    Data?: Array<DataForGetFingerprintAppGroupOutput>;
}
