/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PortForGetDevDetailOutput } from './port-for-get-dev-detail-output';
import { StorageForGetDevDetailOutput } from './storage-for-get-dev-detail-output';
import { VolumeForGetDevDetailOutput } from './volume-for-get-dev-detail-output';
 /**
 * 
 *
 * @export
 * @interface GetDevDetailResponse
 */
export interface GetDevDetailResponse {

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    AccountId?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    AssetId?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    AssetName?: string;

    /**
     * @type {number}
     * @memberof GetDevDetailResponse
     */
    CreateTime?: number;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    FlavorId?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    ImageID?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    Platform?: string;

    /**
     * @type {Array<PortForGetDevDetailOutput>}
     * @memberof GetDevDetailResponse
     */
    Ports?: Array<PortForGetDevDetailOutput>;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    PrivateIP?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    ProtectStatus?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    PublicIP?: string;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    Region?: string;

    /**
     * @type {boolean}
     * @memberof GetDevDetailResponse
     */
    SecurityEnhancement?: boolean;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    Status?: string;

    /**
     * @type {Array<StorageForGetDevDetailOutput>}
     * @memberof GetDevDetailResponse
     */
    Storages?: Array<StorageForGetDevDetailOutput>;

    /**
     * @type {VolumeForGetDevDetailOutput}
     * @memberof GetDevDetailResponse
     */
    Volume?: VolumeForGetDevDetailOutput;

    /**
     * @type {string}
     * @memberof GetDevDetailResponse
     */
    VpcId?: string;
}
