/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetGroupCheckStatusResponse
 */
export interface GetGroupCheckStatusResponse {

    /**
     * @type {number}
     * @memberof GetGroupCheckStatusResponse
     */
    LastCheckTime?: number;

    /**
     * @type {number}
     * @memberof GetGroupCheckStatusResponse
     */
    Progress?: number;

    /**
     * @type {string}
     * @memberof GetGroupCheckStatusResponse
     */
    Status?: string;
}
