/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DetailForInstallAgentClientOutput } from './detail-for-install-agent-client-output';
 /**
 * 
 *
 * @export
 * @interface InstallAgentClientResponse
 */
export interface InstallAgentClientResponse {

    /**
     * @type {Array<DetailForInstallAgentClientOutput>}
     * @memberof InstallAgentClientResponse
     */
    Detail?: Array<DetailForInstallAgentClientOutput>;

    /**
     * @type {number}
     * @memberof InstallAgentClientResponse
     */
    FailureCount?: number;

    /**
     * @type {number}
     * @memberof InstallAgentClientResponse
     */
    SuccessCount?: number;
}
