/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForListAlarmArchiveRecordsOutput } from './data-for-list-alarm-archive-records-output';
 /**
 * 
 *
 * @export
 * @interface ListAlarmArchiveRecordsResponse
 */
export interface ListAlarmArchiveRecordsResponse {

    /**
     * @type {Array<DataForListAlarmArchiveRecordsOutput>}
     * @memberof ListAlarmArchiveRecordsResponse
     */
    Data?: Array<DataForListAlarmArchiveRecordsOutput>;

    /**
     * @type {number}
     * @memberof ListAlarmArchiveRecordsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListAlarmArchiveRecordsResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListAlarmArchiveRecordsResponse
     */
    TotalCount?: number;
}
