/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForListMultiLevelAssetHostsOutput } from './data-for-list-multi-level-asset-hosts-output';
 /**
 * 
 *
 * @export
 * @interface ListMultiLevelAssetHostsResponse
 */
export interface ListMultiLevelAssetHostsResponse {

    /**
     * @type {Array<DataForListMultiLevelAssetHostsOutput>}
     * @memberof ListMultiLevelAssetHostsResponse
     */
    Data?: Array<DataForListMultiLevelAssetHostsOutput>;

    /**
     * @type {number}
     * @memberof ListMultiLevelAssetHostsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListMultiLevelAssetHostsResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListMultiLevelAssetHostsResponse
     */
    TotalCount?: number;
}
