/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForListDevBasicInfosOutput } from './data-for-list-dev-basic-infos-output';
 /**
 * 
 *
 * @export
 * @interface ListDevBasicInfosResponse
 */
export interface ListDevBasicInfosResponse {

    /**
     * @type {Array<DataForListDevBasicInfosOutput>}
     * @memberof ListDevBasicInfosResponse
     */
    Data?: Array<DataForListDevBasicInfosOutput>;

    /**
     * @type {number}
     * @memberof ListDevBasicInfosResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListDevBasicInfosResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListDevBasicInfosResponse
     */
    TotalCount?: number;
}
