/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionsForListWhiteListsInput } from './conditions-for-list-white-lists-input';
 /**
 * 
 *
 * @export
 * @interface ListWhiteListsRequest
 */
export interface ListWhiteListsRequest {

    /**
     * @type {ConditionsForListWhiteListsInput}
     * @memberof ListWhiteListsRequest
     */
    Conditions?: ConditionsForListWhiteListsInput;

    /**
     * @type {number}
     * @memberof ListWhiteListsRequest
     */
    PageNumber: number;

    /**
     * @type {number}
     * @memberof ListWhiteListsRequest
     */
    PageSize: number;

    /**
     * @type {string}
     * @memberof ListWhiteListsRequest
     */
    SortBy?: string;

    /**
     * @type {string}
     * @memberof ListWhiteListsRequest
     */
    SortOrder?: string;

    /**
     * @type {string}
     * @memberof ListWhiteListsRequest
     */
    Type: string;
}
