/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForListRegistryNamespacesOutput } from './data-for-list-registry-namespaces-output';
 /**
 * 
 *
 * @export
 * @interface ListRegistryNamespacesResponse
 */
export interface ListRegistryNamespacesResponse {

    /**
     * @type {Array<DataForListRegistryNamespacesOutput>}
     * @memberof ListRegistryNamespacesResponse
     */
    Data?: Array<DataForListRegistryNamespacesOutput>;

    /**
     * @type {number}
     * @memberof ListRegistryNamespacesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListRegistryNamespacesResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListRegistryNamespacesResponse
     */
    TotalCount?: number;
}
