/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PlusAlarmInfo49ForGetAlarmBySmithKeyOutput
 */
export interface PlusAlarmInfo49ForGetAlarmBySmithKeyOutput {

    /**
     * @type {string}
     * @memberof PlusAlarmInfo49ForGetAlarmBySmithKeyOutput
     */
    PidTree?: string;

    /**
     * @type {string}
     * @memberof PlusAlarmInfo49ForGetAlarmBySmithKeyOutput
     */
    Sip?: string;

    /**
     * @type {string}
     * @memberof PlusAlarmInfo49ForGetAlarmBySmithKeyOutput
     */
    Sport?: string;
}
