/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RangeForEditRaspConfigInput
 */
export interface RangeForEditRaspConfigInput {

    /**
     * @type {Array<string>}
     * @memberof RangeForEditRaspConfigInput
     */
    AgentIDList?: Array<string>;

    /**
     * @type {boolean}
     * @memberof RangeForEditRaspConfigInput
     */
    AllHost?: boolean;

    /**
     * @type {Array<string>}
     * @memberof RangeForEditRaspConfigInput
     */
    LeafGroupIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof RangeForEditRaspConfigInput
     */
    SingleGroupPath?: string;

    /**
     * @type {string}
     * @memberof RangeForEditRaspConfigInput
     */
    SingleHostname?: string;
}
