/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ComplDistrForGetRegistryImageDetailOutput } from './compl-distr-for-get-registry-image-detail-output';
import { SenfileDistrForGetRegistryImageDetailOutput } from './senfile-distr-for-get-registry-image-detail-output';
import { VulnDistrForGetRegistryImageDetailOutput } from './vuln-distr-for-get-registry-image-detail-output';
 /**
 * 
 *
 * @export
 * @interface ScanForGetRegistryImageDetailOutput
 */
export interface ScanForGetRegistryImageDetailOutput {

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    ComplCnt?: number;

    /**
     * @type {ComplDistrForGetRegistryImageDetailOutput}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    ComplDistr?: ComplDistrForGetRegistryImageDetailOutput;

    /**
     * @type {string}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    ErrCode?: string;

    /**
     * @type {string}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    ErrMsg?: string;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    LayerCnt?: number;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    PkgCnt?: number;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    Risk?: number;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    SenfileCnt?: number;

    /**
     * @type {SenfileDistrForGetRegistryImageDetailOutput}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    SenfileDistr?: SenfileDistrForGetRegistryImageDetailOutput;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    VirusCnt?: number;

    /**
     * @type {number}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    VulnCnt?: number;

    /**
     * @type {VulnDistrForGetRegistryImageDetailOutput}
     * @memberof ScanForGetRegistryImageDetailOutput
     */
    VulnDistr?: VulnDistrForGetRegistryImageDetailOutput;
}
