/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LoginLocationForUpdateLoginConfigInput } from './login-location-for-update-login-config-input';
 /**
 * 
 *
 * @export
 * @interface UpdateLoginConfigRequest
 */
export interface UpdateLoginConfigRequest {

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    AgentIDList?: Array<string>;

    /**
     * @type {string}
     * @memberof UpdateLoginConfigRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof UpdateLoginConfigRequest
     */
    ID: string;

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    IPList?: Array<string>;

    /**
     * @type {boolean}
     * @memberof UpdateLoginConfigRequest
     */
    IfAllHost?: boolean;

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    LeafGroupIDs?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    LegalUser?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    LoginConfigRules?: Array<string>;

    /**
     * @type {Array<LoginLocationForUpdateLoginConfigInput>}
     * @memberof UpdateLoginConfigRequest
     */
    LoginLocations?: Array<LoginLocationForUpdateLoginConfigInput>;

    /**
     * @type {Array<string>}
     * @memberof UpdateLoginConfigRequest
     */
    TimeIntervals?: Array<string>;

    /**
     * @type {string}
     * @memberof UpdateLoginConfigRequest
     */
    TopGroupID?: string;
}
