/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VolumeForGetDevDetailOutput
 */
export interface VolumeForGetDevDetailOutput {

    /**
     * @type {string}
     * @memberof VolumeForGetDevDetailOutput
     */
    Id?: string;

    /**
     * @type {number}
     * @memberof VolumeForGetDevDetailOutput
     */
    Size?: number;

    /**
     * @type {string}
     * @memberof VolumeForGetDevDetailOutput
     */
    State?: string;

    /**
     * @type {string}
     * @memberof VolumeForGetDevDetailOutput
     */
    StateHint?: string;

    /**
     * @type {string}
     * @memberof VolumeForGetDevDetailOutput
     */
    Type?: string;

    /**
     * @type {string}
     * @memberof VolumeForGetDevDetailOutput
     */
    Used?: string;
}
