/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor20251201
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateForCreateNotificationTemplateInput } from './template-for-create-notification-template-input';
 /**
 * 
 *
 * @export
 * @interface CreateNotificationTemplateRequest
 */
export interface CreateNotificationTemplateRequest {

    /**
     * @type {string}
     * @memberof CreateNotificationTemplateRequest
     */
    Channel: string;

    /**
     * @type {string}
     * @memberof CreateNotificationTemplateRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof CreateNotificationTemplateRequest
     */
    Name: string;

    /**
     * @type {Array<TemplateForCreateNotificationTemplateInput>}
     * @memberof CreateNotificationTemplateRequest
     */
    Templates?: Array<TemplateForCreateNotificationTemplateInput>;
}
