/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor20251201
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssociatedFilterForListDutySchedulesInput } from './associated-filter-for-list-duty-schedules-input';
 /**
 * 
 *
 * @export
 * @interface ListDutySchedulesRequest
 */
export interface ListDutySchedulesRequest {

    /**
     * @type {boolean}
     * @memberof ListDutySchedulesRequest
     */
    Asc?: boolean;

    /**
     * @type {Array<AssociatedFilterForListDutySchedulesInput>}
     * @memberof ListDutySchedulesRequest
     */
    AssociatedFilters?: Array<AssociatedFilterForListDutySchedulesInput>;

    /**
     * @type {Array<string>}
     * @memberof ListDutySchedulesRequest
     */
    IDs?: Array<string>;

    /**
     * @type {string}
     * @memberof ListDutySchedulesRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof ListDutySchedulesRequest
     */
    OrderBy?: ListDutySchedulesRequestOrderByEnum;

    /**
     * @type {number}
     * @memberof ListDutySchedulesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListDutySchedulesRequest
     */
    PageSize?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ListDutySchedulesRequestOrderByEnum {
    UpdateTime = 'UpdateTime',
    UpdatedAt = 'UpdatedAt',
    CreateTime = 'CreateTime',
    CreatedAt = 'CreatedAt'
}

