/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor20251201
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CloudEventForUpdateSilencePolicyInput } from './cloud-event-for-update-silence-policy-input';
import { CloudMonitorForUpdateSilencePolicyInput } from './cloud-monitor-for-update-silence-policy-input';
import { CommonForUpdateSilencePolicyInput } from './common-for-update-silence-policy-input';
import { VMPForUpdateSilencePolicyInput } from './vmpfor-update-silence-policy-input';
 /**
 * 
 *
 * @export
 * @interface SilenceConditionForUpdateSilencePolicyInput
 */
export interface SilenceConditionForUpdateSilencePolicyInput {

    /**
     * @type {CloudEventForUpdateSilencePolicyInput}
     * @memberof SilenceConditionForUpdateSilencePolicyInput
     */
    CloudEvent?: CloudEventForUpdateSilencePolicyInput;

    /**
     * @type {CloudMonitorForUpdateSilencePolicyInput}
     * @memberof SilenceConditionForUpdateSilencePolicyInput
     */
    CloudMonitor?: CloudMonitorForUpdateSilencePolicyInput;

    /**
     * @type {CommonForUpdateSilencePolicyInput}
     * @memberof SilenceConditionForUpdateSilencePolicyInput
     */
    Common?: CommonForUpdateSilencePolicyInput;

    /**
     * @type {string}
     * @memberof SilenceConditionForUpdateSilencePolicyInput
     */
    MonitorType?: string;

    /**
     * @type {VMPForUpdateSilencePolicyInput}
     * @memberof SilenceConditionForUpdateSilencePolicyInput
     */
    VMP?: VMPForUpdateSilencePolicyInput;
}
