/* tslint:disable */
/* eslint-disable */
/**
 * cloudcontrol
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateResourceResponse
 */
export interface CreateResourceResponse {

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    ErrorCode?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    EventTime?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    Identifier?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    Operation?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    OperationStatus?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    ResourceModel?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    StatusMessage?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    TaskID?: string;

    /**
     * @type {string}
     * @memberof CreateResourceResponse
     */
    TypeName?: string;
}
