/* tslint:disable */
/* eslint-disable */
/**
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProjectListForGetFilterInfoForCostAnalysisOutput
 */
export interface ProjectListForGetFilterInfoForCostAnalysisOutput {

    /**
     * @type {string}
     * @memberof ProjectListForGetFilterInfoForCostAnalysisOutput
     */
    Project?: string;

    /**
     * @type {string}
     * @memberof ProjectListForGetFilterInfoForCostAnalysisOutput
     */
    ProjectDisplayName?: string;
}
