/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthorizedNetworkForCreateBranchInput
 */
export interface AuthorizedNetworkForCreateBranchInput {

    /**
     * @type {string}
     * @memberof AuthorizedNetworkForCreateBranchInput
     */
    DisplayName?: string;

    /**
     * @type {string}
     * @memberof AuthorizedNetworkForCreateBranchInput
     */
    EndIpAddress?: string;

    /**
     * @type {string}
     * @memberof AuthorizedNetworkForCreateBranchInput
     */
    StartIpAddress?: string;
}
