/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AzureBlobForListExportTasksOutput
 */
export interface AzureBlobForListExportTasksOutput {

    /**
     * @type {string}
     * @memberof AzureBlobForListExportTasksOutput
     */
    AuthType?: AzureBlobForListExportTasksOutputAuthTypeEnum;

    /**
     * @type {string}
     * @memberof AzureBlobForListExportTasksOutput
     */
    SasToken?: string;

    /**
     * @type {string}
     * @memberof AzureBlobForListExportTasksOutput
     */
    Uri?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum AzureBlobForListExportTasksOutputAuthTypeEnum {
    ROLEARN = 'ROLE_ARN',
    ACCESSKEY = 'ACCESS_KEY',
    SERVICEACCOUNTKEY = 'SERVICE_ACCOUNT_KEY',
    SASTOKEN = 'SAS_TOKEN'
}

