/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BackupForListBackupsOutput
 */
export interface BackupForListBackupsOutput {

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    BackupId?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    BackupTime?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    ClusterId?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    ExpireTime?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof BackupForListBackupsOutput
     */
    State?: BackupForListBackupsOutputStateEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BackupForListBackupsOutputStateEnum {
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED'
}

