/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ImportOptionsForGetImportTaskDetailsOutput } from './import-options-for-get-import-task-details-output';
import { SourceForGetImportTaskDetailsOutput } from './source-for-get-import-task-details-output';
 /**
 * 
 *
 * @export
 * @interface CreationDetailsForGetImportTaskDetailsOutput
 */
export interface CreationDetailsForGetImportTaskDetailsOutput {

    /**
     * @type {ImportOptionsForGetImportTaskDetailsOutput}
     * @memberof CreationDetailsForGetImportTaskDetailsOutput
     */
    ImportOptions?: ImportOptionsForGetImportTaskDetailsOutput;

    /**
     * @type {SourceForGetImportTaskDetailsOutput}
     * @memberof CreationDetailsForGetImportTaskDetailsOutput
     */
    Source?: SourceForGetImportTaskDetailsOutput;
}
