/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CsvFormatForCreateImportTaskOutput
 */
export interface CsvFormatForCreateImportTaskOutput {

    /**
     * @type {boolean}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    BackslashEscape?: boolean;

    /**
     * @type {string}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    Delimiter?: string;

    /**
     * @type {boolean}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    Header?: boolean;

    /**
     * @type {boolean}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    NotNull?: boolean;

    /**
     * @type {string}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    NullValue?: string;

    /**
     * @type {string}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    Separator?: string;

    /**
     * @type {boolean}
     * @memberof CsvFormatForCreateImportTaskOutput
     */
    TrimLastSeparator?: boolean;
}
