/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PrivateEndpointForGetClusterDetailsOutput } from './private-endpoint-for-get-cluster-details-output';
import { PublicEndpointForGetClusterDetailsOutput } from './public-endpoint-for-get-cluster-details-output';
 /**
 * 
 *
 * @export
 * @interface EndpointsForGetClusterDetailsOutput
 */
export interface EndpointsForGetClusterDetailsOutput {

    /**
     * @type {PrivateEndpointForGetClusterDetailsOutput}
     * @memberof EndpointsForGetClusterDetailsOutput
     */
    PrivateEndpoint?: PrivateEndpointForGetClusterDetailsOutput;

    /**
     * @type {PublicEndpointForGetClusterDetailsOutput}
     * @memberof EndpointsForGetClusterDetailsOutput
     */
    PublicEndpoint?: PublicEndpointForGetClusterDetailsOutput;
}
