/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExportOptionsForDeleteExportTaskOutput } from './export-options-for-delete-export-task-output';
import { TargetForDeleteExportTaskOutput } from './target-for-delete-export-task-output';
 /**
 * 
 *
 * @export
 * @interface ExportForDeleteExportTaskOutput
 */
export interface ExportForDeleteExportTaskOutput {

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    ClusterId?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    CompleteTime?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    DisplayName?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    ExpireTime?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    ExportId?: string;

    /**
     * @type {ExportOptionsForDeleteExportTaskOutput}
     * @memberof ExportForDeleteExportTaskOutput
     */
    ExportOptions?: ExportOptionsForDeleteExportTaskOutput;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    Reason?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    SnapshotTime?: string;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    State?: ExportForDeleteExportTaskOutputStateEnum;

    /**
     * @type {TargetForDeleteExportTaskOutput}
     * @memberof ExportForDeleteExportTaskOutput
     */
    Target?: TargetForDeleteExportTaskOutput;

    /**
     * @type {string}
     * @memberof ExportForDeleteExportTaskOutput
     */
    UpdateTime?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ExportForDeleteExportTaskOutputStateEnum {
    RUNNING = 'RUNNING',
    SUCCEEDED = 'SUCCEEDED',
    FAILED = 'FAILED',
    CANCELED = 'CANCELED',
    DELETED = 'DELETED',
    EXPIRED = 'EXPIRED'
}

