/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TableForCreateExportTaskOutput } from './table-for-create-export-task-output';
 /**
 * 
 *
 * @export
 * @interface FilterForCreateExportTaskOutput
 */
export interface FilterForCreateExportTaskOutput {

    /**
     * @type {string}
     * @memberof FilterForCreateExportTaskOutput
     */
    Sql?: string;

    /**
     * @type {TableForCreateExportTaskOutput}
     * @memberof FilterForCreateExportTaskOutput
     */
    Table?: TableForCreateExportTaskOutput;
}
