/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccessKeyForCreateImportTaskInput } from './access-key-for-create-import-task-input';
 /**
 * 
 *
 * @export
 * @interface OssForCreateImportTaskInput
 */
export interface OssForCreateImportTaskInput {

    /**
     * @type {AccessKeyForCreateImportTaskInput}
     * @memberof OssForCreateImportTaskInput
     */
    AccessKey?: AccessKeyForCreateImportTaskInput;

    /**
     * @type {string}
     * @memberof OssForCreateImportTaskInput
     */
    AuthType?: OssForCreateImportTaskInputAuthTypeEnum;

    /**
     * @type {string}
     * @memberof OssForCreateImportTaskInput
     */
    Uri?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum OssForCreateImportTaskInputAuthTypeEnum {
    ROLEARN = 'ROLE_ARN',
    ACCESSKEY = 'ACCESS_KEY',
    SERVICEACCOUNTKEY = 'SERVICE_ACCOUNT_KEY',
    SASTOKEN = 'SAS_TOKEN'
}

