/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccessKeyForCreateExportTaskInput } from './access-key-for-create-export-task-input';
 /**
 * 
 *
 * @export
 * @interface OssForCreateExportTaskInput
 */
export interface OssForCreateExportTaskInput {

    /**
     * @type {AccessKeyForCreateExportTaskInput}
     * @memberof OssForCreateExportTaskInput
     */
    AccessKey?: AccessKeyForCreateExportTaskInput;

    /**
     * @type {string}
     * @memberof OssForCreateExportTaskInput
     */
    AuthType?: OssForCreateExportTaskInputAuthTypeEnum;

    /**
     * @type {string}
     * @memberof OssForCreateExportTaskInput
     */
    Uri?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum OssForCreateExportTaskInputAuthTypeEnum {
    ROLEARN = 'ROLE_ARN',
    ACCESSKEY = 'ACCESS_KEY',
    SERVICEACCOUNTKEY = 'SERVICE_ACCOUNT_KEY',
    SASTOKEN = 'SAS_TOKEN'
}

