/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccessKeyForListImportTasksOutput } from './access-key-for-list-import-tasks-output';
 /**
 * 
 *
 * @export
 * @interface S3ForListImportTasksOutput
 */
export interface S3ForListImportTasksOutput {

    /**
     * @type {AccessKeyForListImportTasksOutput}
     * @memberof S3ForListImportTasksOutput
     */
    AccessKey?: AccessKeyForListImportTasksOutput;

    /**
     * @type {string}
     * @memberof S3ForListImportTasksOutput
     */
    AuthType?: S3ForListImportTasksOutputAuthTypeEnum;

    /**
     * @type {string}
     * @memberof S3ForListImportTasksOutput
     */
    RoleArn?: string;

    /**
     * @type {string}
     * @memberof S3ForListImportTasksOutput
     */
    Uri?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum S3ForListImportTasksOutputAuthTypeEnum {
    ROLEARN = 'ROLE_ARN',
    ACCESSKEY = 'ACCESS_KEY',
    SERVICEACCOUNTKEY = 'SERVICE_ACCOUNT_KEY',
    SASTOKEN = 'SAS_TOKEN'
}

