/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LocalForCreateImportTaskInput } from './local-for-create-import-task-input';
import { TargetTableInfoForCreateImportTaskInput } from './target-table-info-for-create-import-task-input';
import { TosForCreateImportTaskInput } from './tos-for-create-import-task-input';
 /**
 * 
 *
 * @export
 * @interface SourceForCreateImportTaskInput
 */
export interface SourceForCreateImportTaskInput {

    /**
     * @type {LocalForCreateImportTaskInput}
     * @memberof SourceForCreateImportTaskInput
     */
    Local?: LocalForCreateImportTaskInput;

    /**
     * @type {Array<TargetTableInfoForCreateImportTaskInput>}
     * @memberof SourceForCreateImportTaskInput
     */
    TargetTableInfos?: Array<TargetTableInfoForCreateImportTaskInput>;

    /**
     * @type {TosForCreateImportTaskInput}
     * @memberof SourceForCreateImportTaskInput
     */
    Tos?: TosForCreateImportTaskInput;

    /**
     * @type {string}
     * @memberof SourceForCreateImportTaskInput
     */
    Type?: SourceForCreateImportTaskInputTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SourceForCreateImportTaskInputTypeEnum {
    _6 = '6',
    _7 = '7'
}

