/* tslint:disable */
/* eslint-disable */
/**
 * tidb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ZoneForRestoreClusterInput
 */
export interface ZoneForRestoreClusterInput {

    /**
     * @type {string}
     * @memberof ZoneForRestoreClusterInput
     */
    SubnetId?: string;

    /**
     * @type {string}
     * @memberof ZoneForRestoreClusterInput
     */
    ZoneId?: string;
}
