/* tslint:disable */
/* eslint-disable */
/**
 * emr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListApplicationsRequest
 */
export interface ListApplicationsRequest {

    /**
     * @type {Array<string>}
     * @memberof ListApplicationsRequest
     */
    ApplicationNames?: Array<string>;

    /**
     * @type {string}
     * @memberof ListApplicationsRequest
     */
    ClusterId: string;

    /**
     * @type {number}
     * @memberof ListApplicationsRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof ListApplicationsRequest
     */
    NextToken?: string;
}
