/* tslint:disable */
/* eslint-disable */
/**
 * emr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResultDataForScaleUpNodeGroupDiskOutput } from './result-data-for-scale-up-node-group-disk-output';
 /**
 * 
 *
 * @export
 * @interface ScaleUpNodeGroupDiskResponse
 */
export interface ScaleUpNodeGroupDiskResponse {

    /**
     * @type {string}
     * @memberof ScaleUpNodeGroupDiskResponse
     */
    ClusterId?: string;

    /**
     * @type {string}
     * @memberof ScaleUpNodeGroupDiskResponse
     */
    OperationId?: string;

    /**
     * @type {ResultDataForScaleUpNodeGroupDiskOutput}
     * @memberof ScaleUpNodeGroupDiskResponse
     */
    ResultData?: ResultDataForScaleUpNodeGroupDiskOutput;
}
