/* tslint:disable */
/* eslint-disable */
/**
 * emr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ScaleOutNodeGroupRequest
 */
export interface ScaleOutNodeGroupRequest {

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ClusterId: string;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ElasticScheduledInstanceAutoReleaseAt?: string;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ElasticScheduledInstanceDeliveryType?: ScaleOutNodeGroupRequestElasticScheduledInstanceDeliveryTypeEnum;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ElasticScheduledInstanceEndDeliveryAt?: string;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ElasticScheduledInstanceStartDeliveryAt?: string;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    ElasticScheduledInstanceType?: ScaleOutNodeGroupRequestElasticScheduledInstanceTypeEnum;

    /**
     * @type {string}
     * @memberof ScaleOutNodeGroupRequest
     */
    NodeGroupId: string;

    /**
     * @type {number}
     * @memberof ScaleOutNodeGroupRequest
     */
    ScaleOutNodeCount: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ScaleOutNodeGroupRequestElasticScheduledInstanceDeliveryTypeEnum {
    Reserve = 'Reserve',
    Immediate = 'Immediate'
}
/**
 * @export
 * @enum {string}
 */
export enum ScaleOutNodeGroupRequestElasticScheduledInstanceTypeEnum {
    Esi = 'Esi',
    Segmented = 'Segmented'
}

