/* tslint:disable */
/* eslint-disable */
/**
 * emr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateClusterAttributeResponse
 */
export interface UpdateClusterAttributeResponse {

    /**
     * @type {string}
     * @memberof UpdateClusterAttributeResponse
     */
    ClusterId?: string;

    /**
     * @type {string}
     * @memberof UpdateClusterAttributeResponse
     */
    OperationId?: string;

    /**
     * @type {string}
     * @memberof UpdateClusterAttributeResponse
     */
    ResultData?: string;
}
