/* tslint:disable */
/* eslint-disable */
/**
 * emr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResultDataForUpdateNodeGroupEcsSpecOutput } from './result-data-for-update-node-group-ecs-spec-output';
 /**
 * 
 *
 * @export
 * @interface UpdateNodeGroupEcsSpecResponse
 */
export interface UpdateNodeGroupEcsSpecResponse {

    /**
     * @type {string}
     * @memberof UpdateNodeGroupEcsSpecResponse
     */
    ClusterId?: string;

    /**
     * @type {string}
     * @memberof UpdateNodeGroupEcsSpecResponse
     */
    OperationId?: string;

    /**
     * @type {ResultDataForUpdateNodeGroupEcsSpecOutput}
     * @memberof UpdateNodeGroupEcsSpecResponse
     */
    ResultData?: ResultDataForUpdateNodeGroupEcsSpecOutput;
}
