/* tslint:disable */
/* eslint-disable */
/**
 * cbr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExternalAccountsForListExternalAccountsOutput } from './external-accounts-for-list-external-accounts-output';
 /**
 * 
 *
 * @export
 * @interface ListExternalAccountsResponse
 */
export interface ListExternalAccountsResponse {

    /**
     * @type {ExternalAccountsForListExternalAccountsOutput}
     * @memberof ListExternalAccountsResponse
     */
    ExternalAccounts?: ExternalAccountsForListExternalAccountsOutput;

    /**
     * @type {number}
     * @memberof ListExternalAccountsResponse
     */
    Total?: number;
}
