/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertConditionForUpdateRuleInput } from './convert-condition-for-update-rule-input';
 /**
 * 
 *
 * @export
 * @interface LevelConditionForUpdateRuleInput
 */
export interface LevelConditionForUpdateRuleInput {

    /**
     * @type {Array<ConvertConditionForUpdateRuleInput>}
     * @memberof LevelConditionForUpdateRuleInput
     */
    Conditions?: Array<ConvertConditionForUpdateRuleInput>;

    /**
     * @type {string}
     * @memberof LevelConditionForUpdateRuleInput
     */
    Level?: string;
}
