/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MetricConditionForListAlertOutput
 */
export interface MetricConditionForListAlertOutput {

    /**
     * @type {string}
     * @memberof MetricConditionForListAlertOutput
     */
    Condition?: string;

    /**
     * @type {string}
     * @memberof MetricConditionForListAlertOutput
     */
    CurrentValue?: string;

    /**
     * @type {string}
     * @memberof MetricConditionForListAlertOutput
     */
    Metric?: string;

    /**
     * @type {string}
     * @memberof MetricConditionForListAlertOutput
     */
    TriggerCondition?: string;
}
