/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInput
 */
export interface BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInput {

    /**
     * @type {string}
     * @memberof BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInput
     */
    bandwidth_peak_limit?: string;

    /**
     * @type {string}
     * @memberof BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInput
     */
    isp?: BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInputIspEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BandwidthPeakLimitIspConfigForSetInstancesBandwidthPeakInputIspEnum {
    CMCC = 'CMCC',
    CTCC = 'CTCC',
    CUCC = 'CUCC'
}

