/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BillingForListInstancesOutput
 */
export interface BillingForListInstancesOutput {

    /**
     * @type {string}
     * @memberof BillingForListInstancesOutput
     */
    bandwidth_billing_method?: BillingForListInstancesOutputBandwidthBillingMethodEnum;

    /**
     * @type {string}
     * @memberof BillingForListInstancesOutput
     */
    computing_billing_method?: BillingForListInstancesOutputComputingBillingMethodEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BillingForListInstancesOutputBandwidthBillingMethodEnum {
    MonthlyP95 = 'MonthlyP95',
    DailyPeak = 'DailyPeak'
}
/**
 * @export
 * @enum {string}
 */
export enum BillingForListInstancesOutputComputingBillingMethodEnum {
    MonthlyPeak = 'MonthlyPeak',
    DailyPeak = 'DailyPeak',
    PrePaid = 'PrePaid'
}

