/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateCloudServerResponse
 */
export interface CreateCloudServerResponse {

    /**
     * @type {string}
     * @memberof CreateCloudServerResponse
     */
    cloud_server_identity?: string;

    /**
     * @type {string}
     * @memberof CreateCloudServerResponse
     */
    pre_paid_url?: string;
}
