/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IpNumMapForCreateLNIInstanceInput } from './ip-num-map-for-create-lniinstance-input';
 /**
 * 
 *
 * @export
 * @interface CreateLNIInstanceRequest
 */
export interface CreateLNIInstanceRequest {

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    bandwidth_billing_method?: CreateLNIInstanceRequestBandwidthBillingMethodEnum;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    cluster_name: string;

    /**
     * @type {boolean}
     * @memberof CreateLNIInstanceRequest
     */
    delete_on_release?: boolean;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    desc?: string;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    ip_allocation: CreateLNIInstanceRequestIpAllocationEnum;

    /**
     * @type {number}
     * @memberof CreateLNIInstanceRequest
     */
    ip_bandwidth_peak?: number;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    ip_billing_method?: CreateLNIInstanceRequestIpBillingMethodEnum;

    /**
     * @type {IpNumMapForCreateLNIInstanceInput}
     * @memberof CreateLNIInstanceRequest
     */
    ip_num_map?: IpNumMapForCreateLNIInstanceInput;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    ip_type: CreateLNIInstanceRequestIpTypeEnum;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    ip_version: CreateLNIInstanceRequestIpVersionEnum;

    /**
     * @type {boolean}
     * @memberof CreateLNIInstanceRequest
     */
    is_enhanced?: boolean;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    name?: string;

    /**
     * @type {number}
     * @memberof CreateLNIInstanceRequest
     */
    num: number;

    /**
     * @type {string}
     * @memberof CreateLNIInstanceRequest
     */
    payment_method?: CreateLNIInstanceRequestPaymentMethodEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestBandwidthBillingMethodEnum {
    MonthlyP95DailyPeakHourUsed = 'MonthlyP95，DailyPeak，HourUsed'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestIpAllocationEnum {
    System = 'system'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestIpBillingMethodEnum {
    DailyPeak = 'DailyPeak'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestIpTypeEnum {
    Internalexternal = 'internal，external'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestIpVersionEnum {
    Ipv4ipv4 = 'ipv4，ipv4',
    Ipv6 = 'ipv6'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateLNIInstanceRequestPaymentMethodEnum {
    Postpaid = 'postpaid'
}

