/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateEbsInstancesResponse
 */
export interface CreateEbsInstancesResponse {

    /**
     * @type {Array<string>}
     * @memberof CreateEbsInstancesResponse
     */
    ebs_ids?: Array<string>;
}
