/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuleForCreateSecurityGroupRulesInput } from './rule-for-create-security-group-rules-input';
 /**
 * 
 *
 * @export
 * @interface CreateSecurityGroupRulesRequest
 */
export interface CreateSecurityGroupRulesRequest {

    /**
     * @type {string}
     * @memberof CreateSecurityGroupRulesRequest
     */
    group_identity: string;

    /**
     * @type {Array<RuleForCreateSecurityGroupRulesInput>}
     * @memberof CreateSecurityGroupRulesRequest
     */
    rules?: Array<RuleForCreateSecurityGroupRulesInput>;
}
