/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SecurityGroupForDescribeSecurityGroupsOutput } from './security-group-for-describe-security-groups-output';
 /**
 * 
 *
 * @export
 * @interface DescribeSecurityGroupsResponse
 */
export interface DescribeSecurityGroupsResponse {

    /**
     * @type {Array<SecurityGroupForDescribeSecurityGroupsOutput>}
     * @memberof DescribeSecurityGroupsResponse
     */
    security_groups?: Array<SecurityGroupForDescribeSecurityGroupsOutput>;

    /**
     * @type {number}
     * @memberof DescribeSecurityGroupsResponse
     */
    total_count?: number;
}
