/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuleForDescribeSecurityGroupOutput } from './rule-for-describe-security-group-output';
 /**
 * 
 *
 * @export
 * @interface EgressRuleForDescribeSecurityGroupOutput
 */
export interface EgressRuleForDescribeSecurityGroupOutput {

    /**
     * @type {Array<RuleForDescribeSecurityGroupOutput>}
     * @memberof EgressRuleForDescribeSecurityGroupOutput
     */
    rules?: Array<RuleForDescribeSecurityGroupOutput>;

    /**
     * @type {number}
     * @memberof EgressRuleForDescribeSecurityGroupOutput
     */
    total?: number;
}
