/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuleForDescribeSecurityGroupsOutput } from './rule-for-describe-security-groups-output';
 /**
 * 
 *
 * @export
 * @interface EgressRuleForDescribeSecurityGroupsOutput
 */
export interface EgressRuleForDescribeSecurityGroupsOutput {

    /**
     * @type {Array<RuleForDescribeSecurityGroupsOutput>}
     * @memberof EgressRuleForDescribeSecurityGroupsOutput
     */
    rules?: Array<RuleForDescribeSecurityGroupsOutput>;

    /**
     * @type {number}
     * @memberof EgressRuleForDescribeSecurityGroupsOutput
     */
    total?: number;
}
