/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BillingConfigForBatchCreateEIPInstancesOutput } from './billing-config-for-batch-create-eipinstances-output';
import { BinderResourceForBatchCreateEIPInstancesOutput } from './binder-resource-for-batch-create-eipinstances-output';
import { ClusterForBatchCreateEIPInstancesOutput } from './cluster-for-batch-create-eipinstances-output';
import { TagForBatchCreateEIPInstancesOutput } from './tag-for-batch-create-eipinstances-output';
 /**
 * 
 *
 * @export
 * @interface EipForBatchCreateEIPInstancesOutput
 */
export interface EipForBatchCreateEIPInstancesOutput {

    /**
     * @type {Array<TagForBatchCreateEIPInstancesOutput>}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    Tags?: Array<TagForBatchCreateEIPInstancesOutput>;

    /**
     * @type {number}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    account_identity?: number;

    /**
     * @type {number}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    bandwidth_peak?: number;

    /**
     * @type {BillingConfigForBatchCreateEIPInstancesOutput}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    billing_config?: BillingConfigForBatchCreateEIPInstancesOutput;

    /**
     * @type {BinderResourceForBatchCreateEIPInstancesOutput}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    binder_resource?: BinderResourceForBatchCreateEIPInstancesOutput;

    /**
     * @type {ClusterForBatchCreateEIPInstancesOutput}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    cluster?: ClusterForBatchCreateEIPInstancesOutput;

    /**
     * @type {number}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    create_time?: number;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    desc?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    eip_addr?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    eip_identity?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    eip_name?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    eip_type?: EipForBatchCreateEIPInstancesOutputEipTypeEnum;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    isp?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    network_type?: EipForBatchCreateEIPInstancesOutputNetworkTypeEnum;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    project?: string;

    /**
     * @type {string}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    status?: EipForBatchCreateEIPInstancesOutputStatusEnum;

    /**
     * @type {number}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    update_time?: number;

    /**
     * @type {number}
     * @memberof EipForBatchCreateEIPInstancesOutput
     */
    user_identity?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum EipForBatchCreateEIPInstancesOutputEipTypeEnum {
    IPv4 = 'IPv4',
    IPv6 = 'IPv6'
}
/**
 * @export
 * @enum {string}
 */
export enum EipForBatchCreateEIPInstancesOutputNetworkTypeEnum {
    Public = 'public'
}
/**
 * @export
 * @enum {string}
 */
export enum EipForBatchCreateEIPInstancesOutputStatusEnum {
    Creating = 'creating',
    Unbound = 'unbound',
    Binding = 'binding',
    Bound = 'bound',
    Unbinding = 'unbinding',
    Deleting = 'deleting'
}

