/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EipRequirementListForBatchCreateEIPInstancesInput
 */
export interface EipRequirementListForBatchCreateEIPInstancesInput {

    /**
     * @type {string}
     * @memberof EipRequirementListForBatchCreateEIPInstancesInput
     */
    cluster_name?: string;

    /**
     * @type {number}
     * @memberof EipRequirementListForBatchCreateEIPInstancesInput
     */
    eip_num?: number;

    /**
     * @type {Array<string>}
     * @memberof EipRequirementListForBatchCreateEIPInstancesInput
     */
    ip_addrs?: Array<string>;

    /**
     * @type {string}
     * @memberof EipRequirementListForBatchCreateEIPInstancesInput
     */
    ip_pool_id?: string;

    /**
     * @type {string}
     * @memberof EipRequirementListForBatchCreateEIPInstancesInput
     */
    isp?: string;
}
