/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InstanceForEnableInstancesIPv6Output
 */
export interface InstanceForEnableInstancesIPv6Output {

    /**
     * @type {string}
     * @memberof InstanceForEnableInstancesIPv6Output
     */
    enable_status?: InstanceForEnableInstancesIPv6OutputEnableStatusEnum;

    /**
     * @type {string}
     * @memberof InstanceForEnableInstancesIPv6Output
     */
    instance_identity?: string;

    /**
     * @type {string}
     * @memberof InstanceForEnableInstancesIPv6Output
     */
    instance_name?: string;

    /**
     * @type {string}
     * @memberof InstanceForEnableInstancesIPv6Output
     */
    remark?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum InstanceForEnableInstancesIPv6OutputEnableStatusEnum {
    Success = 'success',
    Fail = 'fail',
    Upgrading = 'upgrading'
}

