/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AdvancedConfigurationForGetInstanceOutput } from './advanced-configuration-for-get-instance-output';
import { BillingForGetInstanceOutput } from './billing-for-get-instance-output';
import { ClusterForGetInstanceOutput } from './cluster-for-get-instance-output';
import { GpuForGetInstanceOutput } from './gpu-for-get-instance-output';
import { ImageForGetInstanceOutput } from './image-for-get-instance-output';
import { MonitorAgentForGetInstanceOutput } from './monitor-agent-for-get-instance-output';
import { NetworkForGetInstanceOutput } from './network-for-get-instance-output';
import { SecretForGetInstanceOutput } from './secret-for-get-instance-output';
import { StorageForGetInstanceOutput } from './storage-for-get-instance-output';
import { TagForGetInstanceOutput } from './tag-for-get-instance-output';
 /**
 * 
 *
 * @export
 * @interface InstanceForGetInstanceOutput
 */
export interface InstanceForGetInstanceOutput {

    /**
     * @type {Array<TagForGetInstanceOutput>}
     * @memberof InstanceForGetInstanceOutput
     */
    Tags?: Array<TagForGetInstanceOutput>;

    /**
     * @type {AdvancedConfigurationForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    advanced_configuration?: AdvancedConfigurationForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    arch?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    bare_metal_package?: string;

    /**
     * @type {BillingForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    billing?: BillingForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    classic_network_identity?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    classic_subnet_identity?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    cloud_server_identity?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    cloud_server_name?: string;

    /**
     * @type {ClusterForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    cluster?: ClusterForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    cpu?: string;

    /**
     * @type {number}
     * @memberof InstanceForGetInstanceOutput
     */
    create_time?: number;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    create_timestamp?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    creator?: string;

    /**
     * @type {number}
     * @memberof InstanceForGetInstanceOutput
     */
    end_time?: number;

    /**
     * @type {GpuForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    gpu?: GpuForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    host_name?: string;

    /**
     * @type {ImageForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    image?: ImageForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    instance_desc?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    instance_identity?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    instance_name?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    instance_uuid?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    load_type?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    mem?: string;

    /**
     * @type {MonitorAgentForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    monitor_agent?: MonitorAgentForGetInstanceOutput;

    /**
     * @type {NetworkForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    network?: NetworkForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    project?: string;

    /**
     * @type {SecretForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    secret?: SecretForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    spec?: string;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    spec_display?: string;

    /**
     * @type {number}
     * @memberof InstanceForGetInstanceOutput
     */
    start_time?: number;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    status?: InstanceForGetInstanceOutputStatusEnum;

    /**
     * @type {StorageForGetInstanceOutput}
     * @memberof InstanceForGetInstanceOutput
     */
    storage?: StorageForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    subnet_cidr?: string;

    /**
     * @type {number}
     * @memberof InstanceForGetInstanceOutput
     */
    update_time?: number;

    /**
     * @type {string}
     * @memberof InstanceForGetInstanceOutput
     */
    vpc_identity?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum InstanceForGetInstanceOutputStatusEnum {
    Opening = 'opening',
    Starting = 'starting',
    Running = 'running',
    Stopping = 'stopping',
    Stop = 'stop',
    Rebooting = 'rebooting',
    Terminating = 'terminating',
    OpenFail = 'open_fail'
}

