/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IpForGetInstanceOutput } from './ip-for-get-instance-output';
 /**
 * 
 *
 * @export
 * @interface InternalInterfaceForGetInstanceOutput
 */
export interface InternalInterfaceForGetInstanceOutput {

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    bandwidth_peak?: string;

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    ip6_addr?: string;

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    ip_addr?: string;

    /**
     * @type {Array<IpForGetInstanceOutput>}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    ips?: Array<IpForGetInstanceOutput>;

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    mac_addr?: string;

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    mask?: string;

    /**
     * @type {string}
     * @memberof InternalInterfaceForGetInstanceOutput
     */
    mask6?: string;
}
