/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EipInstanceForListEIPInstancesOutput } from './eip-instance-for-list-eipinstances-output';
 /**
 * 
 *
 * @export
 * @interface ListEIPInstancesResponse
 */
export interface ListEIPInstancesResponse {

    /**
     * @type {number}
     * @memberof ListEIPInstancesResponse
     */
    count?: number;

    /**
     * @type {Array<EipInstanceForListEIPInstancesOutput>}
     * @memberof ListEIPInstancesResponse
     */
    eip_instances?: Array<EipInstanceForListEIPInstancesOutput>;
}
