/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagFilterForListInstancesInput } from './tag-filter-for-list-instances-input';
 /**
 * 
 *
 * @export
 * @interface ListInstancesRequest
 */
export interface ListInstancesRequest {

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    CloudServerIdentities?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    ClusterNames?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    InstanceIdentities?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    InstanceNames?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    InstanceUuids?: string;

    /**
     * @type {number}
     * @memberof ListInstancesRequest
     */
    OrderBy?: number;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    SpecNames?: string;

    /**
     * @type {Array<TagFilterForListInstancesInput>}
     * @memberof ListInstancesRequest
     */
    TagFilters?: Array<TagFilterForListInstancesInput>;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    VPCIdentities?: string;

    /**
     * @type {boolean}
     * @memberof ListInstancesRequest
     */
    WithTagInfo?: boolean;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    cidrs?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    cities?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    countries?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    ips?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    isps?: string;

    /**
     * @type {number}
     * @memberof ListInstancesRequest
     */
    limit?: number;

    /**
     * @type {number}
     * @memberof ListInstancesRequest
     */
    page?: number;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    projects?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    regions?: string;

    /**
     * @type {string}
     * @memberof ListInstancesRequest
     */
    status?: string;
}
