/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PolicyForModifySecurityGroupRuleInput } from './policy-for-modify-security-group-rule-input';
 /**
 * 
 *
 * @export
 * @interface ModifySecurityGroupRuleRequest
 */
export interface ModifySecurityGroupRuleRequest {

    /**
     * @type {string}
     * @memberof ModifySecurityGroupRuleRequest
     */
    group_identity: string;

    /**
     * @type {PolicyForModifySecurityGroupRuleInput}
     * @memberof ModifySecurityGroupRuleRequest
     */
    policy?: PolicyForModifySecurityGroupRuleInput;

    /**
     * @type {string}
     * @memberof ModifySecurityGroupRuleRequest
     */
    rule_identity: string;
}
