/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BandwidthPeakConfigRatioForGetInstanceOutput } from './bandwidth-peak-config-ratio-for-get-instance-output';
import { ExternalInterfaceForGetInstanceOutput } from './external-interface-for-get-instance-output';
import { InternalInterfaceForGetInstanceOutput } from './internal-interface-for-get-instance-output';
 /**
 * 
 *
 * @export
 * @interface NetworkForGetInstanceOutput
 */
export interface NetworkForGetInstanceOutput {

    /**
     * @type {number}
     * @memberof NetworkForGetInstanceOutput
     */
    actual_secondary_ip_num?: number;

    /**
     * @type {BandwidthPeakConfigRatioForGetInstanceOutput}
     * @memberof NetworkForGetInstanceOutput
     */
    bandwidth_peak_config_ratio?: BandwidthPeakConfigRatioForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    bandwidth_peak_update_status?: NetworkForGetInstanceOutputBandwidthPeakUpdateStatusEnum;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    custom_external_interface_name?: string;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    custom_internal_interface_name?: string;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    default_isp?: string;

    /**
     * @type {boolean}
     * @memberof NetworkForGetInstanceOutput
     */
    disable_ipv4?: boolean;

    /**
     * @type {Array<string>}
     * @memberof NetworkForGetInstanceOutput
     */
    dns_list?: Array<string>;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    dns_type?: NetworkForGetInstanceOutputDnsTypeEnum;

    /**
     * @type {boolean}
     * @memberof NetworkForGetInstanceOutput
     */
    enable_ipv6?: boolean;

    /**
     * @type {ExternalInterfaceForGetInstanceOutput}
     * @memberof NetworkForGetInstanceOutput
     */
    external_interface?: ExternalInterfaceForGetInstanceOutput;

    /**
     * @type {Array<ExternalInterfaceForGetInstanceOutput>}
     * @memberof NetworkForGetInstanceOutput
     */
    external_interfaces?: Array<ExternalInterfaceForGetInstanceOutput>;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    external_network_mode?: NetworkForGetInstanceOutputExternalNetworkModeEnum;

    /**
     * @type {InternalInterfaceForGetInstanceOutput}
     * @memberof NetworkForGetInstanceOutput
     */
    internal_interface?: InternalInterfaceForGetInstanceOutput;

    /**
     * @type {string}
     * @memberof NetworkForGetInstanceOutput
     */
    limit_mode?: NetworkForGetInstanceOutputLimitModeEnum;

    /**
     * @type {number}
     * @memberof NetworkForGetInstanceOutput
     */
    tcp_timeout?: number;

    /**
     * @type {number}
     * @memberof NetworkForGetInstanceOutput
     */
    udp_timeout?: number;

    /**
     * @type {boolean}
     * @memberof NetworkForGetInstanceOutput
     */
    vf_passthrough?: boolean;

    /**
     * @type {boolean}
     * @memberof NetworkForGetInstanceOutput
     */
    vlan_vf_passthrough?: boolean;

    /**
     * @type {number}
     * @memberof NetworkForGetInstanceOutput
     */
    wanted_secondary_ip_num?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum NetworkForGetInstanceOutputBandwidthPeakUpdateStatusEnum {
    Updating = 'updating',
    Ready = 'ready'
}
/**
 * @export
 * @enum {string}
 */
export enum NetworkForGetInstanceOutputDnsTypeEnum {
    Default = 'default',
    Custom = 'custom'
}
/**
 * @export
 * @enum {string}
 */
export enum NetworkForGetInstanceOutputExternalNetworkModeEnum {
    SingleInterfaceMultiIp = 'single_interface_multi_ip',
    SingleInterfaceCmccIp = 'single_interface_cmcc_ip',
    SingleInterfaceCuccIp = 'single_interface_cucc_ip',
    SingleInterfaceCtccIp = 'single_interface_ctcc_ip',
    MultiInterfaceMultiIp = 'multi_interface_multi_ip',
    Rebooting = 'rebooting',
    NoInterface = 'no_interface'
}
/**
 * @export
 * @enum {string}
 */
export enum NetworkForGetInstanceOutputLimitModeEnum {
    Shared = 'shared',
    Isp = 'isp'
}

