/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PolicyForModifySecurityGroupRuleInput
 */
export interface PolicyForModifySecurityGroupRuleInput {

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    direction?: PolicyForModifySecurityGroupRuleInputDirectionEnum;

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    ip_cidr?: string;

    /**
     * @type {Array<string>}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    ip_cidrs?: Array<string>;

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    ports?: string;

    /**
     * @type {number}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    priority?: number;

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    protocol?: string;

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    remark?: string;

    /**
     * @type {string}
     * @memberof PolicyForModifySecurityGroupRuleInput
     */
    rule?: PolicyForModifySecurityGroupRuleInputRuleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PolicyForModifySecurityGroupRuleInputDirectionEnum {
    Ingress = 'ingress',
    Egress = 'egress'
}
/**
 * @export
 * @enum {string}
 */
export enum PolicyForModifySecurityGroupRuleInputRuleEnum {
    Allow = 'allow',
    Reject = 'reject'
}

