/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RuleForDescribeSecurityGroupOutput
 */
export interface RuleForDescribeSecurityGroupOutput {

    /**
     * @type {number}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    create_time?: number;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    direction?: RuleForDescribeSecurityGroupOutputDirectionEnum;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    group_identity?: string;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    ip_cidr?: string;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    ip_type?: RuleForDescribeSecurityGroupOutputIpTypeEnum;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    ports?: string;

    /**
     * @type {number}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    priority?: number;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    protocol?: RuleForDescribeSecurityGroupOutputProtocolEnum;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    remark?: string;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    rule?: RuleForDescribeSecurityGroupOutputRuleEnum;

    /**
     * @type {string}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    rule_identity?: string;

    /**
     * @type {number}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    status?: number;

    /**
     * @type {number}
     * @memberof RuleForDescribeSecurityGroupOutput
     */
    update_time?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum RuleForDescribeSecurityGroupOutputDirectionEnum {
    Ingress = 'ingress',
    Egress = 'egress'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForDescribeSecurityGroupOutputIpTypeEnum {
    Ipv4 = 'ipv4',
    Ipv6 = 'ipv6'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForDescribeSecurityGroupOutputProtocolEnum {
    TCP = 'TCP',
    UDP = 'UDP',
    ICMP = 'ICMP',
    ANY = 'ANY',
    GRE = 'GRE'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForDescribeSecurityGroupOutputRuleEnum {
    Allow = 'allow',
    Reject = 'reject'
}

