/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RuleForCopySecurityGroupOutput
 */
export interface RuleForCopySecurityGroupOutput {

    /**
     * @type {number}
     * @memberof RuleForCopySecurityGroupOutput
     */
    create_time?: number;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    direction?: RuleForCopySecurityGroupOutputDirectionEnum;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    group_identity?: string;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    ip_cidr?: string;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    ip_type?: RuleForCopySecurityGroupOutputIpTypeEnum;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    ports?: string;

    /**
     * @type {number}
     * @memberof RuleForCopySecurityGroupOutput
     */
    priority?: number;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    protocol?: RuleForCopySecurityGroupOutputProtocolEnum;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    remark?: string;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    rule?: RuleForCopySecurityGroupOutputRuleEnum;

    /**
     * @type {string}
     * @memberof RuleForCopySecurityGroupOutput
     */
    rule_identity?: string;

    /**
     * @type {number}
     * @memberof RuleForCopySecurityGroupOutput
     */
    status?: number;

    /**
     * @type {number}
     * @memberof RuleForCopySecurityGroupOutput
     */
    update_time?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum RuleForCopySecurityGroupOutputDirectionEnum {
    Ingress = 'ingress',
    Egress = 'egress'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForCopySecurityGroupOutputIpTypeEnum {
    Ipv4 = 'ipv4',
    Ipv6 = 'ipv6'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForCopySecurityGroupOutputProtocolEnum {
    TCP = 'TCP',
    UDP = 'UDP',
    ICMP = 'ICMP',
    ANY = 'ANY',
    GRE = 'GRE'
}
/**
 * @export
 * @enum {string}
 */
export enum RuleForCopySecurityGroupOutputRuleEnum {
    Allow = 'allow',
    Reject = 'reject'
}

