/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BindsForCreateSecurityGroupOutput } from './binds-for-create-security-group-output';
import { EgressRuleForCreateSecurityGroupOutput } from './egress-rule-for-create-security-group-output';
import { IngressRuleForCreateSecurityGroupOutput } from './ingress-rule-for-create-security-group-output';
import { TagForCreateSecurityGroupOutput } from './tag-for-create-security-group-output';
 /**
 * 
 *
 * @export
 * @interface SecurityGroupForCreateSecurityGroupOutput
 */
export interface SecurityGroupForCreateSecurityGroupOutput {

    /**
     * @type {Array<TagForCreateSecurityGroupOutput>}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    Tags?: Array<TagForCreateSecurityGroupOutput>;

    /**
     * @type {number}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    account_identity?: number;

    /**
     * @type {BindsForCreateSecurityGroupOutput}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    binds?: BindsForCreateSecurityGroupOutput;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    city?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    cluster_name?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    cluster_name_alias?: string;

    /**
     * @type {number}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    create_time?: number;

    /**
     * @type {EgressRuleForCreateSecurityGroupOutput}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    egress_rule?: EgressRuleForCreateSecurityGroupOutput;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    group_identity?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    group_type?: SecurityGroupForCreateSecurityGroupOutputGroupTypeEnum;

    /**
     * @type {IngressRuleForCreateSecurityGroupOutput}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    ingress_rule?: IngressRuleForCreateSecurityGroupOutput;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    name?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    project?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    region?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    remark?: string;

    /**
     * @type {number}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    update_time?: number;

    /**
     * @type {number}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    user_identity?: number;

    /**
     * @type {Array<string>}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    vpc_cidr?: Array<string>;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    vpc_identity?: string;

    /**
     * @type {string}
     * @memberof SecurityGroupForCreateSecurityGroupOutput
     */
    vpc_name?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SecurityGroupForCreateSecurityGroupOutputGroupTypeEnum {
    Default = 'default',
    Custom = 'custom'
}

