/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateInstancesSpecRequest
 */
export interface UpdateInstancesSpecRequest {

    /**
     * @type {Array<string>}
     * @memberof UpdateInstancesSpecRequest
     */
    instance_identities?: Array<string>;

    /**
     * @type {string}
     * @memberof UpdateInstancesSpecRequest
     */
    new_spec_name: string;
}
