/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ClusterForListVPCInstancesOutput } from './cluster-for-list-vpcinstances-output';
import { ResourceStatisticForListVPCInstancesOutput } from './resource-statistic-for-list-vpcinstances-output';
import { SubNetForListVPCInstancesOutput } from './sub-net-for-list-vpcinstances-output';
import { TagForListVPCInstancesOutput } from './tag-for-list-vpcinstances-output';
 /**
 * 
 *
 * @export
 * @interface VpcInstanceForListVPCInstancesOutput
 */
export interface VpcInstanceForListVPCInstancesOutput {

    /**
     * @type {Array<TagForListVPCInstancesOutput>}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    Tags?: Array<TagForListVPCInstancesOutput>;

    /**
     * @type {ClusterForListVPCInstancesOutput}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    cluster?: ClusterForListVPCInstancesOutput;

    /**
     * @type {number}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    create_time?: number;

    /**
     * @type {number}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    cross_account_vgw_num?: number;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    desc?: string;

    /**
     * @type {boolean}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    is_custom?: boolean;

    /**
     * @type {boolean}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    is_default?: boolean;

    /**
     * @type {boolean}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    is_vlan?: boolean;

    /**
     * @type {number}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    local_account_vgw_num?: number;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    project?: string;

    /**
     * @type {ResourceStatisticForListVPCInstancesOutput}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    resource_statistic?: ResourceStatisticForListVPCInstancesOutput;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    segment?: string;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    status?: VpcInstanceForListVPCInstancesOutputStatusEnum;

    /**
     * @type {Array<SubNetForListVPCInstancesOutput>}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    sub_nets?: Array<SubNetForListVPCInstancesOutput>;

    /**
     * @type {number}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    update_time?: number;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    vpc_identity?: string;

    /**
     * @type {string}
     * @memberof VpcInstanceForListVPCInstancesOutput
     */
    vpc_name?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum VpcInstanceForListVPCInstancesOutputStatusEnum {
    Available = 'available',
    Modifying = 'modifying'
}

