/* tslint:disable */
/* eslint-disable */
/**
 * veenedge
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ClusterForListRouteTableAssociatedSubnetsOutput } from './cluster-for-list-route-table-associated-subnets-output';
 /**
 * 
 *
 * @export
 * @interface VpcInfoForListRouteTableAssociatedSubnetsOutput
 */
export interface VpcInfoForListRouteTableAssociatedSubnetsOutput {

    /**
     * @type {ClusterForListRouteTableAssociatedSubnetsOutput}
     * @memberof VpcInfoForListRouteTableAssociatedSubnetsOutput
     */
    cluster?: ClusterForListRouteTableAssociatedSubnetsOutput;

    /**
     * @type {boolean}
     * @memberof VpcInfoForListRouteTableAssociatedSubnetsOutput
     */
    is_custom?: boolean;

    /**
     * @type {string}
     * @memberof VpcInfoForListRouteTableAssociatedSubnetsOutput
     */
    vpc_identity?: string;

    /**
     * @type {string}
     * @memberof VpcInfoForListRouteTableAssociatedSubnetsOutput
     */
    vpc_name?: string;
}
