/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeIpamResourceDiscoveryAssociationsRequest
 */
export interface DescribeIpamResourceDiscoveryAssociationsRequest {

    /**
     * @type {string}
     * @memberof DescribeIpamResourceDiscoveryAssociationsRequest
     */
    IpamId?: string;

    /**
     * @type {string}
     * @memberof DescribeIpamResourceDiscoveryAssociationsRequest
     */
    IpamResourceDiscoveryId?: string;

    /**
     * @type {number}
     * @memberof DescribeIpamResourceDiscoveryAssociationsRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof DescribeIpamResourceDiscoveryAssociationsRequest
     */
    NextToken?: string;
}
