/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyIpamRequest
 */
export interface ModifyIpamRequest {

    /**
     * @type {Array<string>}
     * @memberof ModifyIpamRequest
     */
    AddOperatingRegions?: Array<string>;

    /**
     * @type {string}
     * @memberof ModifyIpamRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ModifyIpamRequest
     */
    IpamId: string;

    /**
     * @type {string}
     * @memberof ModifyIpamRequest
     */
    IpamName?: string;

    /**
     * @type {Array<string>}
     * @memberof ModifyIpamRequest
     */
    RemoveOperatingRegions?: Array<string>;
}
