/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyIpamPoolRequest
 */
export interface ModifyIpamPoolRequest {

    /**
     * @type {number}
     * @memberof ModifyIpamPoolRequest
     */
    AllocationDefaultCidrMask?: number;

    /**
     * @type {number}
     * @memberof ModifyIpamPoolRequest
     */
    AllocationMaxCidrMask?: number;

    /**
     * @type {number}
     * @memberof ModifyIpamPoolRequest
     */
    AllocationMinCidrMask?: number;

    /**
     * @type {boolean}
     * @memberof ModifyIpamPoolRequest
     */
    AutoImport?: boolean;

    /**
     * @type {boolean}
     * @memberof ModifyIpamPoolRequest
     */
    ClearAllocationDefaultCidrMask?: boolean;

    /**
     * @type {string}
     * @memberof ModifyIpamPoolRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ModifyIpamPoolRequest
     */
    IpamPoolId: string;

    /**
     * @type {string}
     * @memberof ModifyIpamPoolRequest
     */
    IpamPoolName?: string;
}
