/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TargetTextForProjectNamespaceSourceDetailOutput } from './target-text-for-project-namespace-source-detail-output';
import { TextExtraForProjectNamespaceSourceDetailOutput } from './text-extra-for-project-namespace-source-detail-output';
 /**
 * 
 *
 * @export
 * @interface DataForProjectNamespaceSourceDetailOutput
 */
export interface DataForProjectNamespaceSourceDetailOutput {

    /**
     * @type {number}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    approvalStatus?: number;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    commentary?: string;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    content?: string;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    createdAt?: string;

    /**
     * @type {number}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    keyText?: string;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    lang?: string;

    /**
     * @type {number}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    lengthLimit?: number;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    operatorName?: string;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    tagName?: string;

    /**
     * @type {Array<TargetTextForProjectNamespaceSourceDetailOutput>}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    targetTexts?: Array<TargetTextForProjectNamespaceSourceDetailOutput>;

    /**
     * @type {number}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    taskId?: number;

    /**
     * @type {TextExtraForProjectNamespaceSourceDetailOutput}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    textExtra?: TextExtraForProjectNamespaceSourceDetailOutput;

    /**
     * @type {number}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    translatedStatus?: number;

    /**
     * @type {string}
     * @memberof DataForProjectNamespaceSourceDetailOutput
     */
    updatedAt?: string;
}
