/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ToolTaskForVideoProjectGetToolTaskOutput } from './tool-task-for-video-project-get-tool-task-output';
 /**
 * 
 *
 * @export
 * @interface DataForVideoProjectGetToolTaskOutput
 */
export interface DataForVideoProjectGetToolTaskOutput {

    /**
     * @type {ToolTaskForVideoProjectGetToolTaskOutput}
     * @memberof DataForVideoProjectGetToolTaskOutput
     */
    toolTask?: ToolTaskForVideoProjectGetToolTaskOutput;
}
