/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DocUrlListForDocumentTaskCreateInput } from './doc-url-list-for-document-task-create-input';
import { ReferenceDocItemForDocumentTaskCreateInput } from './reference-doc-item-for-document-task-create-input';
 /**
 * 
 *
 * @export
 * @interface DocumentTaskCreateRequest
 */
export interface DocumentTaskCreateRequest {

    /**
     * @type {string}
     * @memberof DocumentTaskCreateRequest
     */
    comment?: string;

    /**
     * @type {string}
     * @memberof DocumentTaskCreateRequest
     */
    deadline: string;

    /**
     * @type {Array<DocUrlListForDocumentTaskCreateInput>}
     * @memberof DocumentTaskCreateRequest
     */
    docUrlList?: Array<DocUrlListForDocumentTaskCreateInput>;

    /**
     * @type {number}
     * @memberof DocumentTaskCreateRequest
     */
    procedures?: number;

    /**
     * @type {number}
     * @memberof DocumentTaskCreateRequest
     */
    projectId: number;

    /**
     * @type {number}
     * @memberof DocumentTaskCreateRequest
     */
    proofreadType?: number;

    /**
     * @type {ReferenceDocItemForDocumentTaskCreateInput}
     * @memberof DocumentTaskCreateRequest
     */
    referenceDocItem?: ReferenceDocItemForDocumentTaskCreateInput;

    /**
     * @type {string}
     * @memberof DocumentTaskCreateRequest
     */
    sourceLocale?: string;

    /**
     * @type {Array<string>}
     * @memberof DocumentTaskCreateRequest
     */
    targetLocale?: Array<string>;

    /**
     * @type {string}
     * @memberof DocumentTaskCreateRequest
     */
    taskName: string;

    /**
     * @type {number}
     * @memberof DocumentTaskCreateRequest
     */
    translatorType?: number;

    /**
     * @type {boolean}
     * @memberof DocumentTaskCreateRequest
     */
    useTM?: boolean;
}
