/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreatorForVideoProjectListVideoDramaOutput } from './creator-for-video-project-list-video-drama-output';
 /**
 * 
 *
 * @export
 * @interface DramaForVideoProjectListVideoDramaOutput
 */
export interface DramaForVideoProjectListVideoDramaOutput {

    /**
     * @type {boolean}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    canDelete?: boolean;

    /**
     * @type {string}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    createTime?: string;

    /**
     * @type {CreatorForVideoProjectListVideoDramaOutput}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    creator?: CreatorForVideoProjectListVideoDramaOutput;

    /**
     * @type {string}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    dramaId?: string;

    /**
     * @type {number}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    dramaType?: number;

    /**
     * @type {boolean}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    hasDubTask?: boolean;

    /**
     * @type {string}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    name?: string;

    /**
     * @type {string}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    projectId?: string;

    /**
     * @type {Array<string>}
     * @memberof DramaForVideoProjectListVideoDramaOutput
     */
    targetLangs?: Array<string>;
}
