/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FinishedAudioForVideoProjectGetTaskProductOutput
 */
export interface FinishedAudioForVideoProjectGetTaskProductOutput {

    /**
     * @type {string}
     * @memberof FinishedAudioForVideoProjectGetTaskProductOutput
     */
    name?: string;

    /**
     * @type {string}
     * @memberof FinishedAudioForVideoProjectGetTaskProductOutput
     */
    url?: string;
}
