/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
 */
export interface InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput {

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    posterUrl?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    sourceLastTime?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    sourceName?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    sourceVid?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    sourceVideoUrl?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    targetDownloadUrl?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    targetLastTime?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    targetName?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    targetVid?: string;

    /**
     * @type {string}
     * @memberof InputVideoInfoForVideoProjectListToolTaskByResourceIDsOutput
     */
    targetVideoUrl?: string;
}
