/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreatorForTermBaseTermGroupsOutput } from './creator-for-term-base-term-groups-output';
 /**
 * 
 *
 * @export
 * @interface JaForTermBaseTermGroupsOutput
 */
export interface JaForTermBaseTermGroupsOutput {

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    acronym?: string;

    /**
     * @type {number}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    applyMode?: number;

    /**
     * @type {number}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    caseSensitive?: number;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    content?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    createTime?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    createdAt?: string;

    /**
     * @type {CreatorForTermBaseTermGroupsOutput}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    creator?: CreatorForTermBaseTermGroupsOutput;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    id?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    lang?: string;

    /**
     * @type {CreatorForTermBaseTermGroupsOutput}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    operator?: CreatorForTermBaseTermGroupsOutput;

    /**
     * @type {number}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    partOfSpeech?: number;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    termBaseId?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    termGroupId?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    updateTime?: string;

    /**
     * @type {string}
     * @memberof JaForTermBaseTermGroupsOutput
     */
    updatedAt?: string;
}
