/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AfForTermBaseTermGroupsOutput } from './af-for-term-base-term-groups-output';
import { AfZAForTermBaseTermGroupsOutput } from './af-zafor-term-base-term-groups-output';
import { ArARForTermBaseTermGroupsOutput } from './ar-arfor-term-base-term-groups-output';
import { ArDZForTermBaseTermGroupsOutput } from './ar-dzfor-term-base-term-groups-output';
import { ArForTermBaseTermGroupsOutput } from './ar-for-term-base-term-groups-output';
import { ArSYForTermBaseTermGroupsOutput } from './ar-syfor-term-base-term-groups-output';
import { ArYEForTermBaseTermGroupsOutput } from './ar-yefor-term-base-term-groups-output';
import { BeForTermBaseTermGroupsOutput } from './be-for-term-base-term-groups-output';
import { BnBDForTermBaseTermGroupsOutput } from './bn-bdfor-term-base-term-groups-output';
import { BnForTermBaseTermGroupsOutput } from './bn-for-term-base-term-groups-output';
import { DaForTermBaseTermGroupsOutput } from './da-for-term-base-term-groups-output';
import { DeDEForTermBaseTermGroupsOutput } from './de-defor-term-base-term-groups-output';
import { DeForTermBaseTermGroupsOutput } from './de-for-term-base-term-groups-output';
import { EnDAForTermBaseTermGroupsOutput } from './en-dafor-term-base-term-groups-output';
import { EnForTermBaseTermGroupsOutput } from './en-for-term-base-term-groups-output';
import { EnGBForTermBaseTermGroupsOutput } from './en-gbfor-term-base-term-groups-output';
import { EnINForTermBaseTermGroupsOutput } from './en-infor-term-base-term-groups-output';
import { EnPHForTermBaseTermGroupsOutput } from './en-phfor-term-base-term-groups-output';
import { EnSGForTermBaseTermGroupsOutput } from './en-sgfor-term-base-term-groups-output';
import { EnUSForTermBaseTermGroupsOutput } from './en-usfor-term-base-term-groups-output';
import { Es419ForTermBaseTermGroupsOutput } from './es419-for-term-base-term-groups-output';
import { EsESForTermBaseTermGroupsOutput } from './es-esfor-term-base-term-groups-output';
import { EsForTermBaseTermGroupsOutput } from './es-for-term-base-term-groups-output';
import { EsUSForTermBaseTermGroupsOutput } from './es-usfor-term-base-term-groups-output';
import { FaIRForTermBaseTermGroupsOutput } from './fa-irfor-term-base-term-groups-output';
import { FilForTermBaseTermGroupsOutput } from './fil-for-term-base-term-groups-output';
import { FilPHForTermBaseTermGroupsOutput } from './fil-phfor-term-base-term-groups-output';
import { FrFRForTermBaseTermGroupsOutput } from './fr-frfor-term-base-term-groups-output';
import { FrForTermBaseTermGroupsOutput } from './fr-for-term-base-term-groups-output';
import { HiForTermBaseTermGroupsOutput } from './hi-for-term-base-term-groups-output';
import { HiINForTermBaseTermGroupsOutput } from './hi-infor-term-base-term-groups-output';
import { IdForTermBaseTermGroupsOutput } from './id-for-term-base-term-groups-output';
import { IdIDForTermBaseTermGroupsOutput } from './id-idfor-term-base-term-groups-output';
import { ItForTermBaseTermGroupsOutput } from './it-for-term-base-term-groups-output';
import { ItITForTermBaseTermGroupsOutput } from './it-itfor-term-base-term-groups-output';
import { JaForTermBaseTermGroupsOutput } from './ja-for-term-base-term-groups-output';
import { JaJPForTermBaseTermGroupsOutput } from './ja-jpfor-term-base-term-groups-output';
import { KaForTermBaseTermGroupsOutput } from './ka-for-term-base-term-groups-output';
import { KkKZForTermBaseTermGroupsOutput } from './kk-kzfor-term-base-term-groups-output';
import { KlForTermBaseTermGroupsOutput } from './kl-for-term-base-term-groups-output';
import { KmForTermBaseTermGroupsOutput } from './km-for-term-base-term-groups-output';
import { KmKHForTermBaseTermGroupsOutput } from './km-khfor-term-base-term-groups-output';
import { KoForTermBaseTermGroupsOutput } from './ko-for-term-base-term-groups-output';
import { KoKRForTermBaseTermGroupsOutput } from './ko-krfor-term-base-term-groups-output';
import { MnForTermBaseTermGroupsOutput } from './mn-for-term-base-term-groups-output';
import { MsForTermBaseTermGroupsOutput } from './ms-for-term-base-term-groups-output';
import { MsMYForTermBaseTermGroupsOutput } from './ms-myfor-term-base-term-groups-output';
import { MyForTermBaseTermGroupsOutput } from './my-for-term-base-term-groups-output';
import { NeForTermBaseTermGroupsOutput } from './ne-for-term-base-term-groups-output';
import { PlForTermBaseTermGroupsOutput } from './pl-for-term-base-term-groups-output';
import { PlPLForTermBaseTermGroupsOutput } from './pl-plfor-term-base-term-groups-output';
import { PtBRForTermBaseTermGroupsOutput } from './pt-brfor-term-base-term-groups-output';
import { PtForTermBaseTermGroupsOutput } from './pt-for-term-base-term-groups-output';
import { PtPTForTermBaseTermGroupsOutput } from './pt-ptfor-term-base-term-groups-output';
import { RoForTermBaseTermGroupsOutput } from './ro-for-term-base-term-groups-output';
import { RuForTermBaseTermGroupsOutput } from './ru-for-term-base-term-groups-output';
import { RuRUForTermBaseTermGroupsOutput } from './ru-rufor-term-base-term-groups-output';
import { SkForTermBaseTermGroupsOutput } from './sk-for-term-base-term-groups-output';
import { SlForTermBaseTermGroupsOutput } from './sl-for-term-base-term-groups-output';
import { SourceForTermBaseTermGroupsOutput } from './source-for-term-base-term-groups-output';
import { SrForTermBaseTermGroupsOutput } from './sr-for-term-base-term-groups-output';
import { SvForTermBaseTermGroupsOutput } from './sv-for-term-base-term-groups-output';
import { TaForTermBaseTermGroupsOutput } from './ta-for-term-base-term-groups-output';
import { TargetForTermBaseTermGroupsOutput } from './target-for-term-base-term-groups-output';
import { TeForTermBaseTermGroupsOutput } from './te-for-term-base-term-groups-output';
import { ThForTermBaseTermGroupsOutput } from './th-for-term-base-term-groups-output';
import { ThTHForTermBaseTermGroupsOutput } from './th-thfor-term-base-term-groups-output';
import { TlPHForTermBaseTermGroupsOutput } from './tl-phfor-term-base-term-groups-output';
import { TrForTermBaseTermGroupsOutput } from './tr-for-term-base-term-groups-output';
import { TrTRForTermBaseTermGroupsOutput } from './tr-trfor-term-base-term-groups-output';
import { UrForTermBaseTermGroupsOutput } from './ur-for-term-base-term-groups-output';
import { UzForTermBaseTermGroupsOutput } from './uz-for-term-base-term-groups-output';
import { ViForTermBaseTermGroupsOutput } from './vi-for-term-base-term-groups-output';
import { ViVNForTermBaseTermGroupsOutput } from './vi-vnfor-term-base-term-groups-output';
import { ZhCNForTermBaseTermGroupsOutput } from './zh-cnfor-term-base-term-groups-output';
import { ZhForTermBaseTermGroupsOutput } from './zh-for-term-base-term-groups-output';
import { ZhHKForTermBaseTermGroupsOutput } from './zh-hkfor-term-base-term-groups-output';
import { ZhHansCNForTermBaseTermGroupsOutput } from './zh-hans-cnfor-term-base-term-groups-output';
import { ZhHansForTermBaseTermGroupsOutput } from './zh-hans-for-term-base-term-groups-output';
import { ZhHantForTermBaseTermGroupsOutput } from './zh-hant-for-term-base-term-groups-output';
import { ZhTWForTermBaseTermGroupsOutput } from './zh-twfor-term-base-term-groups-output';
 /**
 * 
 *
 * @export
 * @interface LangItemMapForTermBaseTermGroupsOutput
 */
export interface LangItemMapForTermBaseTermGroupsOutput {

    /**
     * @type {AfForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    af?: AfForTermBaseTermGroupsOutput;

    /**
     * @type {AfZAForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    afZA?: AfZAForTermBaseTermGroupsOutput;

    /**
     * @type {ArForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ar?: ArForTermBaseTermGroupsOutput;

    /**
     * @type {ArARForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    arAR?: ArARForTermBaseTermGroupsOutput;

    /**
     * @type {ArDZForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    arDZ?: ArDZForTermBaseTermGroupsOutput;

    /**
     * @type {ArSYForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    arSY?: ArSYForTermBaseTermGroupsOutput;

    /**
     * @type {ArYEForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    arYE?: ArYEForTermBaseTermGroupsOutput;

    /**
     * @type {BeForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    be?: BeForTermBaseTermGroupsOutput;

    /**
     * @type {BnForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    bn?: BnForTermBaseTermGroupsOutput;

    /**
     * @type {BnBDForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    bnBD?: BnBDForTermBaseTermGroupsOutput;

    /**
     * @type {DaForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    da?: DaForTermBaseTermGroupsOutput;

    /**
     * @type {DeForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    de?: DeForTermBaseTermGroupsOutput;

    /**
     * @type {DeDEForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    deDE?: DeDEForTermBaseTermGroupsOutput;

    /**
     * @type {EnForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    en?: EnForTermBaseTermGroupsOutput;

    /**
     * @type {EnDAForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enDA?: EnDAForTermBaseTermGroupsOutput;

    /**
     * @type {EnGBForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enGB?: EnGBForTermBaseTermGroupsOutput;

    /**
     * @type {EnINForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enIN?: EnINForTermBaseTermGroupsOutput;

    /**
     * @type {EnPHForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enPH?: EnPHForTermBaseTermGroupsOutput;

    /**
     * @type {EnSGForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enSG?: EnSGForTermBaseTermGroupsOutput;

    /**
     * @type {EnUSForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    enUS?: EnUSForTermBaseTermGroupsOutput;

    /**
     * @type {EsForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    es?: EsForTermBaseTermGroupsOutput;

    /**
     * @type {Es419ForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    es419?: Es419ForTermBaseTermGroupsOutput;

    /**
     * @type {EsESForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    esES?: EsESForTermBaseTermGroupsOutput;

    /**
     * @type {EsUSForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    esUS?: EsUSForTermBaseTermGroupsOutput;

    /**
     * @type {FaIRForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    faIR?: FaIRForTermBaseTermGroupsOutput;

    /**
     * @type {FilForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    fil?: FilForTermBaseTermGroupsOutput;

    /**
     * @type {FilPHForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    filPH?: FilPHForTermBaseTermGroupsOutput;

    /**
     * @type {FrForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    fr?: FrForTermBaseTermGroupsOutput;

    /**
     * @type {FrFRForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    frFR?: FrFRForTermBaseTermGroupsOutput;

    /**
     * @type {HiForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    hi?: HiForTermBaseTermGroupsOutput;

    /**
     * @type {HiINForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    hiIN?: HiINForTermBaseTermGroupsOutput;

    /**
     * @type {IdForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    id?: IdForTermBaseTermGroupsOutput;

    /**
     * @type {IdIDForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    idID?: IdIDForTermBaseTermGroupsOutput;

    /**
     * @type {ItForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    it?: ItForTermBaseTermGroupsOutput;

    /**
     * @type {ItITForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    itIT?: ItITForTermBaseTermGroupsOutput;

    /**
     * @type {JaForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ja?: JaForTermBaseTermGroupsOutput;

    /**
     * @type {JaJPForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    jaJP?: JaJPForTermBaseTermGroupsOutput;

    /**
     * @type {KaForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ka?: KaForTermBaseTermGroupsOutput;

    /**
     * @type {KkKZForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    kkKZ?: KkKZForTermBaseTermGroupsOutput;

    /**
     * @type {KlForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    kl?: KlForTermBaseTermGroupsOutput;

    /**
     * @type {KmForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    km?: KmForTermBaseTermGroupsOutput;

    /**
     * @type {KmKHForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    kmKH?: KmKHForTermBaseTermGroupsOutput;

    /**
     * @type {KoForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ko?: KoForTermBaseTermGroupsOutput;

    /**
     * @type {KoKRForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    koKR?: KoKRForTermBaseTermGroupsOutput;

    /**
     * @type {MnForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    mn?: MnForTermBaseTermGroupsOutput;

    /**
     * @type {MsForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ms?: MsForTermBaseTermGroupsOutput;

    /**
     * @type {MsMYForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    msMY?: MsMYForTermBaseTermGroupsOutput;

    /**
     * @type {MyForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    my?: MyForTermBaseTermGroupsOutput;

    /**
     * @type {NeForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ne?: NeForTermBaseTermGroupsOutput;

    /**
     * @type {PlForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    pl?: PlForTermBaseTermGroupsOutput;

    /**
     * @type {PlPLForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    plPL?: PlPLForTermBaseTermGroupsOutput;

    /**
     * @type {PtForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    pt?: PtForTermBaseTermGroupsOutput;

    /**
     * @type {PtBRForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ptBR?: PtBRForTermBaseTermGroupsOutput;

    /**
     * @type {PtPTForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ptPT?: PtPTForTermBaseTermGroupsOutput;

    /**
     * @type {RoForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ro?: RoForTermBaseTermGroupsOutput;

    /**
     * @type {RuForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ru?: RuForTermBaseTermGroupsOutput;

    /**
     * @type {RuRUForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ruRU?: RuRUForTermBaseTermGroupsOutput;

    /**
     * @type {SkForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    sk?: SkForTermBaseTermGroupsOutput;

    /**
     * @type {SlForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    sl?: SlForTermBaseTermGroupsOutput;

    /**
     * @type {SourceForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    source?: SourceForTermBaseTermGroupsOutput;

    /**
     * @type {SrForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    sr?: SrForTermBaseTermGroupsOutput;

    /**
     * @type {SvForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    sv?: SvForTermBaseTermGroupsOutput;

    /**
     * @type {TaForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ta?: TaForTermBaseTermGroupsOutput;

    /**
     * @type {TargetForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    target?: TargetForTermBaseTermGroupsOutput;

    /**
     * @type {TeForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    te?: TeForTermBaseTermGroupsOutput;

    /**
     * @type {ThForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    th?: ThForTermBaseTermGroupsOutput;

    /**
     * @type {ThTHForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    thTH?: ThTHForTermBaseTermGroupsOutput;

    /**
     * @type {TlPHForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    tlPH?: TlPHForTermBaseTermGroupsOutput;

    /**
     * @type {TrForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    tr?: TrForTermBaseTermGroupsOutput;

    /**
     * @type {TrTRForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    trTR?: TrTRForTermBaseTermGroupsOutput;

    /**
     * @type {UrForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    ur?: UrForTermBaseTermGroupsOutput;

    /**
     * @type {UzForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    uz?: UzForTermBaseTermGroupsOutput;

    /**
     * @type {ViForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    vi?: ViForTermBaseTermGroupsOutput;

    /**
     * @type {ViVNForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    viVN?: ViVNForTermBaseTermGroupsOutput;

    /**
     * @type {ZhForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zh?: ZhForTermBaseTermGroupsOutput;

    /**
     * @type {ZhCNForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhCN?: ZhCNForTermBaseTermGroupsOutput;

    /**
     * @type {ZhHKForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhHK?: ZhHKForTermBaseTermGroupsOutput;

    /**
     * @type {ZhHansForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhHans?: ZhHansForTermBaseTermGroupsOutput;

    /**
     * @type {ZhHansCNForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhHansCN?: ZhHansCNForTermBaseTermGroupsOutput;

    /**
     * @type {ZhHantForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhHant?: ZhHantForTermBaseTermGroupsOutput;

    /**
     * @type {ZhTWForTermBaseTermGroupsOutput}
     * @memberof LangItemMapForTermBaseTermGroupsOutput
     */
    zhTW?: ZhTWForTermBaseTermGroupsOutput;
}
