/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForProjectNamespaceSourceMultiUpdateOutput } from './data-for-project-namespace-source-multi-update-output';
 /**
 * 
 *
 * @export
 * @interface ProjectNamespaceSourceMultiUpdateResponse
 */
export interface ProjectNamespaceSourceMultiUpdateResponse {

    /**
     * @type {DataForProjectNamespaceSourceMultiUpdateOutput}
     * @memberof ProjectNamespaceSourceMultiUpdateResponse
     */
    data?: DataForProjectNamespaceSourceMultiUpdateOutput;
}
