/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProjectTaskSourcesRequest
 */
export interface ProjectTaskSourcesRequest {

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    distributeStatus?: number;

    /**
     * @type {Array<string>}
     * @memberof ProjectTaskSourcesRequest
     */
    keyTexts?: Array<string>;

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    limit?: number;

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    offset?: number;

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    projectId: number;

    /**
     * @type {string}
     * @memberof ProjectTaskSourcesRequest
     */
    searchKey?: string;

    /**
     * @type {string}
     * @memberof ProjectTaskSourcesRequest
     */
    searchSource?: string;

    /**
     * @type {string}
     * @memberof ProjectTaskSourcesRequest
     */
    searchTarget?: string;

    /**
     * @type {Array<number>}
     * @memberof ProjectTaskSourcesRequest
     */
    sourceIds?: Array<number>;

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    taskId: number;

    /**
     * @type {number}
     * @memberof ProjectTaskSourcesRequest
     */
    translatedStatus?: number;
}
