/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForProjectTasksOutput } from './data-for-project-tasks-output';
import { PaginationForProjectTasksOutput } from './pagination-for-project-tasks-output';
 /**
 * 
 *
 * @export
 * @interface ProjectTasksResponse
 */
export interface ProjectTasksResponse {

    /**
     * @type {Array<DataForProjectTasksOutput>}
     * @memberof ProjectTasksResponse
     */
    data?: Array<DataForProjectTasksOutput>;

    /**
     * @type {string}
     * @memberof ProjectTasksResponse
     */
    message?: string;

    /**
     * @type {PaginationForProjectTasksOutput}
     * @memberof ProjectTasksResponse
     */
    pagination?: PaginationForProjectTasksOutput;

    /**
     * @type {number}
     * @memberof ProjectTasksResponse
     */
    total?: number;
}
