/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TargetForVideoEditorAddSubtitleOutput
 */
export interface TargetForVideoEditorAddSubtitleOutput {

    /**
     * @type {string}
     * @memberof TargetForVideoEditorAddSubtitleOutput
     */
    style?: string;

    /**
     * @type {string}
     * @memberof TargetForVideoEditorAddSubtitleOutput
     */
    text?: string;
}
