/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ReferenceDocForVideoProjectSerialTaskCreateInput } from './reference-doc-for-video-project-serial-task-create-input';
import { SuppressionParamsForVideoProjectSerialTaskCreateInput } from './suppression-params-for-video-project-serial-task-create-input';
import { TargetStyleMapForVideoProjectSerialTaskCreateInput } from './target-style-map-for-video-project-serial-task-create-input';
 /**
 * 
 *
 * @export
 * @interface TaskInfoForVideoProjectSerialTaskCreateInput
 */
export interface TaskInfoForVideoProjectSerialTaskCreateInput {

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    aiRemoveType?: string;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    asrModel?: number;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    bgmPolicy?: number;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    comment?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    createdAt?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    deadline?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    dramaCoverUrl?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    dramaDescription?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    dramaTitle?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    dubOrTranslationTaskID?: string;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    isDub?: boolean;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    needTranslateCover?: boolean;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    needTranslateDesc?: boolean;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    needTranslateTitle?: boolean;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    needTranslateTitleAndDesc?: boolean;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    needVideoSpeed?: boolean;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    procedures?: number;

    /**
     * @type {ReferenceDocForVideoProjectSerialTaskCreateInput}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    referenceDoc?: ReferenceDocForVideoProjectSerialTaskCreateInput;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    serialNumber?: number;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    sourceLang?: string;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    sourceLocale?: string;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    state?: number;

    /**
     * @type {SuppressionParamsForVideoProjectSerialTaskCreateInput}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    suppressionParams?: SuppressionParamsForVideoProjectSerialTaskCreateInput;

    /**
     * @type {Array<string>}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    targetLangs?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    targetLocale?: Array<string>;

    /**
     * @type {TargetStyleMapForVideoProjectSerialTaskCreateInput}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    targetStyleMap?: TargetStyleMapForVideoProjectSerialTaskCreateInput;

    /**
     * @type {number}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    taskId?: number;

    /**
     * @type {string}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    taskName?: string;

    /**
     * @type {boolean}
     * @memberof TaskInfoForVideoProjectSerialTaskCreateInput
     */
    useMT?: boolean;
}
