/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VoiceForVideoEditorGetSpeakersOutput } from './voice-for-video-editor-get-speakers-output';
 /**
 * 
 *
 * @export
 * @interface TaskSpeakerForVideoEditorGetSpeakersOutput
 */
export interface TaskSpeakerForVideoEditorGetSpeakersOutput {

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    createAt?: number;

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    id?: number;

    /**
     * @type {string}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    speakerDesc?: string;

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    speakerId?: number;

    /**
     * @type {string}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    speakerName?: string;

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    speakerType?: number;

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    status?: number;

    /**
     * @type {number}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    updateAt?: number;

    /**
     * @type {Array<VoiceForVideoEditorGetSpeakersOutput>}
     * @memberof TaskSpeakerForVideoEditorGetSpeakersOutput
     */
    voices?: Array<VoiceForVideoEditorGetSpeakersOutput>;
}
