/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
 */
export interface UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput {

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    bindVid?: string;

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    errMsg?: string;

    /**
     * @type {number}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    fileType?: number;

    /**
     * @type {Array<string>}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    langs?: Array<string>;

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    name?: string;

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    projectId?: string;

    /**
     * @type {number}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    status?: number;

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    subtitleId?: string;

    /**
     * @type {string}
     * @memberof UploadSubtitleInfoForVideoProjectGetUploadSubtitleStatusOutput
     */
    url?: string;
}
