/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForVideoTermBasesOutput } from './data-for-video-term-bases-output';
import { PaginationForVideoTermBasesOutput } from './pagination-for-video-term-bases-output';
 /**
 * 
 *
 * @export
 * @interface VideoTermBasesResponse
 */
export interface VideoTermBasesResponse {

    /**
     * @type {Array<DataForVideoTermBasesOutput>}
     * @memberof VideoTermBasesResponse
     */
    data?: Array<DataForVideoTermBasesOutput>;

    /**
     * @type {PaginationForVideoTermBasesOutput}
     * @memberof VideoTermBasesResponse
     */
    pagination?: PaginationForVideoTermBasesOutput;

    /**
     * @type {number}
     * @memberof VideoTermBasesResponse
     */
    total?: number;
}
