/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForVideoEditorSaveSubtitleOutput } from './data-for-video-editor-save-subtitle-output';
 /**
 * 
 *
 * @export
 * @interface VideoEditorSaveSubtitleResponse
 */
export interface VideoEditorSaveSubtitleResponse {

    /**
     * @type {DataForVideoEditorSaveSubtitleOutput}
     * @memberof VideoEditorSaveSubtitleResponse
     */
    data?: DataForVideoEditorSaveSubtitleOutput;
}
