/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForVideoProjectGetUploadSubtitleStatusOutput } from './data-for-video-project-get-upload-subtitle-status-output';
 /**
 * 
 *
 * @export
 * @interface VideoProjectGetUploadSubtitleStatusResponse
 */
export interface VideoProjectGetUploadSubtitleStatusResponse {

    /**
     * @type {DataForVideoProjectGetUploadSubtitleStatusOutput}
     * @memberof VideoProjectGetUploadSubtitleStatusResponse
     */
    data?: DataForVideoProjectGetUploadSubtitleStatusOutput;
}
