/* tslint:disable */
/* eslint-disable */
/**
 * clawsentry
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client, ClientConfig, Command, buildRequestConfigFromMetaPath, CommandOutput } from '@volcengine/sdk-core';

import { CreateClawRequest } from './types/index';
import { CreateClawResponse } from './types/index';

// ============================================================================
// Output Type Definitions
// ============================================================================
export type CreateClawCommandOutput = CommandOutput<CreateClawResponse>;

/**
 * CLAWSENTRYClient Service Client
 */
export class CLAWSENTRYClient extends Client {
  constructor(config: ClientConfig = {}) {
    super({
      protocol: 'https',
      region: 'cn-beijing',
      ...config,
    });
  }
}

/**
 * Command to CreateClaw
 */
export class CreateClawCommand extends Command<
  CreateClawRequest,
  CreateClawCommandOutput,
  'CreateClawCommand'
> {
  static readonly metaPath = '/CreateClaw/2026-03-27/clawsentry/post/application_json/';

  constructor(input: CreateClawRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateClawCommand.metaPath);
  }
}

export default {
  CLAWSENTRYClient,
  CreateClawCommand,
};
