/* tslint:disable */
/* eslint-disable */
/**
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterInfoForCreateDataFlowTaskInput } from './filter-info-for-create-data-flow-task-input';
 /**
 * 
 *
 * @export
 * @interface ExportPolicyForCreateDataFlowTaskInput
 */
export interface ExportPolicyForCreateDataFlowTaskInput {

    /**
     * @type {Array<string>}
     * @memberof ExportPolicyForCreateDataFlowTaskInput
     */
    EventTypes?: Array<ExportPolicyForCreateDataFlowTaskInputEventTypesEnum>;

    /**
     * @type {FilterInfoForCreateDataFlowTaskInput}
     * @memberof ExportPolicyForCreateDataFlowTaskInput
     */
    FilterInfo?: FilterInfoForCreateDataFlowTaskInput;

    /**
     * @type {string}
     * @memberof ExportPolicyForCreateDataFlowTaskInput
     */
    Status?: ExportPolicyForCreateDataFlowTaskInputStatusEnum;

    /**
     * @type {string}
     * @memberof ExportPolicyForCreateDataFlowTaskInput
     */
    TosDeletePolicy?: ExportPolicyForCreateDataFlowTaskInputTosDeletePolicyEnum;

    /**
     * @type {string}
     * @memberof ExportPolicyForCreateDataFlowTaskInput
     */
    Type?: ExportPolicyForCreateDataFlowTaskInputTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ExportPolicyForCreateDataFlowTaskInputEventTypesEnum {
    CreateAndUpdate = 'CreateAndUpdate',
    Delete = 'Delete'
}
/**
 * @export
 * @enum {string}
 */
export enum ExportPolicyForCreateDataFlowTaskInputStatusEnum {
    Starting = 'Starting',
    Running = 'Running',
    Stopping = 'Stopping',
    Stopped = 'Stopped',
    Error = 'Error'
}
/**
 * @export
 * @enum {string}
 */
export enum ExportPolicyForCreateDataFlowTaskInputTosDeletePolicyEnum {
    None = 'None',
    LatestVersionOnly = 'LatestVersionOnly',
    AllVersions = 'AllVersions',
    SpecifiedVersion = 'SpecifiedVersion'
}
/**
 * @export
 * @enum {string}
 */
export enum ExportPolicyForCreateDataFlowTaskInputTypeEnum {
    None = 'None',
    Customize = 'Customize'
}

