/* tslint:disable */
/* eslint-disable */
/**
 * apmplus_server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ErrorTagsForGetTraceDetailOutput } from './error-tags-for-get-trace-detail-output';
 /**
 * 
 *
 * @export
 * @interface ErrorInfoListForGetTraceDetailOutput
 */
export interface ErrorInfoListForGetTraceDetailOutput {

    /**
     * @type {string}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    ErrorKind?: string;

    /**
     * @type {string}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    ErrorMessage?: string;

    /**
     * @type {number}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    ErrorOccurTime?: number;

    /**
     * @type {string}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    ErrorStack?: string;

    /**
     * @type {ErrorTagsForGetTraceDetailOutput}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    ErrorTags?: ErrorTagsForGetTraceDetailOutput;

    /**
     * @type {string}
     * @memberof ErrorInfoListForGetTraceDetailOutput
     */
    IssueId?: string;
}
