/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteTagRequest
 */
export interface DeleteTagRequest {

    /**
     * @type {string}
     * @memberof DeleteTagRequest
     */
    ProductId: string;

    /**
     * @type {Array<string>}
     * @memberof DeleteTagRequest
     */
    TagIdList?: Array<string>;
}
