/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RowForListHostOutput } from './row-for-list-host-output';
 /**
 * 
 *
 * @export
 * @interface ListHostResponse
 */
export interface ListHostResponse {

    /**
     * @type {string}
     * @memberof ListHostResponse
     */
    NextToken?: string;

    /**
     * @type {Array<RowForListHostOutput>}
     * @memberof ListHostResponse
     */
    Row?: Array<RowForListHostOutput>;
}
