/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PodStopRequest
 */
export interface PodStopRequest {

    /**
     * @type {string}
     * @memberof PodStopRequest
     */
    PodId: string;

    /**
     * @type {string}
     * @memberof PodStopRequest
     */
    ProductId: string;
}
