/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateTagRequest
 */
export interface UpdateTagRequest {

    /**
     * @type {string}
     * @memberof UpdateTagRequest
     */
    ProductId: string;

    /**
     * @type {string}
     * @memberof UpdateTagRequest
     */
    TagDesc?: string;

    /**
     * @type {string}
     * @memberof UpdateTagRequest
     */
    TagId: string;

    /**
     * @type {string}
     * @memberof UpdateTagRequest
     */
    TagName?: string;
}
