/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateAppRequest
 */
export interface UpdateAppRequest {

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    AppDesc?: string;

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    AppId: string;

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    AppMode?: string;

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    AppName?: string;

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    IconUrl?: string;

    /**
     * @type {string}
     * @memberof UpdateAppRequest
     */
    ProductId: string;

    /**
     * @type {number}
     * @memberof UpdateAppRequest
     */
    Rotation?: number;
}
