/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateProductResourceRequest
 */
export interface UpdateProductResourceRequest {

    /**
     * @type {number}
     * @memberof UpdateProductResourceRequest
     */
    ApplyDataSize?: number;

    /**
     * @type {string}
     * @memberof UpdateProductResourceRequest
     */
    ProductId: string;

    /**
     * @type {string}
     * @memberof UpdateProductResourceRequest
     */
    VolcRegion?: string;
}
