/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BitrateControlForGetExecutionOutput } from './bitrate-control-for-get-execution-output';
import { VolumeForGetExecutionOutput } from './volume-for-get-execution-output';
 /**
 * 
 *
 * @export
 * @interface AudioForGetExecutionOutput
 */
export interface AudioForGetExecutionOutput {

    /**
     * @type {BitrateControlForGetExecutionOutput}
     * @memberof AudioForGetExecutionOutput
     */
    BitrateControl?: BitrateControlForGetExecutionOutput;

    /**
     * @type {number}
     * @memberof AudioForGetExecutionOutput
     */
    Channels?: number;

    /**
     * @type {string}
     * @memberof AudioForGetExecutionOutput
     */
    Codec?: AudioForGetExecutionOutputCodecEnum;

    /**
     * @type {string}
     * @memberof AudioForGetExecutionOutput
     */
    Profile?: AudioForGetExecutionOutputProfileEnum;

    /**
     * @type {number}
     * @memberof AudioForGetExecutionOutput
     */
    SampleRate?: number;

    /**
     * @type {VolumeForGetExecutionOutput}
     * @memberof AudioForGetExecutionOutput
     */
    Volume?: VolumeForGetExecutionOutput;
}

/**
 * @export
 * @enum {string}
 */
export enum AudioForGetExecutionOutputCodecEnum {
    Aac = 'aac'
}
/**
 * @export
 * @enum {string}
 */
export enum AudioForGetExecutionOutputProfileEnum {
    AACLC = 'AAC-LC',
    HEAAC = 'HE-AAC',
    HEAACv2 = 'HE-AACv2'
}

