/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertConvertVideoForGetExecutionOutput } from './convert-convert-video-for-get-execution-output';
 /**
 * 
 *
 * @export
 * @interface ConvertVideoGenerationForGetExecutionOutput
 */
export interface ConvertVideoGenerationForGetExecutionOutput {

    /**
     * @type {number}
     * @memberof ConvertVideoGenerationForGetExecutionOutput
     */
    Duration?: number;

    /**
     * @type {string}
     * @memberof ConvertVideoGenerationForGetExecutionOutput
     */
    Model?: string;

    /**
     * @type {string}
     * @memberof ConvertVideoGenerationForGetExecutionOutput
     */
    Resolution?: string;

    /**
     * @type {ConvertConvertVideoForGetExecutionOutput}
     * @memberof ConvertVideoGenerationForGetExecutionOutput
     */
    Video?: ConvertConvertVideoForGetExecutionOutput;
}
