/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertConvertConvertConvertSegmentForGetExecutionOutput
 */
export interface ConvertConvertConvertConvertSegmentForGetExecutionOutput {

    /**
     * @type {string}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Description?: string;

    /**
     * @type {number}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    End?: number;

    /**
     * @type {string}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Location?: string;

    /**
     * @type {string}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Ocr?: string;

    /**
     * @type {number}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Score?: number;

    /**
     * @type {string}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Shot?: string;

    /**
     * @type {number}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    Start?: number;

    /**
     * @type {number}
     * @memberof ConvertConvertConvertConvertSegmentForGetExecutionOutput
     */
    VideoIndex?: number;
}
