/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertFpsControlForStartExecutionInput
 */
export interface ConvertFpsControlForStartExecutionInput {

    /**
     * @type {number}
     * @memberof ConvertFpsControlForStartExecutionInput
     */
    Fps?: number;

    /**
     * @type {string}
     * @memberof ConvertFpsControlForStartExecutionInput
     */
    Mode?: ConvertFpsControlForStartExecutionInputModeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ConvertFpsControlForStartExecutionInputModeEnum {
    Vfr = 'vfr',
    Cfr = 'cfr'
}

