/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StreamControlForGetExecutionOutput
 */
export interface StreamControlForGetExecutionOutput {

    /**
     * @type {string}
     * @memberof StreamControlForGetExecutionOutput
     */
    KeepAudioStreams?: StreamControlForGetExecutionOutputKeepAudioStreamsEnum;

    /**
     * @type {string}
     * @memberof StreamControlForGetExecutionOutput
     */
    KeepDataStreams?: StreamControlForGetExecutionOutputKeepDataStreamsEnum;

    /**
     * @type {string}
     * @memberof StreamControlForGetExecutionOutput
     */
    KeepVideoStreams?: StreamControlForGetExecutionOutputKeepVideoStreamsEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum StreamControlForGetExecutionOutputKeepAudioStreamsEnum {
    Null = 'null',
    All = 'all'
}
/**
 * @export
 * @enum {string}
 */
export enum StreamControlForGetExecutionOutputKeepDataStreamsEnum {
    All = 'all'
}
/**
 * @export
 * @enum {string}
 */
export enum StreamControlForGetExecutionOutputKeepVideoStreamsEnum {
    Null = 'null',
    All = 'all'
}

