/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertBitrateControlForGetExecutionOutput } from './convert-bitrate-control-for-get-execution-output';
import { FpsControlForGetExecutionOutput } from './fps-control-for-get-execution-output';
import { ScaleControlForGetExecutionOutput } from './scale-control-for-get-execution-output';
 /**
 * 
 *
 * @export
 * @interface VideoForGetExecutionOutput
 */
export interface VideoForGetExecutionOutput {

    /**
     * @type {number}
     * @memberof VideoForGetExecutionOutput
     */
    BitDepth?: number;

    /**
     * @type {ConvertBitrateControlForGetExecutionOutput}
     * @memberof VideoForGetExecutionOutput
     */
    BitrateControl?: ConvertBitrateControlForGetExecutionOutput;

    /**
     * @type {string}
     * @memberof VideoForGetExecutionOutput
     */
    Codec?: VideoForGetExecutionOutputCodecEnum;

    /**
     * @type {FpsControlForGetExecutionOutput}
     * @memberof VideoForGetExecutionOutput
     */
    FpsControl?: FpsControlForGetExecutionOutput;

    /**
     * @type {number}
     * @memberof VideoForGetExecutionOutput
     */
    HDRMode?: number;

    /**
     * @type {ScaleControlForGetExecutionOutput}
     * @memberof VideoForGetExecutionOutput
     */
    ScaleControl?: ScaleControlForGetExecutionOutput;
}

/**
 * @export
 * @enum {string}
 */
export enum VideoForGetExecutionOutputCodecEnum {
    H264 = 'h264',
    H265 = 'h265',
    H266 = 'h266'
}

