/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IPAddressListForDeleteIPSetInput } from './ipaddress-list-for-delete-ipset-input';
 /**
 * 
 *
 * @export
 * @interface DeleteIPSetForDeleteIPSetInput
 */
export interface DeleteIPSetForDeleteIPSetInput {

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    AccelerateRegion?: string;

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    AcceleratorId?: string;

    /**
     * @type {IPAddressListForDeleteIPSetInput}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    IPAddressList?: IPAddressListForDeleteIPSetInput;

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    IPSetId?: string;

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    IPVersion?: string;

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    IspType?: DeleteIPSetForDeleteIPSetInputIspTypeEnum;

    /**
     * @type {string}
     * @memberof DeleteIPSetForDeleteIPSetInput
     */
    State?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DeleteIPSetForDeleteIPSetInputIspTypeEnum {
    Advanced = 'Advanced'
}

