/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IPV6ForDescribeIPSetOutput
 */
export interface IPV6ForDescribeIPSetOutput {

    /**
     * @type {string}
     * @memberof IPV6ForDescribeIPSetOutput
     */
    Addr?: string;

    /**
     * @type {string}
     * @memberof IPV6ForDescribeIPSetOutput
     */
    ISP?: string;

    /**
     * @type {string}
     * @memberof IPV6ForDescribeIPSetOutput
     */
    ISPName?: string;
}
