/* tslint:disable */
/* eslint-disable */
/**
 * agentsphere
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MetadataForListSessionsOutput
 */
export interface MetadataForListSessionsOutput {

    /**
     * @type {string}
     * @memberof MetadataForListSessionsOutput
     */
    Value?: string;
}
