/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertFeatureGatesForListClustersOutput
 */
export interface ConvertFeatureGatesForListClustersOutput {

    /**
     * @type {boolean}
     * @memberof ConvertFeatureGatesForListClustersOutput
     */
    InPlacePodVerticalScaling?: boolean;

    /**
     * @type {boolean}
     * @memberof ConvertFeatureGatesForListClustersOutput
     */
    MaxUnavailableStatefulSet?: boolean;

    /**
     * @type {boolean}
     * @memberof ConvertFeatureGatesForListClustersOutput
     */
    StatefulSetAutoDeletePVC?: boolean;
}
