/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AdvancedConfigForCreateClusterInput } from './advanced-config-for-create-cluster-input';
import { ControlPlaneConfigForCreateClusterInput } from './control-plane-config-for-create-cluster-input';
 /**
 * 
 *
 * @export
 * @interface KubernetesConfigForCreateClusterInput
 */
export interface KubernetesConfigForCreateClusterInput {

    /**
     * @type {AdvancedConfigForCreateClusterInput}
     * @memberof KubernetesConfigForCreateClusterInput
     */
    AdvancedConfig?: AdvancedConfigForCreateClusterInput;

    /**
     * @type {string}
     * @memberof KubernetesConfigForCreateClusterInput
     */
    ClusterDomain?: string;

    /**
     * @type {ControlPlaneConfigForCreateClusterInput}
     * @memberof KubernetesConfigForCreateClusterInput
     */
    ControlPlaneConfig?: ControlPlaneConfigForCreateClusterInput;

    /**
     * @type {Array<string>}
     * @memberof KubernetesConfigForCreateClusterInput
     */
    CustomSans?: Array<string>;
}
