/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetadataForCreateSandboxInput } from './metadata-for-create-sandbox-input';
 /**
 * 
 *
 * @export
 * @interface AutoSnapshotConfigForCreateSandboxInput
 */
export interface AutoSnapshotConfigForCreateSandboxInput {

    /**
     * @type {string}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    CronExpression?: string;

    /**
     * @type {boolean}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    Enable?: boolean;

    /**
     * @type {number}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    MaxRetained?: number;

    /**
     * @type {MetadataForCreateSandboxInput}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    Metadata?: MetadataForCreateSandboxInput;

    /**
     * @type {number}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    RetentionDays?: number;

    /**
     * @type {string}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    SnapshotType?: string;

    /**
     * @type {string}
     * @memberof AutoSnapshotConfigForCreateSandboxInput
     */
    TimeZone?: string;
}
