/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BackendForUpdateFunctionInput } from './backend-for-update-function-input';
 /**
 * 
 *
 * @export
 * @interface ConvertMountPointForUpdateFunctionInput
 */
export interface ConvertMountPointForUpdateFunctionInput {

    /**
     * @type {BackendForUpdateFunctionInput}
     * @memberof ConvertMountPointForUpdateFunctionInput
     */
    Backend?: BackendForUpdateFunctionInput;

    /**
     * @type {string}
     * @memberof ConvertMountPointForUpdateFunctionInput
     */
    LocalMountPath?: string;

    /**
     * @type {boolean}
     * @memberof ConvertMountPointForUpdateFunctionInput
     */
    ReadOnly?: boolean;
}
