/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertMountPointForGetRevisionOutput
 */
export interface ConvertMountPointForGetRevisionOutput {

    /**
     * @type {string}
     * @memberof ConvertMountPointForGetRevisionOutput
     */
    BucketName?: string;

    /**
     * @type {string}
     * @memberof ConvertMountPointForGetRevisionOutput
     */
    BucketPath?: string;

    /**
     * @type {string}
     * @memberof ConvertMountPointForGetRevisionOutput
     */
    Endpoint?: string;

    /**
     * @type {string}
     * @memberof ConvertMountPointForGetRevisionOutput
     */
    LocalMountPath?: string;

    /**
     * @type {boolean}
     * @memberof ConvertMountPointForGetRevisionOutput
     */
    ReadOnly?: boolean;
}
