/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BackendForCreateFunctionInput } from './backend-for-create-function-input';
 /**
 * 
 *
 * @export
 * @interface ConvertMountPointForCreateFunctionInput
 */
export interface ConvertMountPointForCreateFunctionInput {

    /**
     * @type {BackendForCreateFunctionInput}
     * @memberof ConvertMountPointForCreateFunctionInput
     */
    Backend?: BackendForCreateFunctionInput;

    /**
     * @type {string}
     * @memberof ConvertMountPointForCreateFunctionInput
     */
    LocalMountPath?: string;

    /**
     * @type {boolean}
     * @memberof ConvertMountPointForCreateFunctionInput
     */
    ReadOnly?: boolean;
}
