/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MountPointForCreateFunctionInput } from './mount-point-for-create-function-input';
 /**
 * 
 *
 * @export
 * @interface EfsMountConfigForCreateFunctionInput
 */
export interface EfsMountConfigForCreateFunctionInput {

    /**
     * @type {Array<MountPointForCreateFunctionInput>}
     * @memberof EfsMountConfigForCreateFunctionInput
     */
    MountPoints?: Array<MountPointForCreateFunctionInput>;
}
