/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MountPointForGetFunctionOutput } from './mount-point-for-get-function-output';
 /**
 * 
 *
 * @export
 * @interface EfsMountConfigForGetFunctionOutput
 */
export interface EfsMountConfigForGetFunctionOutput {

    /**
     * @type {Array<MountPointForGetFunctionOutput>}
     * @memberof EfsMountConfigForGetFunctionOutput
     */
    MountPoints?: Array<MountPointForGetFunctionOutput>;
}
