/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EncryptionConfigForCreateSandboxInput
 */
export interface EncryptionConfigForCreateSandboxInput {

    /**
     * @type {boolean}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    EnableSSE?: boolean;

    /**
     * @type {string}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    EncryptionAlgorithm?: string;

    /**
     * @type {string}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    EncryptionMethod?: string;

    /**
     * @type {string}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    KMSMasterKeyID?: string;

    /**
     * @type {string}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    SSECKey?: string;

    /**
     * @type {string}
     * @memberof EncryptionConfigForCreateSandboxInput
     */
    SSECMD5?: string;
}
