/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowEgressForListSandboxesOutput } from './allow-egress-for-list-sandboxes-output';
import { DenyEgressForListSandboxesOutput } from './deny-egress-for-list-sandboxes-output';
 /**
 * 
 *
 * @export
 * @interface NetworkRulesForListSandboxesOutput
 */
export interface NetworkRulesForListSandboxesOutput {

    /**
     * @type {Array<AllowEgressForListSandboxesOutput>}
     * @memberof NetworkRulesForListSandboxesOutput
     */
    AllowEgress?: Array<AllowEgressForListSandboxesOutput>;

    /**
     * @type {boolean}
     * @memberof NetworkRulesForListSandboxesOutput
     */
    AllowEgressAccess?: boolean;

    /**
     * @type {Array<DenyEgressForListSandboxesOutput>}
     * @memberof NetworkRulesForListSandboxesOutput
     */
    DenyEgress?: Array<DenyEgressForListSandboxesOutput>;

    /**
     * @type {number}
     * @memberof NetworkRulesForListSandboxesOutput
     */
    MaxEgressCps?: number;
}
