/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EBSVolumeForDescribeSandboxSnapshotOutput } from './ebsvolume-for-describe-sandbox-snapshot-output';
import { MetadataForDescribeSandboxSnapshotOutput } from './metadata-for-describe-sandbox-snapshot-output';
import { SidecarForDescribeSandboxSnapshotOutput } from './sidecar-for-describe-sandbox-snapshot-output';
 /**
 * 
 *
 * @export
 * @interface SandboxInfoForDescribeSandboxSnapshotOutput
 */
export interface SandboxInfoForDescribeSandboxSnapshotOutput {

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    AssignStatus?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    AvailabilityZone?: string;

    /**
     * @type {number}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    CpuMilli?: number;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    CreatedAt?: string;

    /**
     * @type {Array<EBSVolumeForDescribeSandboxSnapshotOutput>}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    EBSVolumes?: Array<EBSVolumeForDescribeSandboxSnapshotOutput>;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    ErrorCode?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    ErrorMessage?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    ExpireAt?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    FunctionId?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Id?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Image?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    InstanceType?: string;

    /**
     * @type {number}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    MemoryMB?: number;

    /**
     * @type {MetadataForDescribeSandboxSnapshotOutput}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Metadata?: MetadataForDescribeSandboxSnapshotOutput;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    PausedAt?: string;

    /**
     * @type {boolean}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Pending?: boolean;

    /**
     * @type {number}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    RevisionNumber?: number;

    /**
     * @type {Array<string>}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    RoleChainTrn?: Array<string>;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    RoleTrn?: string;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    SessionId?: string;

    /**
     * @type {Array<SidecarForDescribeSandboxSnapshotOutput>}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Sidecars?: Array<SidecarForDescribeSandboxSnapshotOutput>;

    /**
     * @type {string}
     * @memberof SandboxInfoForDescribeSandboxSnapshotOutput
     */
    Status?: string;
}
