/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetadataForDescribeSandboxSnapshotOutput } from './metadata-for-describe-sandbox-snapshot-output';
import { SandboxInfoForDescribeSandboxSnapshotOutput } from './sandbox-info-for-describe-sandbox-snapshot-output';
 /**
 * 
 *
 * @export
 * @interface SnapshotForDescribeSandboxSnapshotOutput
 */
export interface SnapshotForDescribeSandboxSnapshotOutput {

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    CreatedAt?: string;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    CreatedByJobId?: string;

    /**
     * @type {MetadataForDescribeSandboxSnapshotOutput}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    Metadata?: MetadataForDescribeSandboxSnapshotOutput;

    /**
     * @type {number}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    RetentionDays?: number;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    RetentionExpiresAt?: string;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    SandboxId?: string;

    /**
     * @type {SandboxInfoForDescribeSandboxSnapshotOutput}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    SandboxInfo?: SandboxInfoForDescribeSandboxSnapshotOutput;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    SnapshotId?: string;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    SnapshotType?: string;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    Source?: string;

    /**
     * @type {string}
     * @memberof SnapshotForDescribeSandboxSnapshotOutput
     */
    Status?: string;
}
