/* tslint:disable */
/* eslint-disable */
/**
 * cpaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateListForCreateTemplateV2Input } from './template-list-for-create-template-v2-input';
 /**
 * 
 *
 * @export
 * @interface CreateTemplateV2Request
 */
export interface CreateTemplateV2Request {

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    BusinessType?: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    EnableShortUrl?: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    Language?: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    SceneTemplateName: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    SendAudit?: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    Signature?: string;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    SubAccountId?: string;

    /**
     * @type {Array<TemplateListForCreateTemplateV2Input>}
     * @memberof CreateTemplateV2Request
     */
    TemplateList?: Array<TemplateListForCreateTemplateV2Input>;

    /**
     * @type {string}
     * @memberof CreateTemplateV2Request
     */
    WabaId?: string;
}
