/* tslint:disable */
/* eslint-disable */
/**
 * cpaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForCreateTemplateV2Output
 */
export interface DataForCreateTemplateV2Output {

    /**
     * @type {string}
     * @memberof DataForCreateTemplateV2Output
     */
    SceneTemplateCode?: string;

    /**
     * @type {string}
     * @memberof DataForCreateTemplateV2Output
     */
    SceneTemplateName?: string;
}
