/* tslint:disable */
/* eslint-disable */
/**
 * insight
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResultForExpertInvokeAPIOutput } from './result-for-expert-invoke-apioutput';
 /**
 * 
 *
 * @export
 * @interface ExpertInvokeAPIResponse
 */
export interface ExpertInvokeAPIResponse {

    /**
     * @type {ResultForExpertInvokeAPIOutput}
     * @memberof ExpertInvokeAPIResponse
     */
    Result?: ResultForExpertInvokeAPIOutput;
}
