/* tslint:disable */
/* eslint-disable */
/**
 * insight
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LocationForPullPostOutput } from './location-for-pull-post-output';
 /**
 * 
 *
 * @export
 * @interface ItemDocForPullPostOutput
 */
export interface ItemDocForPullPostOutput {

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Asr?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Content?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    CoverUrl?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    DedupID?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Emotion?: string;

    /**
     * @type {number}
     * @memberof ItemDocForPullPostOutput
     */
    FansCount?: number;

    /**
     * @type {boolean}
     * @memberof ItemDocForPullPostOutput
     */
    IsFollow?: boolean;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    MainDomain?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    MediaName?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Ocr?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    OcrHigh?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    PostID?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    PublishTime?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Reason?: string;

    /**
     * @type {Array<string>}
     * @memberof ItemDocForPullPostOutput
     */
    RiskType?: Array<string>;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Summary?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Title?: string;

    /**
     * @type {string}
     * @memberof ItemDocForPullPostOutput
     */
    Url?: string;

    /**
     * @type {Array<LocationForPullPostOutput>}
     * @memberof ItemDocForPullPostOutput
     */
    locations?: Array<LocationForPullPostOutput>;
}
