/* tslint:disable */
/* eslint-disable */
/**
 * insight
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TaskListForGetTaskListOutput
 */
export interface TaskListForGetTaskListOutput {

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    Status?: string;

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    SubTaskType?: string;

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    TaskCategory?: string;

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    TaskID?: string;

    /**
     * @type {string}
     * @memberof TaskListForGetTaskListOutput
     */
    TaskName?: string;
}
