/* tslint:disable */
/* eslint-disable */
/**
 * partner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListForListChildPartnerCustomerOutput
 */
export interface ListForListChildPartnerCustomerOutput {

    /**
     * @type {number}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    AlarmStatus?: number;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    AlarmValue?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    ChildPartnerName?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    ChildPartnerPassportID?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    CustomerName?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    CustomerPassportID?: string;

    /**
     * @type {number}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    GrantType?: number;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    PaidCurMonth?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    PaidLastMonth?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    PayableCurMonth?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    PayableLastMonth?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    QuotaBalance?: string;

    /**
     * @type {string}
     * @memberof ListForListChildPartnerCustomerOutput
     */
    RelationTime?: string;
}
